package source

import "testing"

// 실측 사례: restrooms 만 구독하는 realtime 파이프라인이 같은 DB 의 child_meal_stores
// CREATE/DROP/ALTER/TRUNCATE 에 schema_changed 로 정지했다. 이 파서가 그 판정의 근거다.
func TestDDLTarget(t *testing.T) {
	cases := []struct {
		name       string
		sql        string
		wantSchema string
		wantTable  string
		wantOK     bool
	}{
		{
			name:       "ALTER TABLE",
			sql:        "ALTER TABLE targetdb.child_meal_stores\n  MODIFY lat VARCHAR(24)",
			wantSchema: "targetdb", wantTable: "child_meal_stores", wantOK: true,
		},
		{
			name:       "서버 생성 DROP — 백틱과 주석이 붙는다",
			sql:        "DROP TABLE IF EXISTS `targetdb`.`child_meal_stores` /* generated by server */",
			wantSchema: "targetdb", wantTable: "child_meal_stores", wantOK: true,
		},
		{
			name:       "CREATE TABLE IF NOT EXISTS",
			sql:        "CREATE TABLE IF NOT EXISTS targetdb.child_meal_stores (\n  store_key VARCHAR(160)\n)",
			wantSchema: "targetdb", wantTable: "child_meal_stores", wantOK: true,
		},
		{
			name:       "TRUNCATE",
			sql:        "TRUNCATE targetdb.child_meal_stores",
			wantSchema: "targetdb", wantTable: "child_meal_stores", wantOK: true,
		},
		{
			name:       "TRUNCATE TABLE",
			sql:        "TRUNCATE TABLE targetdb.restrooms",
			wantSchema: "targetdb", wantTable: "restrooms", wantOK: true,
		},
		{
			name:       "스키마 없는 ALTER — 호출자가 binlog schema 로 채운다",
			sql:        "ALTER TABLE restrooms ADD COLUMN x INT",
			wantSchema: "", wantTable: "restrooms", wantOK: true,
		},
		{
			name:       "RENAME TABLE — 첫 대상만 본다",
			sql:        "RENAME TABLE targetdb.old_name TO targetdb.new_name",
			wantSchema: "targetdb", wantTable: "old_name", wantOK: true,
		},
		{
			name:       "CREATE INDEX — 대상은 ON 뒤",
			sql:        "CREATE INDEX idx_x ON targetdb.restrooms (col)",
			wantSchema: "targetdb", wantTable: "restrooms", wantOK: true,
		},
		{
			name:       "DROP INDEX — 대상은 ON 뒤",
			sql:        "DROP INDEX idx_x ON `targetdb`.`restrooms`",
			wantSchema: "targetdb", wantTable: "restrooms", wantOK: true,
		},
		{
			name:   "알아볼 수 없는 DDL 은 ok=false — 호출자가 보수적으로 다뤄야 한다",
			sql:    "CREATE DATABASE otherdb",
			wantOK: false,
		},
		{
			name:       "소문자 alter 도 인식한다",
			sql:        "alter table `targetdb`.`restrooms` add column y int",
			wantSchema: "targetdb", wantTable: "restrooms", wantOK: true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			schema, table, ok := ddlTarget(tc.sql)
			if ok != tc.wantOK {
				t.Fatalf("ok=%v, want %v (sql=%q)", ok, tc.wantOK, tc.sql)
			}
			if !ok {
				return
			}
			if schema != tc.wantSchema {
				t.Errorf("schema=%q, want %q", schema, tc.wantSchema)
			}
			if table != tc.wantTable {
				t.Errorf("table=%q, want %q", table, tc.wantTable)
			}
		})
	}
}

// 주석 안의 키워드가 대상으로 오인되면 무관한 테이블에서 정지가 발생한다.
func TestDDLTarget_IgnoresCommentContent(t *testing.T) {
	sql := "/* ALTER TABLE decoy.table1 */ ALTER TABLE real.table2 ADD COLUMN x INT"
	schema, table, ok := ddlTarget(sql)
	if !ok {
		t.Fatal("주석을 제거한 뒤 실제 DDL 을 인식해야 한다")
	}
	if schema != "real" || table != "table2" {
		t.Errorf("got %s.%s, want real.table2", schema, table)
	}
}

func TestDDLInScope(t *testing.T) {
	cases := []struct {
		name     string
		tables   []string
		database string
		schema   string
		table    string
		parsed   bool
		want     bool
	}{
		{
			name:   "구독 목록이 비면 전체 구독",
			tables: nil, schema: "targetdb", table: "anything", parsed: true, want: true,
		},
		{
			name:   "구독 중인 테이블의 DDL 은 통과 — 방어가 살아있어야 한다",
			tables: []string{`targetdb\.restrooms`},
			schema: "targetdb", table: "restrooms", parsed: true, want: true,
		},
		{
			name: "구독하지 않는 테이블의 DDL 은 차단 — 실측 오정지 사례",
			// restrooms 만 구독하는데 child_meal_stores 를 만들자 정지했다.
			tables: []string{`targetdb\.restrooms`},
			schema: "targetdb", table: "child_meal_stores", parsed: true, want: false,
		},
		{
			name:   "파싱 실패는 통과시킨다 — 못 읽었다고 방어를 뚫지 않는다",
			tables: []string{`targetdb\.restrooms`},
			parsed: false, want: true,
		},
		{
			name:     "스키마가 비면 소스의 database 로 채워 대조한다",
			tables:   []string{`targetdb\.restrooms`},
			database: "targetdb", schema: "", table: "restrooms", parsed: true, want: true,
		},
		{
			name:   "다른 스키마의 동명 테이블은 차단",
			tables: []string{`targetdb\.restrooms`},
			schema: "otherdb", table: "restrooms", parsed: true, want: false,
		},
		{
			name:   "정규식 와일드카드 구독",
			tables: []string{`targetdb\..*`},
			schema: "targetdb", table: "child_meal_stores", parsed: true, want: true,
		},
		{
			name:   "여러 테이블 중 하나라도 맞으면 통과",
			tables: []string{`targetdb\.restrooms`, `targetdb\.child_meal_stores`},
			schema: "targetdb", table: "child_meal_stores", parsed: true, want: true,
		},
		{
			name:   "잘못된 정규식은 일치로 본다 — 구독 테이블 DDL 을 놓치지 않는다",
			tables: []string{`targetdb\.[invalid`},
			schema: "targetdb", table: "restrooms", parsed: true, want: true,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			s := &CDCSource{tables: tc.tables, database: tc.database}
			if got := s.ddlInScope(tc.schema, tc.table, tc.parsed); got != tc.want {
				t.Errorf("ddlInScope(%q, %q, %v) = %v, want %v",
					tc.schema, tc.table, tc.parsed, got, tc.want)
			}
		})
	}
}
