package source

import (
	"regexp"
	"strings"
)

// DDL 이벤트는 row 이벤트와 달리 canal 의 IncludeTableRegex 필터를 타지 않는다.
// canal 은 스키마 캐시 갱신을 위해 모든 DDL 을 OnDDL 로 전달하기 때문이다.
//
// 그래서 구독하지 않는 테이블의 DDL 까지 파이프라인에 흘러가고, DDL 방어가 켜져 있으면
// (executor 의 on_ddl != "allow") 무관한 테이블 변경에 파이프라인이 정지했다.
//
// 실측: restrooms 만 구독하는 realtime 파이프라인이, 같은 DB 의 다른 테이블
// child_meal_stores 를 CREATE 하자 schema_changed 로 정지했다.
//
// 여기서 DDL 문의 대상 테이블을 뽑아 CDCEvent.Table 을 채우고, 구독 범위 밖이면
// 이벤트를 만들지 않는다.

// DDL 문에서 대상 테이블을 뽑는 패턴들.
//
// 목표는 완전한 SQL 파서가 아니다 — binlog 의 DDL 은 서버가 정규화해 보내므로 형태가
// 제한적이고, 못 알아본 경우는 "구독 대상일 수 있다"고 보수적으로 판정해 방어를 유지한다.
// 완벽한 파싱을 노리다 오탐으로 방어를 뚫는 것보다, 못 읽으면 멈추는 쪽이 안전하다.
var ddlTablePatterns = []*regexp.Regexp{
	// ALTER TABLE / DROP TABLE / RENAME TABLE / TRUNCATE [TABLE] / CREATE TABLE
	regexp.MustCompile(`(?is)^\s*ALTER\s+(?:ONLINE\s+|OFFLINE\s+|IGNORE\s+)*TABLE\s+(` + ddlNameRe + `)`),
	regexp.MustCompile(`(?is)^\s*DROP\s+(?:TEMPORARY\s+)?TABLE\s+(?:IF\s+EXISTS\s+)?(` + ddlNameRe + `)`),
	regexp.MustCompile(`(?is)^\s*RENAME\s+TABLE\s+(` + ddlNameRe + `)`),
	regexp.MustCompile(`(?is)^\s*TRUNCATE\s+(?:TABLE\s+)?(` + ddlNameRe + `)`),
	regexp.MustCompile(`(?is)^\s*CREATE\s+(?:TEMPORARY\s+)?TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?(` + ddlNameRe + `)`),
	// 인덱스는 대상 테이블이 ON 뒤에 온다
	regexp.MustCompile(`(?is)^\s*CREATE\s+(?:UNIQUE\s+|FULLTEXT\s+|SPATIAL\s+)?INDEX\s+` + ddlNameRe + `\s+ON\s+(` + ddlNameRe + `)`),
	regexp.MustCompile(`(?is)^\s*DROP\s+INDEX\s+` + ddlNameRe + `\s+ON\s+(` + ddlNameRe + `)`),
}

// 식별자: 백틱 인용 또는 비인용, 옵션으로 `db`.`table` 형태.
const ddlNameRe = "(?:`[^`]+`|[A-Za-z0-9_$]+)(?:\\s*\\.\\s*(?:`[^`]+`|[A-Za-z0-9_$]+))?"

// ddlTarget 은 DDL SQL 의 대상 스키마·테이블을 반환한다.
// 스키마가 SQL 에 없으면 schema 는 빈 문자열이다(호출자가 binlog 의 schema 로 채운다).
// 알아보지 못하면 ok=false — 호출자는 이를 "판정 불가"로 다뤄야 한다.
func ddlTarget(ddlSQL string) (schema, table string, ok bool) {
	stripped := stripDDLComments(ddlSQL)
	for _, re := range ddlTablePatterns {
		m := re.FindStringSubmatch(stripped)
		if m == nil {
			continue
		}
		s, t := splitQualifiedName(m[1])
		if t == "" {
			continue
		}
		return s, t, true
	}
	return "", "", false
}

// 서버가 생성한 DDL 에는 `/* generated by server */` 같은 주석이 붙는다.
// 주석 안의 단어가 패턴에 걸리는 것을 막는다.
var (
	ddlBlockComment = regexp.MustCompile(`(?s)/\*.*?\*/`)
	ddlLineComment  = regexp.MustCompile(`(?m)(?:--[ \t][^\n]*|#[^\n]*)`)
)

func stripDDLComments(sql string) string {
	sql = ddlBlockComment.ReplaceAllString(sql, " ")
	sql = ddlLineComment.ReplaceAllString(sql, " ")
	return sql
}

// splitQualifiedName 은 `db`.`table` 또는 db.table 또는 table 을 분해한다.
func splitQualifiedName(name string) (schema, table string) {
	parts := strings.SplitN(name, ".", 2)
	if len(parts) == 2 {
		return unquoteIdent(parts[0]), unquoteIdent(parts[1])
	}
	return "", unquoteIdent(parts[0])
}

func unquoteIdent(s string) string {
	s = strings.TrimSpace(s)
	s = strings.Trim(s, "`")
	return strings.TrimSpace(s)
}

// ddlInScope 는 이 DDL 이 구독 범위에 드는지 판정한다.
//
// tables 가 비면 전체 구독이므로 항상 true.
// 대상 테이블을 못 읽어냈으면 true — 방어를 뚫지 않기 위해 보수적으로 판정한다.
func (s *CDCSource) ddlInScope(schema, table string, parsed bool) bool {
	if len(s.tables) == 0 {
		return true
	}
	if !parsed {
		return true
	}
	if schema == "" {
		schema = s.database
	}
	return matchesTableFilter(s.tables, schema, table)
}

// matchesTableFilter 는 canal 의 IncludeTableRegex 와 같은 규칙으로 대조한다.
// 패턴은 `db\.table` 형식의 정규식이며, canal 은 전체 일치로 다룬다.
func matchesTableFilter(patterns []string, schema, table string) bool {
	qualified := schema + "." + table
	for _, p := range patterns {
		re, err := regexp.Compile("^" + strings.TrimSuffix(strings.TrimPrefix(p, "^"), "$") + "$")
		if err != nil {
			// 잘못된 패턴은 canal 쪽에서도 실패한다. 여기서 조용히 제외하면
			// 구독 중인 테이블의 DDL 을 놓칠 수 있으므로 일치로 본다.
			return true
		}
		if re.MatchString(qualified) || re.MatchString(table) {
			return true
		}
	}
	return false
}
