import { useEffect, useState, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  Card,
  CardContent,
  Button,
  Box,
  Stack,
  CircularProgress,
  Typography,
  Tabs,
  Tab,
  Breadcrumbs,
  Link,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  Switch,
  FormControlLabel,
  Divider,
  Chip,
  FormHelperText,
} from '@mui/material'
import ArrowBackIcon from '@mui/icons-material/ArrowBack'
import SaveIcon from '@mui/icons-material/Save'
import ApiIcon from '@mui/icons-material/Api'
import StorageIcon from '@mui/icons-material/Storage'
import CloudIcon from '@mui/icons-material/Cloud'
import InsertDriveFileIcon from '@mui/icons-material/InsertDriveFile'
import BoltIcon from '@mui/icons-material/Bolt'
import SyncIcon from '@mui/icons-material/Sync'
import { useTranslation } from 'react-i18next'
import Editor from '@monaco-editor/react'
import yaml from 'js-yaml'
import { api } from '../services/api'
import type { WorkflowSource, WorkflowPipeline, RateLimitConfig, RealtimePipelineMode, PaginationType } from '../types/pipeline'
import { createDefaultStages, removeAutoGeneratedStages } from '../utils/defaultStages'
import { useSnackbar } from '../hooks/useSnackbar'

// Source 타입 정의
type SourceType = 'rest_api' | 'kafka' | 'cdc' | 'sql' | 'file' | 'sql_event' | 'kubernetes'

interface Workflow {
  id: string
  name: string
  slug: string
  type: 'batch' | 'realtime'
  project_id: string
  pipelines?: WorkflowPipeline[]
  project?: {
    id: string
    name: string
    alias: string
  }
}

// Source 타입별 설정
const sourceTypeConfig: Record<SourceType, { color: string; icon: React.ReactNode; label: string }> = {
  rest_api: { color: '#1976d2', icon: <ApiIcon fontSize="small" />, label: 'REST API' },
  kafka: { color: '#4caf50', icon: <BoltIcon fontSize="small" />, label: 'Kafka' },
  cdc: { color: '#9c27b0', icon: <SyncIcon fontSize="small" />, label: 'CDC' },
  sql: { color: '#ff9800', icon: <StorageIcon fontSize="small" />, label: 'SQL' },
  file: { color: '#00bcd4', icon: <InsertDriveFileIcon fontSize="small" />, label: 'File' },
  sql_event: { color: '#e91e63', icon: <CloudIcon fontSize="small" />, label: 'SQL Event' },
  kubernetes: { color: '#3f51b5', icon: <CloudIcon fontSize="small" />, label: 'Kubernetes Logs' },
}

// 워크플로우 타입별 사용 가능한 소스 타입
const sourceTypesByWorkflow: Record<'batch' | 'realtime', SourceType[]> = {
  batch: ['rest_api', 'sql', 'file'],
  realtime: ['rest_api', 'kafka', 'cdc', 'sql_event', 'kubernetes'],
}

// 실시간 소스 타입별 자동 설정되는 realtime_mode (강제)
const autoRealtimeModeBySourceType: Record<string, RealtimePipelineMode> = {
  cdc: 'cdc',        // CDC는 당연히 cdc 모드
  sql_event: 'raw',  // SQL Event는 단순 폴링이므로 raw 모드
  kubernetes: 'raw', // K8s Logs는 로그 스트리밍이므로 raw 모드
}

// 실시간 소스 타입별 권장 realtime_mode (선택 가능)
const recommendedRealtimeModeBySourceType: Record<string, RealtimePipelineMode> = {
  rest_api: 'cdc',   // REST API는 cdc/raw 둘 다 가능, 기본은 cdc 권장
  kafka: 'cdc',      // Kafka는 보통 Debezium 등 CDC 커넥터와 사용하지만 raw도 가능
}

// Form state interface
interface FormState {
  type: SourceType
  name: string
  // REST API
  url: string
  method: string
  headers: string
  query_params: string
  body: string
  // Pagination
  pagination_type: PaginationType | 'none' | ''
  pagination_page_param: string
  pagination_start_value: number | ''
  pagination_data_field: string
  pagination_url_path: string
  pagination_offset_param: string
  pagination_offset_path: string
  pagination_current_count_path: string
  pagination_per_page_path: string
  // Kafka
  brokers: string
  topic: string
  group_id: string
  offset: string
  // CDC
  connection_string: string
  database: string
  table: string
  slot_name: string
  // SQL
  query: string
  fetch_size: number | ''
  // File
  path: string
  format: string
  delimiter: string
  // SQL Event
  poll_interval: string
  watermark_column: string
  // Kubernetes
  namespace: string
  pod_selector: string
  container_name: string
  follow: boolean
  tail_lines: number | ''
  since_seconds: number | ''
  log_format: string
  log_pattern: string
  kubeconfig: string
  context: string
  // Rate Limit
  rate_limit_enabled: boolean
  rate_limit_rate: number | ''
  rate_limit_interval: RateLimitConfig['interval']
  rate_limit_burst: number | ''
  rate_limit_strategy: RateLimitConfig['strategy']
  // Partition (batch 소스용)
  partition_enabled: boolean
  partition_mode: 'discovery' | 'static'
  partition_discovery_url: string
  partition_discovery_query: string
  partition_id_path: string
  partition_url_template: string
  partition_query_template: string
  partition_static_list: string  // 쉼표로 구분된 파티션 ID 목록
  partition_parallelism: number | ''
  // Batch Processing (파이프라인 레벨)
  // Stage는 항상 병렬 처리, Sink만 bulk/individual 선택
  batch_enabled: boolean
  batch_output_mode: 'bulk' | 'individual'
  batch_size: number | ''
  batch_workers: number | ''
  batch_flush_interval: string
}

const initialFormState: FormState = {
  type: 'rest_api',
  name: '',
  url: '',
  method: 'GET',
  headers: '',
  query_params: '',
  body: '',
  pagination_type: '',
  pagination_page_param: '',
  pagination_start_value: '',
  pagination_data_field: '',
  pagination_url_path: '',
  pagination_offset_param: '',
  pagination_offset_path: '',
  pagination_current_count_path: '',
  pagination_per_page_path: '',
  brokers: '',
  topic: '',
  group_id: '',
  offset: 'latest',
  connection_string: '',
  database: '',
  table: '',
  slot_name: '',
  query: '',
  fetch_size: 1000,
  path: '',
  format: 'json',
  delimiter: '',
  poll_interval: '1m',
  watermark_column: '',
  namespace: '',
  pod_selector: '',
  container_name: '',
  follow: true,
  tail_lines: 100,
  since_seconds: '',
  log_format: 'auto',
  log_pattern: '',
  kubeconfig: '',
  context: '',
  rate_limit_enabled: false,
  rate_limit_rate: '',
  rate_limit_interval: 'second',
  rate_limit_burst: '',
  rate_limit_strategy: 'token_bucket',
  // Partition
  partition_enabled: false,
  partition_mode: 'static',
  partition_discovery_url: '',
  partition_discovery_query: '',
  partition_id_path: 'partitions',
  partition_url_template: '',
  partition_query_template: '',
  partition_static_list: '',
  partition_parallelism: 4,
  // Batch Processing
  batch_enabled: false,
  batch_output_mode: 'bulk',
  batch_size: 100,
  batch_workers: 20,
  batch_flush_interval: '5s',
}

export default function SourceEditorPage() {
  const { t } = useTranslation()
  const { projectAlias, workflowId, pipelineId } = useParams<{
    projectAlias: string
    workflowId: string
    pipelineId: string
  }>()
  const navigate = useNavigate()
  const { showSuccess, showError, showWarning, showInfo } = useSnackbar()

  const [workflow, setWorkflow] = useState<Workflow | null>(null)
  const [pipeline, setPipeline] = useState<WorkflowPipeline | null>(null)
  const [source, setSource] = useState<WorkflowSource | null>(null)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [testingConnection, setTestingConnection] = useState(false)

  // Edit mode
  const [editMode, setEditMode] = useState<'visual' | 'yaml'>('visual')
  const [yamlContent, setYamlContent] = useState<string>('')
  const [yamlError, setYamlError] = useState<string | null>(null)

  // Form state
  const [formState, setFormState] = useState<FormState>(initialFormState)
  const [formErrors, setFormErrors] = useState<Record<string, string>>({})

  // Update form field
  const updateFormField = useCallback(<K extends keyof FormState>(field: K, value: FormState[K]) => {
    setFormState(prev => ({ ...prev, [field]: value }))
    // Clear error when field is updated
    if (formErrors[field]) {
      setFormErrors(prev => {
        const newErrors = { ...prev }
        delete newErrors[field]
        return newErrors
      })
    }
  }, [formErrors])

  const fetchData = useCallback(async () => {
    try {
      setLoading(true)
      const res = await api.getWorkflow(workflowId!)
      if (res.success && res.data) {
        setWorkflow(res.data)

        const pipelines = res.data.pipelines || []
        const found = pipelines.find((p: WorkflowPipeline) => p.id === pipelineId)
        if (found) {
          setPipeline(found)
          const sourceData = found.source || createDefaultSource(res.data.type)
          setSource(sourceData)
          setYamlContent(yaml.dump(sourceData, { indent: 2 }))

          // Initialize form state from source data
          const newFormState: FormState = {
            ...initialFormState,
            type: sourceData.type as SourceType,
            name: sourceData.name || '',
            // Rate limit
            rate_limit_enabled: sourceData.rate_limit?.enabled || false,
            rate_limit_rate: sourceData.rate_limit?.rate || '',
            rate_limit_interval: sourceData.rate_limit?.interval || 'second',
            rate_limit_burst: sourceData.rate_limit?.burst || '',
            rate_limit_strategy: sourceData.rate_limit?.strategy || 'token_bucket',
          }

          // Load config fields based on type
          const config = sourceData.config || {}
          switch (sourceData.type) {
            case 'rest_api':
              newFormState.url = config.url as string || ''
              newFormState.method = config.method as string || 'GET'
              newFormState.headers = config.headers ? JSON.stringify(config.headers, null, 2) : ''
              newFormState.query_params = config.query_params ? JSON.stringify(config.query_params, null, 2) : ''
              newFormState.body = config.body as string || ''
              // Pagination
              {
              const pagination = config.pagination as Record<string, unknown> | undefined
              if (pagination && pagination.type) {
                newFormState.pagination_type = pagination.type as PaginationType
                newFormState.pagination_data_field = pagination.data_field as string || ''
                switch (pagination.type) {
                  case 'page_increment':
                    newFormState.pagination_page_param = pagination.param_name as string || ''
                    newFormState.pagination_start_value = pagination.start_value as number || ''
                    break
                  case 'next_url':
                    newFormState.pagination_url_path = pagination.url_path as string || ''
                    break
                  case 'next_offset':
                    newFormState.pagination_offset_param = pagination.offset_param as string || ''
                    newFormState.pagination_offset_path = pagination.offset_path as string || ''
                    break
                  case 'page_with_count':
                    newFormState.pagination_page_param = pagination.page_param as string || ''
                    newFormState.pagination_start_value = pagination.start_value as number || ''
                    newFormState.pagination_current_count_path = pagination.current_count_path as string || ''
                    newFormState.pagination_per_page_path = pagination.per_page_path as string || ''
                    break
                }
              }
              }
              // Partition (HTTP)
              {
              const partition = config.partition as Record<string, unknown> | undefined
              if (partition) {
                newFormState.partition_enabled = true
                newFormState.partition_parallelism = partition.parallelism as number || 4
                if (partition.static_partitions) {
                  newFormState.partition_mode = 'static'
                  newFormState.partition_static_list = (partition.static_partitions as string[]).join(', ')
                } else if (partition.discovery_url) {
                  newFormState.partition_mode = 'discovery'
                  newFormState.partition_discovery_url = partition.discovery_url as string || ''
                  // partition_id_path 또는 하위 호환: partition_list_path + partition_id_field
                  if (partition.partition_id_path) {
                    newFormState.partition_id_path = partition.partition_id_path as string
                  } else {
                    const listPath = (partition.partition_list_path as string) || 'partitions'
                    const idField = partition.partition_id_field as string
                    newFormState.partition_id_path = idField ? `${listPath}.[*].${idField}` : listPath
                  }
                }
                newFormState.partition_url_template = partition.url_template as string || ''
              }
              }
              break
            case 'kafka':
              newFormState.brokers = config.brokers as string || ''
              newFormState.topic = config.topic as string || ''
              newFormState.group_id = config.group_id as string || ''
              newFormState.offset = config.offset as string || 'latest'
              break
            case 'cdc':
              newFormState.connection_string = config.connection_string as string || ''
              newFormState.database = config.database as string || ''
              newFormState.table = config.table as string || ''
              newFormState.slot_name = config.slot_name as string || ''
              break
            case 'sql':
              newFormState.connection_string = config.connection_string as string || ''
              newFormState.query = config.query as string || ''
              newFormState.fetch_size = config.fetch_size as number || 1000
              // Partition (SQL)
              {
              const partition = config.partition as Record<string, unknown> | undefined
              if (partition) {
                newFormState.partition_enabled = true
                newFormState.partition_parallelism = partition.parallelism as number || 4
                if (partition.static_partitions) {
                  newFormState.partition_mode = 'static'
                  newFormState.partition_static_list = (partition.static_partitions as string[]).join(', ')
                } else if (partition.discovery_query) {
                  newFormState.partition_mode = 'discovery'
                  newFormState.partition_discovery_query = partition.discovery_query as string || ''
                }
                newFormState.partition_query_template = partition.query_template as string || ''
              }
              }
              break
            case 'file':
              newFormState.path = config.path as string || ''
              newFormState.format = config.format as string || 'json'
              newFormState.delimiter = config.delimiter as string || ''
              break
            case 'sql_event':
              newFormState.connection_string = config.connection_string as string || ''
              newFormState.query = config.query as string || ''
              newFormState.poll_interval = config.poll_interval as string || '1m'
              newFormState.watermark_column = config.watermark_column as string || ''
              break
            case 'kubernetes':
              newFormState.namespace = config.namespace as string || ''
              newFormState.pod_selector = config.pod_selector as string || ''
              newFormState.container_name = config.container_name as string || ''
              newFormState.follow = config.follow !== false
              newFormState.tail_lines = config.tail_lines as number || 100
              newFormState.since_seconds = config.since_seconds as number || ''
              newFormState.log_format = config.log_format as string || 'auto'
              newFormState.log_pattern = config.log_pattern as string || ''
              newFormState.kubeconfig = config.kubeconfig as string || ''
              newFormState.context = config.context as string || ''
              break
          }

          setFormState(newFormState)
        }
      }
    } catch {
      showError(t('source.loadError'))
    } finally {
      setLoading(false)
    }
  }, [workflowId, pipelineId, showError, t])

  useEffect(() => {
    if (workflowId && pipelineId) {
      fetchData()
    }
  }, [workflowId, pipelineId, fetchData])

  const createDefaultSource = (workflowType: 'batch' | 'realtime'): WorkflowSource => {
    if (workflowType === 'realtime') {
      return {
        type: 'kafka',
        name: 'kafka_source',
        config: {
          brokers: '',
          topic: '',
          group_id: '',
          offset: 'latest',
        },
      }
    }
    return {
      type: 'rest_api',
      name: 'api_source',
      config: {
        url: '',
        method: 'GET',
        headers: {},
      },
    }
  }

  const validateForm = (): boolean => {
    const errors: Record<string, string> = {}

    if (!formState.name) {
      errors.name = t('source.nameRequired')
    }

    switch (formState.type) {
      case 'rest_api':
        if (!formState.url) {
          errors.url = t('source.urlRequired')
        }
        break
      case 'kafka':
        if (!formState.brokers) {
          errors.brokers = t('source.brokersRequired')
        }
        if (!formState.topic) {
          errors.topic = t('source.topicRequired')
        }
        break
      case 'cdc':
        if (!formState.connection_string) {
          errors.connection_string = t('source.connectionStringRequired')
        }
        if (!formState.database) {
          errors.database = t('common.required')
        }
        if (!formState.table) {
          errors.table = t('common.required')
        }
        break
      case 'sql':
        if (!formState.connection_string) {
          errors.connection_string = t('source.connectionStringRequired')
        }
        if (!formState.query) {
          errors.query = t('common.required')
        }
        break
      case 'file':
        if (!formState.path) {
          errors.path = t('common.required')
        }
        break
      case 'sql_event':
        if (!formState.connection_string) {
          errors.connection_string = t('source.connectionStringRequired')
        }
        if (!formState.query) {
          errors.query = t('common.required')
        }
        break
      case 'kubernetes':
        if (!formState.pod_selector) {
          errors.pod_selector = t('source.k8s.podSelectorRequired')
        }
        break
    }

    // Pagination validation
    if (formState.pagination_type && formState.pagination_type !== 'none') {
      switch (formState.pagination_type) {
        case 'page_increment':
          if (!formState.pagination_page_param) errors.pagination_page_param = t('common.required')
          if (formState.pagination_start_value === '') errors.pagination_start_value = t('common.required')
          break
        case 'next_url':
          if (!formState.pagination_url_path) errors.pagination_url_path = t('common.required')
          break
        case 'next_offset':
          if (!formState.pagination_offset_param) errors.pagination_offset_param = t('common.required')
          if (!formState.pagination_offset_path) errors.pagination_offset_path = t('common.required')
          break
        case 'page_with_count':
          if (!formState.pagination_page_param) errors.pagination_page_param = t('common.required')
          if (formState.pagination_start_value === '') errors.pagination_start_value = t('common.required')
          if (!formState.pagination_current_count_path) errors.pagination_current_count_path = t('common.required')
          if (!formState.pagination_per_page_path) errors.pagination_per_page_path = t('common.required')
          break
      }
    }

    setFormErrors(errors)
    return Object.keys(errors).length === 0
  }

  const handleSave = async () => {
    try {
      setSaving(true)

      let sourceToSave: WorkflowSource

      if (editMode === 'yaml') {
        // YAML 모드에서 저장
        try {
          sourceToSave = yaml.load(yamlContent) as WorkflowSource
        } catch {
          showError(t('source.yamlParseError'))
          return
        }
      } else {
        // Visual 모드에서 저장
        if (!validateForm()) {
          return
        }
        sourceToSave = buildSourceFromForm()
      }

      // 파이프라인 업데이트 준비
      const updatedPipeline = { ...pipeline!, source: sourceToSave }

      // 배치 처리 설정 (batch 워크플로우에서만)
      // Stage는 항상 병렬 처리, Sink만 bulk/individual 선택
      if (workflow?.type === 'batch') {
        if (formState.batch_enabled) {
          const batchConfig: WorkflowPipeline['batch'] = {
            enabled: true,
            output_mode: formState.batch_output_mode || 'bulk',
            size: formState.batch_size || 100,
            workers: formState.batch_workers || 20,
            flush_interval: formState.batch_flush_interval || '5s',
          }
          updatedPipeline.batch = batchConfig
        } else {
          // 비활성화 시 batch 필드 제거
          delete updatedPipeline.batch
        }
      }

      // 실시간 워크플로우인 경우: 소스 타입에 따라 realtime_mode 처리
      if (workflow?.type === 'realtime') {
        const autoMode = autoRealtimeModeBySourceType[sourceToSave.type]
        const recommendedMode = recommendedRealtimeModeBySourceType[sourceToSave.type]
        const oldRealtimeMode = pipeline?.realtime_mode

        if (autoMode && autoMode !== oldRealtimeMode) {
          // 강제 자동 설정 (CDC, SQL Event)
          updatedPipeline.realtime_mode = autoMode
          const userStages = removeAutoGeneratedStages(pipeline?.stages || [])
          const newDefaultStages = createDefaultStages('realtime', autoMode)
          updatedPipeline.stages = [...newDefaultStages, ...userStages]

          showInfo(t('source.sourceModeChanged', { mode: autoMode.toUpperCase() }))
        } else if (recommendedMode && recommendedMode !== oldRealtimeMode) {
          // 권장사항 안내 (Kafka)
          showInfo(t('source.sourceModeRecommended', { mode: recommendedMode.toUpperCase() }))
        }
      }

      const updatedPipelines = workflow!.pipelines!.map(p =>
        p.id === pipelineId ? updatedPipeline : p
      )

      const res = await api.updateWorkflow(workflowId!, { pipelines: updatedPipelines })
      if (res.success) {
        setSource(sourceToSave)
        setPipeline(updatedPipeline)
        showSuccess(t('source.saveSuccess'))
      } else {
        showError(res.error || t('source.saveError'))
      }
    } catch {
      showError(t('source.saveError'))
    } finally {
      setSaving(false)
    }
  }

  const buildSourceFromForm = (): WorkflowSource => {
    const config: Record<string, unknown> = {}

    // 타입별 config 필드 추출
    switch (formState.type) {
      case 'rest_api': {
        config.url = formState.url
        config.method = formState.method || 'GET'
        try {
          config.headers = formState.headers ? JSON.parse(formState.headers) : {}
        } catch {
          config.headers = {}
        }
        try {
          config.query_params = formState.query_params ? JSON.parse(formState.query_params) : {}
        } catch {
          config.query_params = {}
        }
        config.body = formState.body

        // Build pagination config based on type
        const paginationType = formState.pagination_type as PaginationType
        const dataField = formState.pagination_data_field
        if (paginationType && paginationType !== 'none') {
          switch (paginationType) {
            case 'page_increment':
              config.pagination = {
                type: 'page_increment',
                param_name: formState.pagination_page_param,
                start_value: formState.pagination_start_value,
                ...(dataField && { data_field: dataField }),
              }
              break
            case 'next_url':
              config.pagination = {
                type: 'next_url',
                url_path: formState.pagination_url_path,
                ...(dataField && { data_field: dataField }),
              }
              break
            case 'next_offset':
              config.pagination = {
                type: 'next_offset',
                offset_param: formState.pagination_offset_param,
                offset_path: formState.pagination_offset_path,
                ...(dataField && { data_field: dataField }),
              }
              break
            case 'page_with_count':
              config.pagination = {
                type: 'page_with_count',
                page_param: formState.pagination_page_param,
                start_value: formState.pagination_start_value,
                current_count_path: formState.pagination_current_count_path,
                per_page_path: formState.pagination_per_page_path,
                ...(dataField && { data_field: dataField }),
              }
              break
          }
        }

        // HTTP Partition 설정
        if (formState.partition_enabled) {
          const partition: Record<string, unknown> = {
            parallelism: formState.partition_parallelism || 4,
          }
          if (formState.partition_mode === 'static' && formState.partition_static_list) {
            partition.static_partitions = formState.partition_static_list.split(',').map(s => s.trim()).filter(Boolean)
          } else if (formState.partition_mode === 'discovery' && formState.partition_discovery_url) {
            partition.discovery_url = formState.partition_discovery_url
            if (formState.partition_id_path) partition.partition_id_path = formState.partition_id_path
          }
          if (formState.partition_url_template) {
            partition.url_template = formState.partition_url_template
          }
          config.partition = partition
        }
        break
      }
      case 'kafka':
        config.brokers = formState.brokers
        config.topic = formState.topic
        config.group_id = formState.group_id
        config.offset = formState.offset || 'latest'
        break
      case 'cdc':
        config.connection_string = formState.connection_string
        config.database = formState.database
        config.table = formState.table
        config.slot_name = formState.slot_name
        break
      case 'sql':
        config.connection_string = formState.connection_string
        config.query = formState.query
        config.fetch_size = formState.fetch_size || 1000

        // SQL Partition 설정
        if (formState.partition_enabled) {
          const partition: Record<string, unknown> = {
            parallelism: formState.partition_parallelism || 4,
          }
          if (formState.partition_mode === 'static' && formState.partition_static_list) {
            partition.static_partitions = formState.partition_static_list.split(',').map(s => s.trim()).filter(Boolean)
          } else if (formState.partition_mode === 'discovery' && formState.partition_discovery_query) {
            partition.discovery_query = formState.partition_discovery_query
          }
          if (formState.partition_query_template) {
            partition.query_template = formState.partition_query_template
          }
          config.partition = partition
        }
        break
      case 'file':
        config.path = formState.path
        config.format = formState.format || 'json'
        config.delimiter = formState.delimiter
        break
      case 'sql_event':
        config.connection_string = formState.connection_string
        config.query = formState.query
        config.poll_interval = formState.poll_interval || '1m'
        config.watermark_column = formState.watermark_column
        break
      case 'kubernetes':
        config.namespace = formState.namespace
        config.pod_selector = formState.pod_selector
        config.container_name = formState.container_name
        config.follow = formState.follow
        config.tail_lines = formState.tail_lines || 100
        config.since_seconds = formState.since_seconds || undefined
        config.kubeconfig = formState.kubeconfig
        config.context = formState.context
        config.log_format = formState.log_format || 'auto'
        config.log_pattern = formState.log_pattern
        break
    }

    const sourceResult: WorkflowSource = {
      type: formState.type,
      name: formState.name,
      config,
    }

    // Rate limit 설정
    if (formState.rate_limit_enabled) {
      sourceResult.rate_limit = {
        enabled: true,
        rate: formState.rate_limit_rate as number,
        interval: formState.rate_limit_interval,
        burst: formState.rate_limit_burst as number | undefined,
        strategy: formState.rate_limit_strategy,
      }
    }

    return sourceResult
  }

  const handleModeChange = (_event: React.SyntheticEvent, newValue: string) => {
    if (newValue === 'yaml' && editMode === 'visual') {
      // Visual -> YAML: 폼 값을 YAML로 변환
      try {
        const sourceData = buildSourceFromForm()
        setYamlContent(yaml.dump(sourceData, { indent: 2 }))
        setYamlError(null)
      } catch {
        // 폼 값이 없으면 현재 source 사용
        if (source) {
          setYamlContent(yaml.dump(source, { indent: 2 }))
        }
      }
    } else if (newValue === 'visual' && editMode === 'yaml') {
      // YAML -> Visual: YAML을 파싱하여 폼에 설정
      try {
        const parsed = yaml.load(yamlContent) as WorkflowSource
        setSource(parsed)
        // Re-initialize form state from parsed YAML
        const newFormState: FormState = {
          ...initialFormState,
          type: parsed.type as SourceType,
          name: parsed.name || '',
          rate_limit_enabled: parsed.rate_limit?.enabled || false,
          rate_limit_rate: parsed.rate_limit?.rate || '',
          rate_limit_interval: parsed.rate_limit?.interval || 'second',
          rate_limit_burst: parsed.rate_limit?.burst || '',
          rate_limit_strategy: parsed.rate_limit?.strategy || 'token_bucket',
        }
        // Load config fields (객체 필드는 JSON 문자열로 변환)
        const cfg = parsed.config || {}
        Object.keys(cfg).forEach(key => {
          if (key in newFormState) {
            const value = cfg[key]
            // headers, query_params 등 객체 필드는 JSON 문자열로 변환
            if ((key === 'headers' || key === 'query_params') && value && typeof value === 'object') {
              (newFormState as unknown as Record<string, unknown>)[key] = JSON.stringify(value, null, 2)
            } else {
              (newFormState as unknown as Record<string, unknown>)[key] = value
            }
          }
        })
        setFormState(newFormState)
        setYamlError(null)
      } catch {
        showError(t('source.yamlParseError'))
        return
      }
    }
    setEditMode(newValue as 'visual' | 'yaml')
  }

  const handleYamlChange = (value: string | undefined) => {
    setYamlContent(value || '')
    try {
      yaml.load(value || '')
      setYamlError(null)
    } catch (e) {
      setYamlError((e as Error).message)
    }
  }

  // Test REST API Connection
  const handleTestRESTAPI = async () => {
    if (!formState.url) {
      showWarning(t('source.testConnectionNoUrl'))
      return
    }

    setTestingConnection(true)
    try {
      const result = await api.testRESTAPI({
        url: formState.url,
        method: formState.method || 'GET',
      })
      if (result.success) {
        showSuccess(`${t('source.testConnectionSuccess')} (${result.latency}) - ${result.message}`)
      } else {
        showError(`${t('source.testConnectionFailed')}: ${result.error}`)
      }
    } catch {
      showError(t('source.testConnectionError'))
    } finally {
      setTestingConnection(false)
    }
  }

  // Test Kafka Connection
  const handleTestKafka = async () => {
    if (!formState.brokers) {
      showWarning(t('source.testConnectionNoBroker'))
      return
    }

    setTestingConnection(true)
    try {
      const result = await api.testKafka({
        brokers: formState.brokers.split(',').map((s: string) => s.trim()).filter(Boolean),
        topic: formState.topic,
      })
      if (result.success) {
        showSuccess(`${t('source.testConnectionSuccess')} (${result.latency}) - ${result.message}`)
      } else {
        showError(`${t('source.testConnectionFailed')}: ${result.error}`)
      }
    } catch {
      showError(t('source.testConnectionError'))
    } finally {
      setTestingConnection(false)
    }
  }

  // Test DB Connection (for sql, cdc, sql_event)
  const handleTestDBConnection = async () => {
    if (!formState.connection_string) {
      showWarning(t('source.testConnectionNoString'))
      return
    }

    setTestingConnection(true)
    try {
      const result = await api.testDBConnection(formState.connection_string)
      if (result.success) {
        showSuccess(`${t('source.testConnectionSuccess')} (${result.latency})`)
      } else {
        showError(`${t('source.testConnectionFailed')}: ${result.error}`)
      }
    } catch {
      showError(t('source.testConnectionError'))
    } finally {
      setTestingConnection(false)
    }
  }

  // Source 타입별 폼 필드 렌더링
  const renderSourceConfigFields = () => {
    switch (formState.type) {
      case 'rest_api':
        return (
          <Stack spacing={2}>
            <TextField
              label={t('source.url')}
              value={formState.url}
              onChange={(e) => updateFormField('url', e.target.value)}
              error={!!formErrors.url}
              helperText={formErrors.url}
              placeholder="https://api.example.com/data"
              required
              fullWidth
            />
            <FormControl fullWidth>
              <InputLabel>{t('source.method')}</InputLabel>
              <Select
                value={formState.method}
                onChange={(e) => updateFormField('method', e.target.value)}
                label={t('source.method')}
              >
                <MenuItem value="GET">GET</MenuItem>
                <MenuItem value="POST">POST</MenuItem>
              </Select>
            </FormControl>
            <Button
              variant="outlined"
              startIcon={<ApiIcon />}
              onClick={handleTestRESTAPI}
              disabled={testingConnection}
            >
              {testingConnection ? <CircularProgress size={20} /> : t('source.testConnection')}
            </Button>
            <TextField
              label={t('source.headers')}
              value={formState.headers}
              onChange={(e) => updateFormField('headers', e.target.value)}
              helperText={t('source.headersHelp')}
              placeholder='{"Authorization": "Bearer token"}'
              multiline
              rows={3}
              fullWidth
            />
            <FormControl fullWidth>
              <InputLabel>{t('source.pagination')}</InputLabel>
              <Select
                value={formState.pagination_type}
                onChange={(e) => updateFormField('pagination_type', e.target.value as PaginationType | 'none' | '')}
                label={t('source.pagination')}
              >
                <MenuItem value="">
                  <Chip label={t('source.paginationTypes.none')} size="small" />
                  <Typography variant="body2" color="text.secondary" sx={{ ml: 1 }}>
                    {t('source.paginationTypes.noneDesc')}
                  </Typography>
                </MenuItem>
                <MenuItem value="page_increment">
                  <Chip label={t('source.paginationTypes.page_increment')} size="small" color="primary" />
                  <Typography variant="body2" color="text.secondary" sx={{ ml: 1 }}>
                    {t('source.paginationTypes.page_incrementDesc')}
                  </Typography>
                </MenuItem>
                <MenuItem value="next_url">
                  <Chip label={t('source.paginationTypes.next_url')} size="small" color="success" />
                  <Typography variant="body2" color="text.secondary" sx={{ ml: 1 }}>
                    {t('source.paginationTypes.next_urlDesc')}
                  </Typography>
                </MenuItem>
                <MenuItem value="next_offset">
                  <Chip label={t('source.paginationTypes.next_offset')} size="small" color="warning" />
                  <Typography variant="body2" color="text.secondary" sx={{ ml: 1 }}>
                    {t('source.paginationTypes.next_offsetDesc')}
                  </Typography>
                </MenuItem>
                <MenuItem value="page_with_count">
                  <Chip label={t('source.paginationTypes.page_with_count')} size="small" color="secondary" />
                  <Typography variant="body2" color="text.secondary" sx={{ ml: 1 }}>
                    {t('source.paginationTypes.page_with_countDesc')}
                  </Typography>
                </MenuItem>
              </Select>
              <FormHelperText>{t('source.paginationHelp')}</FormHelperText>
            </FormControl>

            {/* Pagination type-specific config fields */}
            {formState.pagination_type === 'page_increment' && (
              <Box sx={{ ml: 2, p: 2, bgcolor: 'action.hover', borderRadius: 1 }}>
                <Stack spacing={2}>
                  <TextField
                    label={t('source.paginationConfig.pageParam')}
                    value={formState.pagination_page_param}
                    onChange={(e) => updateFormField('pagination_page_param', e.target.value)}
                    error={!!formErrors.pagination_page_param}
                    helperText={formErrors.pagination_page_param || t('source.paginationConfig.pageParamHelp')}
                    placeholder={t('source.paginationConfig.pageParamPlaceholder')}
                    required
                    sx={{ width: 200 }}
                  />
                  <TextField
                    label={t('source.paginationConfig.startValue')}
                    type="number"
                    value={formState.pagination_start_value}
                    onChange={(e) => updateFormField('pagination_start_value', e.target.value ? Number(e.target.value) : '')}
                    error={!!formErrors.pagination_start_value}
                    helperText={formErrors.pagination_start_value || t('source.paginationConfig.startValueHelp')}
                    placeholder="1"
                    required
                    sx={{ width: 100 }}
                  />
                  <TextField
                    label={t('source.paginationConfig.dataField')}
                    value={formState.pagination_data_field}
                    onChange={(e) => updateFormField('pagination_data_field', e.target.value)}
                    helperText={t('source.paginationConfig.dataFieldHelp')}
                    placeholder={t('source.paginationConfig.dataFieldPlaceholder')}
                    sx={{ width: 200 }}
                  />
                </Stack>
              </Box>
            )}

            {formState.pagination_type === 'next_url' && (
              <Box sx={{ ml: 2, p: 2, bgcolor: 'action.hover', borderRadius: 1 }}>
                <Stack spacing={2}>
                  <TextField
                    label={t('source.paginationConfig.urlPath')}
                    value={formState.pagination_url_path}
                    onChange={(e) => updateFormField('pagination_url_path', e.target.value)}
                    error={!!formErrors.pagination_url_path}
                    helperText={formErrors.pagination_url_path || t('source.paginationConfig.urlPathHelp')}
                    placeholder={t('source.paginationConfig.urlPathPlaceholder')}
                    required
                    sx={{ width: 250 }}
                  />
                  <TextField
                    label={t('source.paginationConfig.dataField')}
                    value={formState.pagination_data_field}
                    onChange={(e) => updateFormField('pagination_data_field', e.target.value)}
                    helperText={t('source.paginationConfig.dataFieldHelp')}
                    placeholder={t('source.paginationConfig.dataFieldPlaceholder')}
                    sx={{ width: 200 }}
                  />
                </Stack>
              </Box>
            )}

            {formState.pagination_type === 'next_offset' && (
              <Box sx={{ ml: 2, p: 2, bgcolor: 'action.hover', borderRadius: 1 }}>
                <Stack spacing={2}>
                  <TextField
                    label={t('source.paginationConfig.offsetParam')}
                    value={formState.pagination_offset_param}
                    onChange={(e) => updateFormField('pagination_offset_param', e.target.value)}
                    error={!!formErrors.pagination_offset_param}
                    helperText={formErrors.pagination_offset_param || t('source.paginationConfig.offsetParamHelp')}
                    placeholder={t('source.paginationConfig.offsetParamPlaceholder')}
                    required
                    sx={{ width: 200 }}
                  />
                  <TextField
                    label={t('source.paginationConfig.offsetPath')}
                    value={formState.pagination_offset_path}
                    onChange={(e) => updateFormField('pagination_offset_path', e.target.value)}
                    error={!!formErrors.pagination_offset_path}
                    helperText={formErrors.pagination_offset_path || t('source.paginationConfig.offsetPathHelp')}
                    placeholder={t('source.paginationConfig.offsetPathPlaceholder')}
                    required
                    sx={{ width: 250 }}
                  />
                  <TextField
                    label={t('source.paginationConfig.dataField')}
                    value={formState.pagination_data_field}
                    onChange={(e) => updateFormField('pagination_data_field', e.target.value)}
                    helperText={t('source.paginationConfig.dataFieldHelp')}
                    placeholder={t('source.paginationConfig.dataFieldPlaceholder')}
                    sx={{ width: 200 }}
                  />
                </Stack>
              </Box>
            )}

            {formState.pagination_type === 'page_with_count' && (
              <Box sx={{ ml: 2, p: 2, bgcolor: 'action.hover', borderRadius: 1 }}>
                <Stack spacing={2}>
                  <TextField
                    label={t('source.paginationConfig.pageParam')}
                    value={formState.pagination_page_param}
                    onChange={(e) => updateFormField('pagination_page_param', e.target.value)}
                    error={!!formErrors.pagination_page_param}
                    helperText={formErrors.pagination_page_param || t('source.paginationConfig.pageParamHelp')}
                    placeholder={t('source.paginationConfig.pageParamPlaceholder')}
                    required
                    sx={{ width: 200 }}
                  />
                  <TextField
                    label={t('source.paginationConfig.startValue')}
                    type="number"
                    value={formState.pagination_start_value}
                    onChange={(e) => updateFormField('pagination_start_value', e.target.value ? Number(e.target.value) : '')}
                    error={!!formErrors.pagination_start_value}
                    helperText={formErrors.pagination_start_value || t('source.paginationConfig.startValueHelp')}
                    placeholder="1"
                    required
                    sx={{ width: 100 }}
                  />
                  <TextField
                    label={t('source.paginationConfig.currentCountPath')}
                    value={formState.pagination_current_count_path}
                    onChange={(e) => updateFormField('pagination_current_count_path', e.target.value)}
                    error={!!formErrors.pagination_current_count_path}
                    helperText={formErrors.pagination_current_count_path || t('source.paginationConfig.currentCountPathHelp')}
                    placeholder={t('source.paginationConfig.currentCountPathPlaceholder')}
                    required
                    sx={{ width: 250 }}
                  />
                  <TextField
                    label={t('source.paginationConfig.perPagePath')}
                    value={formState.pagination_per_page_path}
                    onChange={(e) => updateFormField('pagination_per_page_path', e.target.value)}
                    error={!!formErrors.pagination_per_page_path}
                    helperText={formErrors.pagination_per_page_path || t('source.paginationConfig.perPagePathHelp')}
                    placeholder={t('source.paginationConfig.perPagePathPlaceholder')}
                    required
                    sx={{ width: 250 }}
                  />
                  <TextField
                    label={t('source.paginationConfig.dataField')}
                    value={formState.pagination_data_field}
                    onChange={(e) => updateFormField('pagination_data_field', e.target.value)}
                    helperText={t('source.paginationConfig.dataFieldHelp')}
                    placeholder={t('source.paginationConfig.dataFieldPlaceholder')}
                    sx={{ width: 200 }}
                  />
                </Stack>
              </Box>
            )}

            {/* Partition 설정 (batch 워크플로우용) */}
            {workflow?.type === 'batch' && (
              <>
                <Divider sx={{ my: 2 }}>{t('source.partition.title')}</Divider>
                <FormControlLabel
                  control={
                    <Switch
                      checked={formState.partition_enabled}
                      onChange={(e) => updateFormField('partition_enabled', e.target.checked)}
                    />
                  }
                  label={t('source.partition.enabled')}
                />
                <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: -1, mb: 1 }}>
                  {t('source.partition.enabledHelp')}
                </Typography>

                {formState.partition_enabled && (
                  <Box sx={{ ml: 2, p: 2, bgcolor: 'action.hover', borderRadius: 1 }}>
                    <Stack spacing={2}>
                      <FormControl sx={{ width: 200 }}>
                        <InputLabel>{t('source.partition.mode')}</InputLabel>
                        <Select
                          value={formState.partition_mode}
                          onChange={(e) => updateFormField('partition_mode', e.target.value as 'discovery' | 'static')}
                          label={t('source.partition.mode')}
                        >
                          <MenuItem value="static">{t('source.partition.modeStatic')}</MenuItem>
                          <MenuItem value="discovery">{t('source.partition.modeDiscovery')}</MenuItem>
                        </Select>
                      </FormControl>

                      {formState.partition_mode === 'static' ? (
                        <TextField
                          label={t('source.partition.staticList')}
                          value={formState.partition_static_list}
                          onChange={(e) => updateFormField('partition_static_list', e.target.value)}
                          helperText={t('source.partition.staticListHelp')}
                          placeholder="p0, p1, p2, p3"
                          fullWidth
                          multiline
                          rows={2}
                        />
                      ) : (
                        <>
                          <TextField
                            label={t('source.partition.discoveryUrl')}
                            value={formState.partition_discovery_url}
                            onChange={(e) => updateFormField('partition_discovery_url', e.target.value)}
                            helperText={t('source.partition.discoveryUrlHelp')}
                            placeholder="https://api.example.com/data/_partitions"
                            fullWidth
                          />
                          <TextField
                            label={t('source.partition.idPath', 'Partition ID Path')}
                            value={formState.partition_id_path}
                            onChange={(e) => updateFormField('partition_id_path', e.target.value)}
                            helperText="JSONPath-like: path.[*].field (e.g. partitions.[*].url)"
                            placeholder="partitions.[*].url"
                            fullWidth
                          />
                        </>
                      )}

                      <TextField
                        label={t('source.partition.urlTemplate')}
                        value={formState.partition_url_template}
                        onChange={(e) => updateFormField('partition_url_template', e.target.value)}
                        helperText={t('source.partition.urlTemplateHelp')}
                        placeholder="https://api.example.com/data?partition=${partition}"
                        fullWidth
                      />

                      <TextField
                        label={t('source.partition.parallelism')}
                        type="number"
                        value={formState.partition_parallelism}
                        onChange={(e) => updateFormField('partition_parallelism', e.target.value ? Number(e.target.value) : '')}
                        helperText={t('source.partition.parallelismHelp')}
                        inputProps={{ min: 1, max: 32 }}
                        sx={{ width: 120 }}
                      />
                    </Stack>
                  </Box>
                )}
              </>
            )}

            {/* 배치 처리 설정 (batch 워크플로우에서만 표시) */}
            {workflow?.type === 'batch' && (
              <>
                <Divider sx={{ my: 2 }}>{t('source.batch.title')}</Divider>
                <FormControlLabel
                  control={
                    <Switch
                      checked={formState.batch_enabled}
                      onChange={(e) => updateFormField('batch_enabled', e.target.checked)}
                    />
                  }
                  label={t('source.batch.enabled')}
                />
                <FormHelperText sx={{ mt: -1, mb: 1 }}>
                  {t('source.batch.enabledHelp')}
                </FormHelperText>

                {formState.batch_enabled && (
                  <Box sx={{ pl: 2 }}>
                    <Stack spacing={2}>
                      {/* Stage는 항상 병렬 처리 안내 */}
                      <Typography variant="body2" color="text.secondary">
                        {t('source.batch.stageNote')}
                      </Typography>

                      {/* Sink 처리 모드 선택 */}
                      <FormControl sx={{ width: 280 }}>
                        <InputLabel>{t('source.batch.outputMode')}</InputLabel>
                        <Select
                          value={formState.batch_output_mode}
                          onChange={(e) => updateFormField('batch_output_mode', e.target.value as 'bulk' | 'individual')}
                          label={t('source.batch.outputMode')}
                        >
                          <MenuItem value="bulk">
                            <Box>
                              <Typography variant="body2">{t('source.batch.outputModeBulk')}</Typography>
                              <Typography variant="caption" color="text.secondary">
                                {t('source.batch.outputModeBulkDesc')}
                              </Typography>
                            </Box>
                          </MenuItem>
                          <MenuItem value="individual">
                            <Box>
                              <Typography variant="body2">{t('source.batch.outputModeIndividual')}</Typography>
                              <Typography variant="caption" color="text.secondary">
                                {t('source.batch.outputModeIndividualDesc')}
                              </Typography>
                            </Box>
                          </MenuItem>
                        </Select>
                        <FormHelperText>{t('source.batch.outputModeHelp')}</FormHelperText>
                      </FormControl>

                      {/* 배치 크기 */}
                      <TextField
                        label={t('source.batch.size')}
                        type="number"
                        value={formState.batch_size}
                        onChange={(e) => updateFormField('batch_size', e.target.value ? Number(e.target.value) : '')}
                        helperText={t('source.batch.sizeHelp')}
                        inputProps={{ min: 1, max: 10000 }}
                        sx={{ width: 180 }}
                      />

                      {/* 병렬 워커 수 */}
                      <TextField
                        label={t('source.batch.workers')}
                        type="number"
                        value={formState.batch_workers}
                        onChange={(e) => updateFormField('batch_workers', e.target.value ? Number(e.target.value) : '')}
                        helperText={t('source.batch.workersHelp')}
                        inputProps={{ min: 1, max: 100 }}
                        sx={{ width: 180 }}
                      />

                      {/* 플러시 인터벌 */}
                      <TextField
                        label={t('source.batch.flushInterval')}
                        value={formState.batch_flush_interval}
                        onChange={(e) => updateFormField('batch_flush_interval', e.target.value)}
                        helperText={t('source.batch.flushIntervalHelp')}
                        placeholder="5s"
                        sx={{ width: 180 }}
                      />
                    </Stack>
                  </Box>
                )}
              </>
            )}
          </Stack>
        )

      case 'kafka':
        return (
          <Stack spacing={2}>
            <TextField
              label={t('source.brokers')}
              value={formState.brokers}
              onChange={(e) => updateFormField('brokers', e.target.value)}
              error={!!formErrors.brokers}
              helperText={formErrors.brokers || t('source.brokersHelp')}
              placeholder="localhost:9092,localhost:9093"
              required
              fullWidth
            />
            <Button
              variant="outlined"
              startIcon={<ApiIcon />}
              onClick={handleTestKafka}
              disabled={testingConnection}
            >
              {testingConnection ? <CircularProgress size={20} /> : t('source.testConnection')}
            </Button>
            <TextField
              label={t('source.topic')}
              value={formState.topic}
              onChange={(e) => updateFormField('topic', e.target.value)}
              error={!!formErrors.topic}
              helperText={formErrors.topic}
              placeholder="my-topic"
              required
              fullWidth
            />
            <TextField
              label={t('source.groupId')}
              value={formState.group_id}
              onChange={(e) => updateFormField('group_id', e.target.value)}
              placeholder="consumer-group-1"
              fullWidth
            />
            <FormControl fullWidth>
              <InputLabel>{t('source.offset')}</InputLabel>
              <Select
                value={formState.offset}
                onChange={(e) => updateFormField('offset', e.target.value)}
                label={t('source.offset')}
              >
                <MenuItem value="latest">Latest</MenuItem>
                <MenuItem value="earliest">Earliest</MenuItem>
              </Select>
            </FormControl>
          </Stack>
        )

      case 'cdc':
        return (
          <Stack spacing={2}>
            <TextField
              label={t('source.connectionString')}
              type="password"
              value={formState.connection_string}
              onChange={(e) => updateFormField('connection_string', e.target.value)}
              error={!!formErrors.connection_string}
              helperText={formErrors.connection_string}
              placeholder="postgres://user:pass@host:5432/db"
              required
              fullWidth
            />
            <Button
              variant="outlined"
              startIcon={<ApiIcon />}
              onClick={handleTestDBConnection}
              disabled={testingConnection}
            >
              {testingConnection ? <CircularProgress size={20} /> : t('source.testConnection')}
            </Button>
            <TextField
              label={t('source.database')}
              value={formState.database}
              onChange={(e) => updateFormField('database', e.target.value)}
              error={!!formErrors.database}
              helperText={formErrors.database}
              placeholder="mydb"
              required
              fullWidth
            />
            <TextField
              label={t('source.table')}
              value={formState.table}
              onChange={(e) => updateFormField('table', e.target.value)}
              error={!!formErrors.table}
              helperText={formErrors.table}
              placeholder="users"
              required
              fullWidth
            />
            <TextField
              label={t('source.slotName')}
              value={formState.slot_name}
              onChange={(e) => updateFormField('slot_name', e.target.value)}
              placeholder="cdc_slot"
              fullWidth
            />
          </Stack>
        )

      case 'sql':
        return (
          <Stack spacing={2}>
            <TextField
              label={t('source.connectionString')}
              type="password"
              value={formState.connection_string}
              onChange={(e) => updateFormField('connection_string', e.target.value)}
              error={!!formErrors.connection_string}
              helperText={formErrors.connection_string}
              placeholder="postgres://user:pass@host:5432/db"
              required
              fullWidth
            />
            <Button
              variant="outlined"
              startIcon={<ApiIcon />}
              onClick={handleTestDBConnection}
              disabled={testingConnection}
            >
              {testingConnection ? <CircularProgress size={20} /> : t('source.testConnection')}
            </Button>
            <TextField
              label={t('source.query')}
              value={formState.query}
              onChange={(e) => updateFormField('query', e.target.value)}
              error={!!formErrors.query}
              helperText={formErrors.query}
              placeholder="SELECT * FROM users WHERE updated_at > :last_sync"
              multiline
              rows={4}
              required
              fullWidth
            />
            <TextField
              label={t('source.fetchSize')}
              type="number"
              value={formState.fetch_size}
              onChange={(e) => updateFormField('fetch_size', e.target.value ? Number(e.target.value) : '')}
              placeholder="1000"
              inputProps={{ min: 100, max: 100000 }}
              fullWidth
            />

            {/* SQL Partition 설정 (batch 워크플로우용) */}
            {workflow?.type === 'batch' && (
              <>
                <Divider sx={{ my: 2 }}>{t('source.partition.title')}</Divider>
                <FormControlLabel
                  control={
                    <Switch
                      checked={formState.partition_enabled}
                      onChange={(e) => updateFormField('partition_enabled', e.target.checked)}
                    />
                  }
                  label={t('source.partition.enabled')}
                />
                <Typography variant="caption" color="text.secondary" sx={{ display: 'block', mt: -1, mb: 1 }}>
                  {t('source.partition.sqlEnabledHelp')}
                </Typography>

                {formState.partition_enabled && (
                  <Box sx={{ ml: 2, p: 2, bgcolor: 'action.hover', borderRadius: 1 }}>
                    <Stack spacing={2}>
                      <FormControl sx={{ width: 200 }}>
                        <InputLabel>{t('source.partition.mode')}</InputLabel>
                        <Select
                          value={formState.partition_mode}
                          onChange={(e) => updateFormField('partition_mode', e.target.value as 'discovery' | 'static')}
                          label={t('source.partition.mode')}
                        >
                          <MenuItem value="static">{t('source.partition.modeStatic')}</MenuItem>
                          <MenuItem value="discovery">{t('source.partition.modeDiscovery')}</MenuItem>
                        </Select>
                      </FormControl>

                      {formState.partition_mode === 'static' ? (
                        <TextField
                          label={t('source.partition.staticList')}
                          value={formState.partition_static_list}
                          onChange={(e) => updateFormField('partition_static_list', e.target.value)}
                          helperText={t('source.partition.sqlStaticListHelp')}
                          placeholder="p202401, p202402, p202403"
                          fullWidth
                          multiline
                          rows={2}
                        />
                      ) : (
                        <TextField
                          label={t('source.partition.discoveryQuery')}
                          value={formState.partition_discovery_query}
                          onChange={(e) => updateFormField('partition_discovery_query', e.target.value)}
                          helperText={t('source.partition.discoveryQueryHelp')}
                          placeholder="SELECT PARTITION_NAME FROM INFORMATION_SCHEMA.PARTITIONS WHERE TABLE_NAME = 'events'"
                          fullWidth
                          multiline
                          rows={3}
                        />
                      )}

                      <TextField
                        label={t('source.partition.queryTemplate')}
                        value={formState.partition_query_template}
                        onChange={(e) => updateFormField('partition_query_template', e.target.value)}
                        helperText={t('source.partition.queryTemplateHelp')}
                        placeholder="SELECT * FROM events PARTITION (${partition})"
                        fullWidth
                        multiline
                        rows={2}
                      />

                      <TextField
                        label={t('source.partition.parallelism')}
                        type="number"
                        value={formState.partition_parallelism}
                        onChange={(e) => updateFormField('partition_parallelism', e.target.value ? Number(e.target.value) : '')}
                        helperText={t('source.partition.parallelismHelp')}
                        inputProps={{ min: 1, max: 32 }}
                        sx={{ width: 120 }}
                      />
                    </Stack>
                  </Box>
                )}
              </>
            )}

            {/* 배치 처리 설정 (batch 워크플로우에서만 표시) */}
            {workflow?.type === 'batch' && (
              <>
                <Divider sx={{ my: 2 }}>{t('source.batch.title')}</Divider>
                <FormControlLabel
                  control={
                    <Switch
                      checked={formState.batch_enabled}
                      onChange={(e) => updateFormField('batch_enabled', e.target.checked)}
                    />
                  }
                  label={t('source.batch.enabled')}
                />
                <FormHelperText sx={{ mt: -1, mb: 1 }}>
                  {t('source.batch.enabledHelp')}
                </FormHelperText>

                {formState.batch_enabled && (
                  <Box sx={{ pl: 2 }}>
                    <Stack spacing={2}>
                      {/* Stage는 항상 병렬 처리 안내 */}
                      <Typography variant="body2" color="text.secondary">
                        {t('source.batch.stageNote')}
                      </Typography>

                      {/* Sink 처리 모드 선택 */}
                      <FormControl sx={{ width: 280 }}>
                        <InputLabel>{t('source.batch.outputMode')}</InputLabel>
                        <Select
                          value={formState.batch_output_mode}
                          onChange={(e) => updateFormField('batch_output_mode', e.target.value as 'bulk' | 'individual')}
                          label={t('source.batch.outputMode')}
                        >
                          <MenuItem value="bulk">
                            <Box>
                              <Typography variant="body2">{t('source.batch.outputModeBulk')}</Typography>
                              <Typography variant="caption" color="text.secondary">
                                {t('source.batch.outputModeBulkDesc')}
                              </Typography>
                            </Box>
                          </MenuItem>
                          <MenuItem value="individual">
                            <Box>
                              <Typography variant="body2">{t('source.batch.outputModeIndividual')}</Typography>
                              <Typography variant="caption" color="text.secondary">
                                {t('source.batch.outputModeIndividualDesc')}
                              </Typography>
                            </Box>
                          </MenuItem>
                        </Select>
                        <FormHelperText>{t('source.batch.outputModeHelp')}</FormHelperText>
                      </FormControl>

                      {/* 배치 크기 */}
                      <TextField
                        label={t('source.batch.size')}
                        type="number"
                        value={formState.batch_size}
                        onChange={(e) => updateFormField('batch_size', e.target.value ? Number(e.target.value) : '')}
                        helperText={t('source.batch.sizeHelp')}
                        inputProps={{ min: 1, max: 10000 }}
                        sx={{ width: 180 }}
                      />

                      {/* 병렬 워커 수 */}
                      <TextField
                        label={t('source.batch.workers')}
                        type="number"
                        value={formState.batch_workers}
                        onChange={(e) => updateFormField('batch_workers', e.target.value ? Number(e.target.value) : '')}
                        helperText={t('source.batch.workersHelp')}
                        inputProps={{ min: 1, max: 100 }}
                        sx={{ width: 180 }}
                      />

                      {/* 플러시 인터벌 */}
                      <TextField
                        label={t('source.batch.flushInterval')}
                        value={formState.batch_flush_interval}
                        onChange={(e) => updateFormField('batch_flush_interval', e.target.value)}
                        helperText={t('source.batch.flushIntervalHelp')}
                        placeholder="5s"
                        sx={{ width: 180 }}
                      />
                    </Stack>
                  </Box>
                )}
              </>
            )}
          </Stack>
        )

      case 'file':
        return (
          <Stack spacing={2}>
            <TextField
              label={t('source.path')}
              value={formState.path}
              onChange={(e) => updateFormField('path', e.target.value)}
              error={!!formErrors.path}
              helperText={formErrors.path}
              placeholder="/data/input/*.json"
              required
              fullWidth
            />
            <FormControl fullWidth>
              <InputLabel>{t('source.format')}</InputLabel>
              <Select
                value={formState.format}
                onChange={(e) => updateFormField('format', e.target.value)}
                label={t('source.format')}
              >
                <MenuItem value="json">JSON</MenuItem>
                <MenuItem value="csv">CSV</MenuItem>
                <MenuItem value="parquet">Parquet</MenuItem>
              </Select>
            </FormControl>
            <TextField
              label={t('source.delimiter')}
              value={formState.delimiter}
              onChange={(e) => updateFormField('delimiter', e.target.value)}
              placeholder=","
              sx={{ width: 100 }}
            />
          </Stack>
        )

      case 'sql_event':
        return (
          <Stack spacing={2}>
            <TextField
              label={t('source.connectionString')}
              type="password"
              value={formState.connection_string}
              onChange={(e) => updateFormField('connection_string', e.target.value)}
              error={!!formErrors.connection_string}
              helperText={formErrors.connection_string}
              placeholder="postgres://user:pass@host:5432/db"
              required
              fullWidth
            />
            <Button
              variant="outlined"
              startIcon={<ApiIcon />}
              onClick={handleTestDBConnection}
              disabled={testingConnection}
            >
              {testingConnection ? <CircularProgress size={20} /> : t('source.testConnection')}
            </Button>
            <TextField
              label={t('source.query')}
              value={formState.query}
              onChange={(e) => updateFormField('query', e.target.value)}
              error={!!formErrors.query}
              helperText={formErrors.query}
              placeholder="SELECT * FROM events WHERE created_at > :watermark"
              multiline
              rows={4}
              required
              fullWidth
            />
            <TextField
              label={t('source.pollInterval')}
              value={formState.poll_interval}
              onChange={(e) => updateFormField('poll_interval', e.target.value)}
              placeholder="1m"
              sx={{ width: 150 }}
            />
            <TextField
              label={t('source.watermarkColumn')}
              value={formState.watermark_column}
              onChange={(e) => updateFormField('watermark_column', e.target.value)}
              placeholder="created_at"
              fullWidth
            />
          </Stack>
        )

      case 'kubernetes':
        return (
          <Stack spacing={2}>
            <TextField
              label={t('source.k8s.namespace')}
              value={formState.namespace}
              onChange={(e) => updateFormField('namespace', e.target.value)}
              helperText={t('source.k8s.namespaceHelp')}
              placeholder="default"
              fullWidth
            />
            <TextField
              label={t('source.k8s.podSelector')}
              value={formState.pod_selector}
              onChange={(e) => updateFormField('pod_selector', e.target.value)}
              error={!!formErrors.pod_selector}
              helperText={formErrors.pod_selector || t('source.k8s.podSelectorHelp')}
              placeholder="app=nginx,env=production"
              required
              fullWidth
            />
            <TextField
              label={t('source.k8s.containerName')}
              value={formState.container_name}
              onChange={(e) => updateFormField('container_name', e.target.value)}
              helperText={t('source.k8s.containerNameHelp')}
              placeholder="nginx"
              fullWidth
            />
            <FormControlLabel
              control={
                <Switch
                  checked={formState.follow}
                  onChange={(e) => updateFormField('follow', e.target.checked)}
                />
              }
              label={t('source.k8s.follow')}
            />
            <TextField
              label={t('source.k8s.tailLines')}
              type="number"
              value={formState.tail_lines}
              onChange={(e) => updateFormField('tail_lines', e.target.value ? Number(e.target.value) : '')}
              helperText={t('source.k8s.tailLinesHelp')}
              placeholder="100"
              inputProps={{ min: 1, max: 10000 }}
              sx={{ width: 150 }}
            />
            <TextField
              label={t('source.k8s.sinceSeconds')}
              type="number"
              value={formState.since_seconds}
              onChange={(e) => updateFormField('since_seconds', e.target.value ? Number(e.target.value) : '')}
              helperText={t('source.k8s.sinceSecondsHelp')}
              placeholder="3600"
              inputProps={{ min: 1 }}
              sx={{ width: 150 }}
            />
            <Divider>{t('source.k8s.logParsing')}</Divider>
            <FormControl sx={{ width: 150 }}>
              <InputLabel>{t('source.k8s.logFormat')}</InputLabel>
              <Select
                value={formState.log_format}
                onChange={(e) => updateFormField('log_format', e.target.value)}
                label={t('source.k8s.logFormat')}
              >
                <MenuItem value="auto">{t('source.k8s.logFormatAuto')}</MenuItem>
                <MenuItem value="json">{t('source.k8s.logFormatJson')}</MenuItem>
                <MenuItem value="text">{t('source.k8s.logFormatText')}</MenuItem>
              </Select>
              <FormHelperText>{t('source.k8s.logFormatHelp')}</FormHelperText>
            </FormControl>
            <TextField
              label={t('source.k8s.logPattern')}
              value={formState.log_pattern}
              onChange={(e) => updateFormField('log_pattern', e.target.value)}
              helperText={t('source.k8s.logPatternHelp')}
              placeholder="(?P<level>\w+)\s+(?P<message>.*)"
              fullWidth
            />
            <Divider>{t('source.k8s.externalCluster')}</Divider>
            <TextField
              label={t('source.k8s.kubeconfig')}
              value={formState.kubeconfig}
              onChange={(e) => updateFormField('kubeconfig', e.target.value)}
              helperText={t('source.k8s.kubeconfigHelp')}
              placeholder="/path/to/kubeconfig"
              fullWidth
            />
            <TextField
              label={t('source.k8s.context')}
              value={formState.context}
              onChange={(e) => updateFormField('context', e.target.value)}
              helperText={t('source.k8s.contextHelp')}
              placeholder="my-cluster-context"
              fullWidth
            />
          </Stack>
        )

      default:
        return null
    }
  }

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 400 }}>
        <CircularProgress size={40} />
      </Box>
    )
  }

  if (!workflow || !pipeline) {
    return (
      <Box sx={{ textAlign: 'center', p: 5 }}>
        <Typography color="text.secondary">{t('source.notFound')}</Typography>
      </Box>
    )
  }

  return (
    <Box>
      <Breadcrumbs sx={{ mb: 2 }}>
        <Link
          component="button"
          underline="hover"
          color="inherit"
          onClick={() => navigate('/projects')}
        >
          {t('project.title')}
        </Link>
        <Link
          component="button"
          underline="hover"
          color="inherit"
          onClick={() => navigate(`/projects/${projectAlias}`)}
        >
          {workflow.project?.name}
        </Link>
        <Link
          component="button"
          underline="hover"
          color="inherit"
          onClick={() => navigate(`/projects/${projectAlias}/workflows/${workflowId}`)}
        >
          {workflow.name}
        </Link>
        <Typography color="text.primary">{pipeline.name}</Typography>
        <Typography color="text.primary">{t('source.title')}</Typography>
      </Breadcrumbs>

      <Box sx={{ mb: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Stack direction="row" spacing={2} alignItems="center">
          <Button
            startIcon={<ArrowBackIcon />}
            onClick={() => navigate(`/projects/${projectAlias}/workflows/${workflowId}`)}
          >
            {t('common.back')}
          </Button>
          <Typography variant="h5">
            {t('source.title')} - {pipeline.name}
          </Typography>
        </Stack>
        <Button
          variant="contained"
          startIcon={<SaveIcon />}
          onClick={handleSave}
          disabled={saving || (editMode === 'yaml' && !!yamlError)}
        >
          {saving ? <CircularProgress size={20} /> : t('common.save')}
        </Button>
      </Box>

      <Card>
        <CardContent>
          <Tabs value={editMode} onChange={handleModeChange} sx={{ mb: 2 }}>
            <Tab label={t('source.visual')} value="visual" />
            <Tab
              label={
                <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                  {t('source.yaml')}
                  {yamlError && <Chip label="Error" size="small" color="error" />}
                </Box>
              }
              value="yaml"
            />
          </Tabs>

          {editMode === 'visual' ? (
            <Box sx={{ maxWidth: 600 }}>
              <Stack spacing={3}>
                <FormControl fullWidth required>
                  <InputLabel>{t('source.type')}</InputLabel>
                  <Select
                    value={formState.type}
                    onChange={(e) => updateFormField('type', e.target.value as SourceType)}
                    label={t('source.type')}
                  >
                    {sourceTypesByWorkflow[workflow.type].map((key) => {
                      const config = sourceTypeConfig[key]
                      return (
                        <MenuItem key={key} value={key}>
                          <Stack direction="row" spacing={1} alignItems="center">
                            <Chip
                              icon={config.icon as React.ReactElement}
                              label={config.label}
                              size="small"
                              sx={{ bgcolor: config.color, color: 'white' }}
                            />
                          </Stack>
                        </MenuItem>
                      )
                    })}
                  </Select>
                </FormControl>

                <TextField
                  label={t('source.name')}
                  value={formState.name}
                  onChange={(e) => updateFormField('name', e.target.value)}
                  error={!!formErrors.name}
                  helperText={formErrors.name}
                  placeholder="api_source"
                  required
                  fullWidth
                />

                <Divider>{t('source.configuration')}</Divider>

                {renderSourceConfigFields()}

                <Divider>{t('rateLimit.title')}</Divider>

                <FormControlLabel
                  control={
                    <Switch
                      checked={formState.rate_limit_enabled}
                      onChange={(e) => updateFormField('rate_limit_enabled', e.target.checked)}
                    />
                  }
                  label={t('rateLimit.enabled')}
                />

                {formState.rate_limit_enabled && (
                  <Stack spacing={2}>
                    <Stack direction="row" spacing={2}>
                      <TextField
                        label={t('rateLimit.rate')}
                        type="number"
                        value={formState.rate_limit_rate}
                        onChange={(e) => updateFormField('rate_limit_rate', e.target.value ? Number(e.target.value) : '')}
                        placeholder="100"
                        inputProps={{ min: 1 }}
                        sx={{ width: 120 }}
                      />
                      <FormControl sx={{ width: 120 }}>
                        <InputLabel>{t('rateLimit.interval')}</InputLabel>
                        <Select
                          value={formState.rate_limit_interval}
                          onChange={(e) => updateFormField('rate_limit_interval', e.target.value as RateLimitConfig['interval'])}
                          label={t('rateLimit.interval')}
                        >
                          <MenuItem value="second">{t('rateLimit.perSecond')}</MenuItem>
                          <MenuItem value="minute">{t('rateLimit.perMinute')}</MenuItem>
                          <MenuItem value="hour">{t('rateLimit.perHour')}</MenuItem>
                        </Select>
                      </FormControl>
                    </Stack>
                    <Stack direction="row" spacing={2}>
                      <TextField
                        label={t('rateLimit.burst')}
                        type="number"
                        value={formState.rate_limit_burst}
                        onChange={(e) => updateFormField('rate_limit_burst', e.target.value ? Number(e.target.value) : '')}
                        placeholder="10"
                        inputProps={{ min: 1 }}
                        sx={{ width: 120 }}
                      />
                      <FormControl sx={{ width: 150 }}>
                        <InputLabel>{t('rateLimit.strategy')}</InputLabel>
                        <Select
                          value={formState.rate_limit_strategy}
                          onChange={(e) => updateFormField('rate_limit_strategy', e.target.value as RateLimitConfig['strategy'])}
                          label={t('rateLimit.strategy')}
                        >
                          <MenuItem value="token_bucket">{t('rateLimit.tokenBucket')}</MenuItem>
                          <MenuItem value="sliding_window">{t('rateLimit.slidingWindow')}</MenuItem>
                          <MenuItem value="fixed_window">{t('rateLimit.fixedWindow')}</MenuItem>
                        </Select>
                      </FormControl>
                    </Stack>
                  </Stack>
                )}
              </Stack>
            </Box>
          ) : (
            <Box>
              {yamlError && (
                <Box sx={{ mb: 1, p: 1, bgcolor: 'error.light', borderRadius: 1 }}>
                  <Typography color="error">{yamlError}</Typography>
                </Box>
              )}
              <Editor
                height="500px"
                language="yaml"
                theme="vs-dark"
                value={yamlContent}
                onChange={handleYamlChange}
                options={{
                  minimap: { enabled: false },
                  fontSize: 14,
                  lineNumbers: 'on',
                  tabSize: 2,
                  scrollBeyondLastLine: false,
                }}
              />
            </Box>
          )}
        </CardContent>
      </Card>
    </Box>
  )
}
