import { useEffect, useState, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  Card,
  CardContent,
  CardHeader,
  Typography,
  Box,
  Button,
  Chip,
  Tabs,
  Tab,
  CircularProgress,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
  Breadcrumbs,
  Link,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  TextField,
  Select,
  MenuItem,
  FormControl,
  InputLabel,
  FormHelperText,
  IconButton,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Alert,
  Radio,
  RadioGroup,
  FormControlLabel,
} from '@mui/material'
import { DateTimePicker } from '@mui/x-date-pickers/DateTimePicker'
import { LocalizationProvider } from '@mui/x-date-pickers/LocalizationProvider'
import { AdapterDayjs } from '@mui/x-date-pickers/AdapterDayjs'
import type { Dayjs } from 'dayjs'
import {
  ArrowBack as ArrowBackIcon,
  Edit as EditIcon,
  Delete as DeleteIcon,
  Add as AddIcon,
  RemoveCircleOutline as RemoveCircleIcon,
  PlayCircle as PlayCircleIcon,
  PauseCircle as PauseCircleIcon,
  AccountTree as BranchesIcon,
  Settings as SettingsIcon,
  History as HistoryIcon,
  CheckCircle as CheckCircleIcon,
  Cancel as CloseCircleIcon,
  Sync as SyncIcon,
  Stop as StopIcon,
  Visibility as VisibilityIcon,
  Warning as WarningIcon,
  Storage as StorageIcon,
  Refresh as RefreshIcon,
  ExpandMore as ExpandMoreIcon,
} from '@mui/icons-material'
import { useTranslation } from 'react-i18next'
import { api } from '../services/api'
import type { WorkflowPipeline, RealtimePipelineMode, TargetModelMapping, ExpansionMode } from '../types/pipeline'
import { createDefaultStages, removeAutoGeneratedStages } from '../utils/defaultStages'
import { useSnackbar } from '../hooks/useSnackbar'
import { ConfirmDialog } from '../components/common/ConfirmDialog'
import { PipelineEditor } from '../components/PipelineEditor'

interface TabPanelProps {
  children?: React.ReactNode
  index: number
  value: number
}

function TabPanel(props: TabPanelProps) {
  const { children, value, index, ...other } = props
  return (
    <div role="tabpanel" hidden={value !== index} {...other}>
      {value === index && <Box sx={{ pt: 2 }}>{children}</Box>}
    </div>
  )
}

interface Workflow {
  id: string
  project_id: string
  name: string
  slug: string
  description?: string
  type: 'batch' | 'realtime'
  execution_mode: string
  status: string
  schedule_enabled: boolean
  pipelines_config?: string
  pipelines?: WorkflowPipeline[]
  created_at: string
  updated_at: string
  project?: {
    id: string
    name: string
    alias: string
  }
}

interface DataType {
  id: string
  name: string
  display_name: string
  parent_id?: string | null
}

interface WorkflowExecution {
  id: string
  workflow_id: string
  status: string
  started_at: string
  completed_at?: string
  total_records: number
  failed_records: number
  error_message?: string
  triggered_by?: string
  created_at: string
}

interface PipelineExecutionResult {
  pipeline_id: string
  pipeline_name: string
  status: string
  started_at: string
  completed_at?: string
  records_read: number
  records_written: number
  records_processed: number
  records_failed: number
  error_message?: string
}

interface ExecutionDetail {
  id: string
  workflow_id: string
  status: string
  started_at: string
  completed_at?: string
  duration_ms?: number
  total_records: number
  failed_records: number
  error_message?: string
  triggered_by?: string
  triggered_by_id?: string
  created_at: string
  pipelines_snapshot?: WorkflowPipeline[]
  pipeline_results?: PipelineExecutionResult[]
}

interface SourceCheckpoint {
  id: string
  workflow_id: string
  pipeline_id: string
  pipeline_name: string
  source_type: string
  partition_key: string
  offset_value: string
  offset_type: string
  record_count: number
  metadata?: string
  created_at: string
  updated_at: string
}

interface MonitoringCheckpoint {
  partition_key: string
  offset_value: string
  offset_type: string
  record_count?: number
}

interface MonitoringSample {
  timestamp: string
  data: Record<string, unknown>
}

interface MonitoringStage {
  name: string
  type: string
  input_count?: number
  output_count?: number
  error_count?: number
  samples?: MonitoringSample[]
}

interface MonitoringPipeline {
  pipeline_id: string
  pipeline_name?: string
  status: string
  checkpoints?: MonitoringCheckpoint[]
  stages?: MonitoringStage[]
}

interface MonitoringResponse {
  data?: {
    pipelines?: MonitoringPipeline[]
  }
}

export default function WorkflowDetailPage() {
  const { t } = useTranslation()
  const { id, workflowId } = useParams<{ id?: string; workflowId?: string }>()
  const effectiveId = id || workflowId
  const navigate = useNavigate()
  const { showSuccess, showError } = useSnackbar()
  const [workflow, setWorkflow] = useState<Workflow | null>(null)
  const [pipelines, setPipelines] = useState<WorkflowPipeline[]>([])
  const [dataTypes, setDataTypes] = useState<DataType[]>([])
  const [executions, setExecutions] = useState<WorkflowExecution[]>([])
  const [loading, setLoading] = useState(true)
  const [tabValue, setTabValue] = useState(1) // Default to pipelines tab

  // Pipeline modal states
  const [pipelineModalOpen, setPipelineModalOpen] = useState(false)
  const [editingPipeline, setEditingPipeline] = useState<WorkflowPipeline | null>(null)
  const [pipelineForm, setPipelineForm] = useState({
    name: '',
    description: '',
    priority: 0,
    parent_pipeline_id: '',
    target_data_type_id: '',
    expansion_mode: 'none' as ExpansionMode,
    realtime_mode: 'cdc' as RealtimePipelineMode,
    target_models: [] as { model_id: string; discriminator_value: string }[],
    discriminator_field: '',
    parameter_bindings: [] as { parent_field: string; child_param: string }[],
  })
  const [saving, setSaving] = useState(false)
  const [selectedParentPipeline, setSelectedParentPipeline] = useState<string | undefined>()
  const [actionLoading, setActionLoading] = useState(false)
  const [deletePipelineId, setDeletePipelineId] = useState<string | null>(null)

  // Pipeline Editor states (듀얼 에디터)
  const [pipelineEditorOpen, setPipelineEditorOpen] = useState(false)
  const [pipelineToEdit, setPipelineToEdit] = useState<WorkflowPipeline | null>(null)

  // Execution detail modal states
  const [executionDetailOpen, setExecutionDetailOpen] = useState(false)
  const [executionDetail, setExecutionDetail] = useState<ExecutionDetail | null>(null)
  const [executionDetailLoading, setExecutionDetailLoading] = useState(false)

  // Checkpoint states
  const [checkpoints, setCheckpoints] = useState<SourceCheckpoint[]>([])
  const [checkpointsLoading, setCheckpointsLoading] = useState(false)
  const [resetModalOpen, setResetModalOpen] = useState(false)
  const [resetPipelineId, setResetPipelineId] = useState<string | null>(null)
  const [resetMode, setResetMode] = useState<'specific_time' | 'beginning' | 'specific_offset'>('specific_time')
  const [resetTimestamp, setResetTimestamp] = useState<Dayjs | null>(null)
  const [resetOffsetValue, setResetOffsetValue] = useState('')
  const [resetting, setResetting] = useState(false)
  const [deleteCheckpointPipelineId, setDeleteCheckpointPipelineId] = useState<string | null>(null)

  // Monitoring states
  const [monitoringData, setMonitoringData] = useState<MonitoringResponse | null>(null)
  const [monitoringLoading, setMonitoringLoading] = useState(false)
  const [monitoringInterval, setMonitoringInterval] = useState<ReturnType<typeof setInterval> | null>(null)
  const [runningExecutionId, setRunningExecutionId] = useState<string | null>(null)

  const fetchMonitoringData = useCallback(async (executionId: string) => {
    if (!effectiveId) return
    try {
      setMonitoringLoading(true)
      const res = await api.getWorkflowExecutionMonitoring(effectiveId, executionId)
      if (res.success && res.data) {
        setMonitoringData(res.data)
      }
    } catch (error) {
      console.error('Failed to fetch monitoring data:', error)
    } finally {
      setMonitoringLoading(false)
    }
  }, [effectiveId])

  const fetchWorkflowData = useCallback(async () => {
    try {
      setLoading(true)
      const workflowRes = await api.getWorkflow(effectiveId!)
      if (workflowRes.success && workflowRes.data) {
        setWorkflow(workflowRes.data)
        if (workflowRes.data.pipelines) {
          setPipelines(workflowRes.data.pipelines)
        } else if (workflowRes.data.pipelines_config) {
          try {
            const parsed = JSON.parse(workflowRes.data.pipelines_config)
            setPipelines(parsed || [])
          } catch {
            setPipelines([])
          }
        }
        if (workflowRes.data.project_id) {
          const dataTypesRes = await api.getProjectDataTypes(workflowRes.data.project_id)
          if (dataTypesRes.success) {
            setDataTypes(dataTypesRes.data || [])
          }
        }
        const executionsRes = await api.getWorkflowExecutions(effectiveId!)
        if (executionsRes.success) {
          setExecutions(executionsRes.data || [])
        }
      }
    } catch (error) {
      showError(t('workflow.loadError'))
    } finally {
      setLoading(false)
    }
  }, [effectiveId, showError, t])

  useEffect(() => {
    if (effectiveId) {
      fetchWorkflowData()
    }
  }, [effectiveId, fetchWorkflowData])

  // 실행 중인 execution 찾기 및 모니터링 시작
  useEffect(() => {
    const runningExec = executions.find(e => e.status === 'running')
    if (runningExec && runningExec.id !== runningExecutionId) {
      setRunningExecutionId(runningExec.id)
      fetchMonitoringData(runningExec.id)
      const interval = setInterval(() => {
        fetchMonitoringData(runningExec.id)
      }, 5000)
      setMonitoringInterval(interval)
    } else if (!runningExec && monitoringInterval) {
      clearInterval(monitoringInterval)
      setMonitoringInterval(null)
      setRunningExecutionId(null)
      setMonitoringData(null)
    }
    return () => {
      if (monitoringInterval) {
        clearInterval(monitoringInterval)
      }
    }
  }, [executions, runningExecutionId, fetchMonitoringData, monitoringInterval])

  const fetchCheckpoints = async () => {
    if (!effectiveId) return
    try {
      setCheckpointsLoading(true)
      const res = await api.getWorkflowCheckpoints(effectiveId)
      if (res.success && res.data) {
        setCheckpoints(res.data.checkpoints || [])
      }
    } catch (error) {
      console.error('Failed to fetch checkpoints:', error)
    } finally {
      setCheckpointsLoading(false)
    }
  }

  const handleResetCheckpoint = (pipelineId: string) => {
    setResetPipelineId(pipelineId)
    setResetMode('specific_time')
    setResetTimestamp(null)
    setResetOffsetValue('')
    setResetModalOpen(true)
  }

  const handleResetSubmit = async () => {
    if (!resetPipelineId) return
    try {
      setResetting(true)

      const data: {
        mode: 'specific_time' | 'beginning' | 'specific_offset'
        timestamp?: string
        offset_value?: string
      } = { mode: resetMode }

      if (resetMode === 'specific_time' && resetTimestamp) {
        data.timestamp = resetTimestamp.toISOString()
      } else if (resetMode === 'specific_offset' && resetOffsetValue) {
        data.offset_value = resetOffsetValue
      }

      const res = await api.resetPipelineCheckpoints(resetPipelineId, data)
      if (res.success) {
        showSuccess(t('checkpoint.resetSuccess'))
        setResetModalOpen(false)
        fetchCheckpoints()
      } else {
        showError(res.error?.message || t('checkpoint.resetError'))
      }
    } catch (error) {
      showError(t('checkpoint.resetError'))
    } finally {
      setResetting(false)
    }
  }

  const handleDeleteCheckpoints = async () => {
    if (!deleteCheckpointPipelineId) return
    try {
      const res = await api.deletePipelineCheckpoints(deleteCheckpointPipelineId)
      if (res.success) {
        showSuccess(t('checkpoint.deleteSuccess'))
        setDeleteCheckpointPipelineId(null)
        fetchCheckpoints()
      } else {
        showError(res.error?.message || t('checkpoint.deleteError'))
      }
    } catch (error) {
      showError(t('checkpoint.deleteError'))
    }
  }

  const handleStartWorkflow = async () => {
    if (!effectiveId) return
    try {
      setActionLoading(true)
      const res = await api.startWorkflow(effectiveId)
      if (res.success) {
        showSuccess(t('workflow.startSuccess'))
        fetchWorkflowData()
      } else {
        showError(res.error?.message || t('workflow.startError'))
      }
    } catch (error: unknown) {
      const err = error as { response?: { data?: { error?: { message?: string } } } }
      showError(err.response?.data?.error?.message || t('workflow.startError'))
    } finally {
      setActionLoading(false)
    }
  }

  const handleStopWorkflow = async () => {
    if (!effectiveId) return
    try {
      setActionLoading(true)
      const res = await api.stopWorkflow(effectiveId)
      if (res.success) {
        showSuccess(t('workflow.stopSuccess'))
        fetchWorkflowData()
      } else {
        showError(res.error?.message || t('workflow.stopError'))
      }
    } catch (error: unknown) {
      const err = error as { response?: { data?: { error?: { message?: string } } } }
      showError(err.response?.data?.error?.message || t('workflow.stopError'))
    } finally {
      setActionLoading(false)
    }
  }

  const handleViewExecutionDetail = async (executionId: string) => {
    if (!effectiveId) return
    try {
      setExecutionDetailLoading(true)
      setExecutionDetailOpen(true)
      const res = await api.getWorkflowExecution(effectiveId, executionId)
      if (res.success && res.data) {
        setExecutionDetail(res.data)
      } else {
        showError(t('workflow.executionDetailError'))
      }
    } catch (error) {
      showError(t('workflow.executionDetailError'))
    } finally {
      setExecutionDetailLoading(false)
    }
  }

  const handleCreatePipeline = () => {
    setEditingPipeline(null)
    setSelectedParentPipeline(undefined)
    setPipelineForm({
      name: '',
      description: '',
      priority: pipelines.length,
      parent_pipeline_id: '',
      target_data_type_id: '',
      expansion_mode: 'none',
      realtime_mode: workflow?.type === 'realtime' ? 'cdc' : 'cdc',
      target_models: workflow?.type === 'realtime' ? [{ model_id: '', discriminator_value: '' }] : [],
      discriminator_field: '',
      parameter_bindings: [],
    })
    setPipelineModalOpen(true)
  }

  const handleEditPipeline = (pipeline: WorkflowPipeline) => {
    setEditingPipeline(pipeline)
    setSelectedParentPipeline(pipeline.parent_pipeline_id || undefined)

    const targetModels = pipeline.target_models?.map(tm => ({
      model_id: tm.model_id,
      discriminator_value: tm.discriminator_value || '',
    })) || (pipeline.target_data_type_id ? [{ model_id: pipeline.target_data_type_id, discriminator_value: '' }] : [])

    setPipelineForm({
      name: pipeline.name,
      description: pipeline.description || '',
      priority: pipeline.priority,
      parent_pipeline_id: pipeline.parent_pipeline_id || '',
      target_data_type_id: pipeline.target_data_type_id || '',
      expansion_mode: pipeline.expansion_mode || 'none',
      realtime_mode: pipeline.realtime_mode || 'cdc',
      target_models: targetModels,
      discriminator_field: pipeline.discriminator_field || '',
      parameter_bindings: pipeline.parameter_bindings || [],
    })
    setPipelineModalOpen(true)
  }

  const handleDeletePipeline = async () => {
    if (!deletePipelineId) return
    const hasChildren = pipelines.some(p => p.parent_pipeline_id === deletePipelineId)
    if (hasChildren) {
      showError(t('pipeline.cannotDeleteHasChildren'))
      setDeletePipelineId(null)
      return
    }

    const newPipelines = pipelines.filter(p => p.id !== deletePipelineId)
    await savePipelines(newPipelines)
    setDeletePipelineId(null)
  }

  const handlePipelineSubmit = async () => {
    try {
      setSaving(true)

      const workflowType = workflow?.type || 'batch'
      const newRealtimeMode = pipelineForm.realtime_mode
      const oldRealtimeMode = editingPipeline?.realtime_mode

      let stages = editingPipeline?.stages || []

      if (!editingPipeline) {
        stages = createDefaultStages(workflowType, newRealtimeMode)
      } else if (workflowType === 'realtime' && oldRealtimeMode !== newRealtimeMode) {
        const userStages = removeAutoGeneratedStages(stages)
        const newDefaultStages = createDefaultStages(workflowType, newRealtimeMode)
        stages = [...newDefaultStages, ...userStages]
      }

      let targetModels: TargetModelMapping[] | undefined
      let discriminatorField: string | undefined
      let targetDataTypeId: string | null = null

      if (workflowType === 'realtime') {
        targetModels = pipelineForm.target_models
          .filter(tm => tm.model_id)
          .map(tm => ({
            model_id: tm.model_id,
            discriminator_value: tm.discriminator_value || undefined,
          }))
        discriminatorField = pipelineForm.discriminator_field || undefined
      } else {
        targetDataTypeId = pipelineForm.target_data_type_id || null
      }

      // input/source 설정 (하위 호환성 유지)
      const inputSource = editingPipeline?.input || editingPipeline?.source || { type: 'rest_api', name: pipelineForm.name, config: {} }

      const pipelineData: WorkflowPipeline = {
        id: editingPipeline?.id || crypto.randomUUID(),
        name: pipelineForm.name,
        description: pipelineForm.description,
        priority: pipelineForm.priority,
        input: inputSource,    // 권장 필드
        source: inputSource,   // 하위 호환성
        parent_pipeline_id: pipelineForm.parent_pipeline_id || null,
        target_data_type_id: targetDataTypeId,
        expansion_mode: pipelineForm.expansion_mode || 'none',
        parameter_bindings: pipelineForm.parameter_bindings,
        stages,
        realtime_mode: workflowType === 'realtime' ? newRealtimeMode : undefined,
        target_models: targetModels,
        discriminator_field: discriminatorField,
      }

      let newPipelines: WorkflowPipeline[]
      if (editingPipeline) {
        newPipelines = pipelines.map(p => p.id === editingPipeline.id ? pipelineData : p)
      } else {
        newPipelines = [...pipelines, pipelineData]
      }

      await savePipelines(newPipelines)
      setPipelineModalOpen(false)
    } catch (error) {
      showError(t('common.saveError'))
    } finally {
      setSaving(false)
    }
  }

  const savePipelines = async (newPipelines: WorkflowPipeline[]) => {
    try {
      const response = await api.updateWorkflow(effectiveId!, {
        pipelines: newPipelines,
      })
      if (response.success) {
        setPipelines(newPipelines)
        showSuccess(t('common.saveSuccess'))
      } else {
        showError(response.error || t('common.saveError'))
      }
    } catch (error) {
      showError(t('common.saveError'))
    }
  }

  // Pipeline Editor 열기 (듀얼 에디터)
  const handleOpenPipelineEditor = (pipeline: WorkflowPipeline) => {
    setPipelineToEdit(pipeline)
    setPipelineEditorOpen(true)
  }

  // Pipeline Editor에서 저장
  const handlePipelineEditorSave = async (updatedPipeline: WorkflowPipeline) => {
    const newPipelines = pipelines.map(p => p.id === updatedPipeline.id ? updatedPipeline : p)
    await savePipelines(newPipelines)
    setPipelineEditorOpen(false)
    setPipelineToEdit(null)
  }

  // Pipeline Editor 닫기
  const handlePipelineEditorClose = () => {
    setPipelineEditorOpen(false)
    setPipelineToEdit(null)
  }

  const handleParentPipelineChange = (parentId: string | undefined) => {
    setSelectedParentPipeline(parentId)
    if (parentId) {
      const parentPipeline = pipelines.find(p => p.id === parentId)
      if (parentPipeline?.target_data_type_id) {
        setPipelineForm(prev => ({
          ...prev,
          parent_pipeline_id: parentId,
          target_data_type_id: parentPipeline.target_data_type_id || '',
          expansion_mode: 'for_each_record',
        }))
      } else {
        setPipelineForm(prev => ({
          ...prev,
          parent_pipeline_id: parentId,
        }))
      }
    } else {
      setPipelineForm(prev => ({
        ...prev,
        parent_pipeline_id: '',
        expansion_mode: 'none',
        parameter_bindings: [],
      }))
    }
  }

  const getStatusConfig = (status: string) => {
    const configs: Record<string, { color: 'default' | 'success' | 'warning' | 'error' | 'primary'; text: string }> = {
      idle: { color: 'default', text: t('pipeline.status.idle') },
      running: { color: 'success', text: t('pipeline.status.running') },
      paused: { color: 'warning', text: t('pipeline.status.paused') },
      stopped: { color: 'default', text: t('pipeline.status.stopped') },
      error: { color: 'error', text: t('pipeline.status.error') },
      completed: { color: 'primary', text: t('pipeline.status.completed') },
    }
    return configs[status] || { color: 'default' as const, text: status }
  }

  const getPipelineDepth = (pipeline: WorkflowPipeline): number => {
    let depth = 0
    let currentParentId = pipeline.parent_pipeline_id
    while (currentParentId) {
      depth++
      const parent = pipelines.find(p => p.id === currentParentId)
      currentParentId = parent?.parent_pipeline_id || null
    }
    return depth
  }

  const getHierarchicalPipelines = (): WorkflowPipeline[] => {
    const result: WorkflowPipeline[] = []
    const addWithChildren = (parentId: string | null) => {
      const children = pipelines
        .filter(p => (p.parent_pipeline_id || null) === parentId)
        .sort((a, b) => a.priority - b.priority)
      for (const child of children) {
        result.push(child)
        addWithChildren(child.id)
      }
    }
    addWithChildren(null)
    return result
  }

  const hierarchicalPipelines = getHierarchicalPipelines()

  const handleTabChange = (_event: React.SyntheticEvent, newValue: number) => {
    setTabValue(newValue)
    // Load checkpoints when switching to checkpoints tab
    if (newValue === 4 && workflow?.type === 'realtime') {
      fetchCheckpoints()
    }
  }

  // Add/remove target model handlers
  const addTargetModel = () => {
    setPipelineForm(prev => ({
      ...prev,
      target_models: [...prev.target_models, { model_id: '', discriminator_value: '' }],
    }))
  }

  const removeTargetModel = (index: number) => {
    setPipelineForm(prev => ({
      ...prev,
      target_models: prev.target_models.filter((_, i) => i !== index),
    }))
  }

  const updateTargetModel = (index: number, field: 'model_id' | 'discriminator_value', value: string) => {
    setPipelineForm(prev => ({
      ...prev,
      target_models: prev.target_models.map((tm, i) =>
        i === index ? { ...tm, [field]: value } : tm
      ),
    }))
  }

  // Add/remove parameter binding handlers
  const addParameterBinding = () => {
    setPipelineForm(prev => ({
      ...prev,
      parameter_bindings: [...prev.parameter_bindings, { parent_field: 'id', child_param: '' }],
    }))
  }

  const removeParameterBinding = (index: number) => {
    setPipelineForm(prev => ({
      ...prev,
      parameter_bindings: prev.parameter_bindings.filter((_, i) => i !== index),
    }))
  }

  const updateParameterBinding = (index: number, field: 'parent_field' | 'child_param', value: string) => {
    setPipelineForm(prev => ({
      ...prev,
      parameter_bindings: prev.parameter_bindings.map((pb, i) =>
        i === index ? { ...pb, [field]: value } : pb
      ),
    }))
  }

  if (loading) {
    return (
      <Box sx={{ display: 'flex', justifyContent: 'center', py: 6 }}>
        <CircularProgress />
      </Box>
    )
  }

  if (!workflow) {
    return (
      <Box sx={{ textAlign: 'center', py: 6 }}>
        <Typography color="text.secondary" sx={{ mb: 2 }}>{t('workflow.notFound')}</Typography>
        <Button variant="contained" onClick={() => navigate(-1)}>
          {t('common.back')}
        </Button>
      </Box>
    )
  }

  const statusConfig = getStatusConfig(workflow.status)

  // Build tab list
  const tabList = [
    { label: t('project.overview'), icon: <SettingsIcon /> },
    { label: `${t('pipeline.title')} (${pipelines.length})`, icon: <BranchesIcon /> },
    { label: `${t('workflow.executions')} (${executions.length})`, icon: <HistoryIcon /> },
  ]

  if (runningExecutionId) {
    tabList.push({ label: t('workflow.monitoring'), icon: <SyncIcon /> })
  }

  if (workflow.type === 'realtime') {
    tabList.push({ label: t('checkpoint.title'), icon: <StorageIcon /> })
  }

  return (
    <LocalizationProvider dateAdapter={AdapterDayjs}>
      <Box>
        <Breadcrumbs sx={{ mb: 2 }}>
          <Link component="button" underline="hover" color="inherit" onClick={() => navigate('/projects')}>
            {t('project.title')}
          </Link>
          {workflow.project && (
            <Link component="button" underline="hover" color="inherit" onClick={() => navigate(`/projects/${workflow.project_id}`)}>
              {workflow.project.name}
            </Link>
          )}
          <Typography color="text.primary">{workflow.name}</Typography>
        </Breadcrumbs>

        <Box sx={{ mb: 2, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <Box sx={{ display: 'flex', alignItems: 'center', gap: 2 }}>
            <Button startIcon={<ArrowBackIcon />} onClick={() => navigate(-1)}>
              {t('common.back')}
            </Button>
            <Typography variant="h5">{workflow.name}</Typography>
            <Chip
              label={workflow.type === 'realtime' ? t('workflow.realtime') : t('workflow.batch')}
              color={workflow.type === 'realtime' ? 'primary' : 'secondary'}
              size="small"
            />
            <Chip label={statusConfig.text} color={statusConfig.color} size="small" />
          </Box>
          <Box sx={{ display: 'flex', gap: 1 }}>
            {workflow.status === 'running' ? (
              <Button
                startIcon={<PauseCircleIcon />}
                onClick={handleStopWorkflow}
                disabled={actionLoading}
              >
                {actionLoading ? <CircularProgress size={20} /> : t('workflow.stop')}
              </Button>
            ) : (
              <Button
                variant="contained"
                startIcon={<PlayCircleIcon />}
                onClick={handleStartWorkflow}
                disabled={actionLoading}
              >
                {actionLoading ? <CircularProgress size={20} /> : t('workflow.start')}
              </Button>
            )}
          </Box>
        </Box>

        <Tabs value={tabValue} onChange={handleTabChange} sx={{ borderBottom: 1, borderColor: 'divider' }}>
          {tabList.map((tab, index) => (
            <Tab key={index} icon={tab.icon} iconPosition="start" label={tab.label} />
          ))}
        </Tabs>

        {/* Overview Tab */}
        <TabPanel value={tabValue} index={0}>
          <Card>
            <CardContent>
              <TableContainer component={Paper} variant="outlined">
                <Table>
                  <TableBody>
                    <TableRow>
                      <TableCell component="th" sx={{ width: 150, bgcolor: 'grey.50' }}>{t('workflow.name')}</TableCell>
                      <TableCell>{workflow.name}</TableCell>
                      <TableCell component="th" sx={{ width: 150, bgcolor: 'grey.50' }}>{t('workflow.slug')}</TableCell>
                      <TableCell><code>{workflow.slug}</code></TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.type')}</TableCell>
                      <TableCell>
                        <Chip
                          label={workflow.type === 'realtime' ? t('workflow.realtime') : t('workflow.batch')}
                          color={workflow.type === 'realtime' ? 'primary' : 'secondary'}
                          size="small"
                        />
                      </TableCell>
                      <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.executionMode')}</TableCell>
                      <TableCell><Chip label={workflow.execution_mode} size="small" /></TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('common.status')}</TableCell>
                      <TableCell>
                        <Chip label={statusConfig.text} color={statusConfig.color} size="small" />
                      </TableCell>
                      <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.enabled')}</TableCell>
                      <TableCell>
                        <Chip
                          label={workflow.schedule_enabled ? t('workflow.on') : t('workflow.off')}
                          color={workflow.schedule_enabled ? 'success' : 'default'}
                          size="small"
                        />
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('common.description')}</TableCell>
                      <TableCell colSpan={3}>{workflow.description || '-'}</TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('common.createdAt')}</TableCell>
                      <TableCell>{new Date(workflow.created_at).toLocaleString()}</TableCell>
                      <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('common.updatedAt')}</TableCell>
                      <TableCell>{new Date(workflow.updated_at).toLocaleString()}</TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </TableContainer>
            </CardContent>
          </Card>
        </TabPanel>

        {/* Pipelines Tab */}
        <TabPanel value={tabValue} index={1}>
          <Card>
            <CardHeader
              title={t('pipeline.title')}
              subheader={t('pipeline.hierarchyHelp')}
              action={
                <Button variant="contained" startIcon={<AddIcon />} onClick={handleCreatePipeline}>
                  {t('pipeline.new')}
                </Button>
              }
            />
            <CardContent>
              {pipelines.length > 0 ? (
                <TableContainer component={Paper} variant="outlined">
                  <Table>
                    <TableHead>
                      <TableRow>
                        <TableCell>{t('pipeline.name')}</TableCell>
                        <TableCell sx={{ width: 120 }}>{t('pipeline.source')}</TableCell>
                        <TableCell sx={{ width: 120 }}>{t('pipeline.output')}</TableCell>
                        <TableCell sx={{ width: 80 }}>{t('pipeline.priority')}</TableCell>
                        <TableCell sx={{ width: 200 }}>{t('common.actions')}</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {hierarchicalPipelines.map((pipeline) => {
                        const depth = getPipelineDepth(pipeline)
                        const targetDataType = dataTypes.find(dt => dt.id === pipeline.target_data_type_id)
                        const hasChildren = pipelines.some(p => p.parent_pipeline_id === pipeline.id)
                        const outputTypes = ['sql', 'elasticsearch', 'kafka', 'mongodb', 's3', 'rest_api', 'file']
                        const outputStages = pipeline.stages?.filter(s => outputTypes.includes(s.type)) || []
                        return (
                          <TableRow key={pipeline.id}>
                            <TableCell>
                              <Box sx={{ pl: depth * 3 }}>
                                <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
                                  {depth > 0 && (
                                    <Typography color="text.secondary" sx={{ fontSize: 12 }}>--</Typography>
                                  )}
                                  <Typography>{pipeline.name}</Typography>
                                  {pipeline.expansion_mode === 'for_each_record' && (
                                    <Chip icon={<BranchesIcon />} label={t('pipeline.expansion')} color="secondary" size="small" />
                                  )}
                                </Box>
                                {targetDataType && (
                                  <Typography variant="caption" color="text.secondary" sx={{ pl: depth > 0 ? 2.5 : 0 }}>
                                    {t('pipeline.targetDataModel')}: <code>{targetDataType.display_name}</code>
                                  </Typography>
                                )}
                              </Box>
                            </TableCell>
                            <TableCell>
                              <Chip label={pipeline.source?.type || '-'} size="small" />
                            </TableCell>
                            <TableCell>
                              <Box sx={{ display: 'flex', gap: 0.5, flexWrap: 'wrap' }}>
                                {outputStages.slice(0, 2).map((stage, i) => (
                                  <Chip key={i} label={stage.type} size="small" />
                                ))}
                                {outputStages.length > 2 && <Chip label={`+${outputStages.length - 2}`} size="small" />}
                                {outputStages.length === 0 && <Chip label="-" size="small" variant="outlined" />}
                              </Box>
                            </TableCell>
                            <TableCell>{pipeline.priority}</TableCell>
                            <TableCell>
                              <Box sx={{ display: 'flex', gap: 0.5 }}>
                                <IconButton
                                  size="small"
                                  onClick={() => handleOpenPipelineEditor(pipeline)}
                                  title={t('pipelineEditor.openEditor')}
                                  color="primary"
                                >
                                  <SettingsIcon fontSize="small" />
                                </IconButton>
                                <IconButton
                                  size="small"
                                  onClick={() => handleEditPipeline(pipeline)}
                                  title={t('pipeline.editMetadata')}
                                >
                                  <EditIcon fontSize="small" />
                                </IconButton>
                                {!hasChildren && (
                                  <IconButton
                                    size="small"
                                    color="error"
                                    onClick={() => setDeletePipelineId(pipeline.id)}
                                  >
                                    <DeleteIcon fontSize="small" />
                                  </IconButton>
                                )}
                              </Box>
                            </TableCell>
                          </TableRow>
                        )
                      })}
                    </TableBody>
                  </Table>
                </TableContainer>
              ) : (
                <Box sx={{ textAlign: 'center', py: 6 }}>
                  <Typography color="text.secondary" sx={{ mb: 2 }}>{t('pipeline.noPipelines')}</Typography>
                  <Button variant="contained" onClick={handleCreatePipeline}>
                    {t('pipeline.new')}
                  </Button>
                </Box>
              )}
            </CardContent>
          </Card>
        </TabPanel>

        {/* Executions Tab */}
        <TabPanel value={tabValue} index={2}>
          <Card>
            <CardHeader title={t('workflow.executionHistory')} />
            <CardContent>
              {executions.length > 0 ? (
                <TableContainer component={Paper} variant="outlined">
                  <Table>
                    <TableHead>
                      <TableRow>
                        <TableCell sx={{ width: 120 }}>{t('common.status')}</TableCell>
                        <TableCell>{t('workflow.startedAt')}</TableCell>
                        <TableCell>{t('workflow.completedAt')}</TableCell>
                        <TableCell>{t('workflow.duration')}</TableCell>
                        <TableCell align="right">{t('workflow.totalRecords')}</TableCell>
                        <TableCell align="right">{t('workflow.failedRecords')}</TableCell>
                        <TableCell>{t('workflow.errorMessage')}</TableCell>
                        <TableCell sx={{ width: 80 }}>{t('common.actions')}</TableCell>
                      </TableRow>
                    </TableHead>
                    <TableBody>
                      {executions.map((exec) => {
                        const start = new Date(exec.started_at).getTime()
                        const end = exec.completed_at ? new Date(exec.completed_at).getTime() : Date.now()
                        const duration = Math.round((end - start) / 1000)
                        let durationStr = '-'
                        if (exec.started_at) {
                          if (duration < 60) durationStr = `${duration}s`
                          else if (duration < 3600) durationStr = `${Math.floor(duration / 60)}m ${duration % 60}s`
                          else durationStr = `${Math.floor(duration / 3600)}h ${Math.floor((duration % 3600) / 60)}m`
                        }

                        const execStatusConfig: Record<string, { color: 'success' | 'info' | 'error' | 'default'; icon: React.ReactNode }> = {
                          completed: { color: 'success', icon: <CheckCircleIcon fontSize="small" /> },
                          running: { color: 'info', icon: <SyncIcon fontSize="small" /> },
                          error: { color: 'error', icon: <CloseCircleIcon fontSize="small" /> },
                          stopped: { color: 'default', icon: <StopIcon fontSize="small" /> },
                        }
                        const execConfig = execStatusConfig[exec.status] || { color: 'default' as const, icon: null }

                        return (
                          <TableRow key={exec.id}>
                            <TableCell>
                              <Chip
                                icon={execConfig.icon as React.ReactElement}
                                label={t(`pipeline.status.${exec.status}`)}
                                color={execConfig.color}
                                size="small"
                              />
                            </TableCell>
                            <TableCell>{exec.started_at ? new Date(exec.started_at).toLocaleString() : '-'}</TableCell>
                            <TableCell>{exec.completed_at ? new Date(exec.completed_at).toLocaleString() : '-'}</TableCell>
                            <TableCell>{durationStr}</TableCell>
                            <TableCell align="right">{exec.total_records}</TableCell>
                            <TableCell align="right">
                              {exec.failed_records > 0 ? (
                                <Typography color="error">{exec.failed_records}</Typography>
                              ) : exec.failed_records}
                            </TableCell>
                            <TableCell sx={{ maxWidth: 200, overflow: 'hidden', textOverflow: 'ellipsis' }}>
                              {exec.error_message ? (
                                <Typography color="error" noWrap title={exec.error_message}>
                                  {exec.error_message}
                                </Typography>
                              ) : '-'}
                            </TableCell>
                            <TableCell>
                              <IconButton
                                size="small"
                                onClick={() => handleViewExecutionDetail(exec.id)}
                                title={t('workflow.viewExecutionDetail')}
                              >
                                <VisibilityIcon fontSize="small" />
                              </IconButton>
                            </TableCell>
                          </TableRow>
                        )
                      })}
                    </TableBody>
                  </Table>
                </TableContainer>
              ) : (
                <Box sx={{ textAlign: 'center', py: 6 }}>
                  <Typography color="text.secondary">{t('workflow.noExecutions')}</Typography>
                </Box>
              )}
            </CardContent>
          </Card>
        </TabPanel>

        {/* Monitoring Tab (only when running) */}
        {runningExecutionId && (
          <TabPanel value={tabValue} index={3}>
            <Card>
              <CardHeader
                title={t('workflow.monitoring')}
                action={
                  <Button
                    startIcon={<RefreshIcon />}
                    onClick={() => runningExecutionId && fetchMonitoringData(runningExecutionId)}
                    disabled={monitoringLoading}
                  >
                    {t('common.refresh')}
                  </Button>
                }
              />
              <CardContent>
                {monitoringLoading && !monitoringData ? (
                  <Box sx={{ textAlign: 'center', py: 5 }}>
                    <CircularProgress />
                  </Box>
                ) : (monitoringData?.data?.pipelines?.length ?? 0) > 0 ? (
                  monitoringData?.data?.pipelines?.map((pipeline: MonitoringPipeline) => (
                    <Card key={pipeline.pipeline_id} variant="outlined" sx={{ mb: 2 }}>
                      <CardHeader
                        title={
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <Typography>{pipeline.pipeline_name || pipeline.pipeline_id}</Typography>
                            <Chip
                              label={pipeline.status}
                              color={pipeline.status === 'running' ? 'success' : 'default'}
                              size="small"
                            />
                          </Box>
                        }
                        titleTypographyProps={{ variant: 'subtitle1' }}
                      />
                      <CardContent>
                        {/* Source Checkpoints */}
                        {(pipeline.checkpoints?.length ?? 0) > 0 && (
                          <Box sx={{ mb: 2 }}>
                            <Typography variant="subtitle2" sx={{ display: 'flex', alignItems: 'center', gap: 1, mb: 1 }}>
                              <StorageIcon fontSize="small" /> {t('checkpoint.sourceCheckpoints')}
                            </Typography>
                            <TableContainer component={Paper} variant="outlined">
                              <Table size="small">
                                <TableHead>
                                  <TableRow>
                                    <TableCell>{t('checkpoint.partition')}</TableCell>
                                    <TableCell>{t('checkpoint.offset')}</TableCell>
                                    <TableCell align="right">{t('checkpoint.recordCount')}</TableCell>
                                  </TableRow>
                                </TableHead>
                                <TableBody>
                                  {pipeline.checkpoints?.map((cp: MonitoringCheckpoint) => (
                                    <TableRow key={cp.partition_key}>
                                      <TableCell><code style={{ fontSize: 11 }}>{cp.partition_key}</code></TableCell>
                                      <TableCell>
                                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                                          <code style={{ fontSize: 11 }}>{cp.offset_value}</code>
                                          <Chip label={cp.offset_type} size="small" />
                                        </Box>
                                      </TableCell>
                                      <TableCell align="right">{cp.record_count?.toLocaleString() || 0}</TableCell>
                                    </TableRow>
                                  ))}
                                </TableBody>
                              </Table>
                            </TableContainer>
                          </Box>
                        )}

                        {/* Stages */}
                        {(pipeline.stages?.length ?? 0) > 0 && (
                          <Box>
                            <Typography variant="subtitle2" sx={{ mb: 1 }}>{t('stage.title')}</Typography>
                            {pipeline.stages?.map((stage: MonitoringStage) => (
                              <Accordion key={stage.name} variant="outlined">
                                <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                                  <Box sx={{ display: 'flex', alignItems: 'center', gap: 1, flexWrap: 'wrap' }}>
                                    <Typography>{stage.name}</Typography>
                                    <Chip label={stage.type} size="small" />
                                    <Chip label={`${t('stage.inputCount')}: ${stage.input_count?.toLocaleString() || 0}`} color="primary" size="small" />
                                    <Chip label={`${t('stage.outputCount')}: ${stage.output_count?.toLocaleString() || 0}`} color="success" size="small" />
                                    {(stage.error_count ?? 0) > 0 && (
                                      <Chip label={`${t('stage.errorCount')}: ${stage.error_count}`} color="error" size="small" />
                                    )}
                                  </Box>
                                </AccordionSummary>
                                <AccordionDetails>
                                  {/* Recent Data Samples */}
                                  {(stage.samples?.length ?? 0) > 0 && (
                                    <Box>
                                      <Typography variant="subtitle2" sx={{ mb: 1 }}>{t('workflow.recentDataSamples')}</Typography>
                                      <TableContainer component={Paper} variant="outlined">
                                        <Table size="small">
                                          <TableHead>
                                            <TableRow>
                                              <TableCell sx={{ width: 180 }}>{t('workflow.timestamp')}</TableCell>
                                              <TableCell>{t('workflow.data')}</TableCell>
                                            </TableRow>
                                          </TableHead>
                                          <TableBody>
                                            {stage.samples?.slice(0, 5).map((sample: MonitoringSample, idx: number) => (
                                              <TableRow key={idx}>
                                                <TableCell>{new Date(sample.timestamp).toLocaleString()}</TableCell>
                                                <TableCell>
                                                  <pre
                                                    style={{
                                                      margin: 0,
                                                      fontSize: 11,
                                                      maxHeight: 200,
                                                      overflow: 'auto',
                                                      background: '#f5f5f5',
                                                      padding: 8,
                                                      borderRadius: 4,
                                                      whiteSpace: 'pre-wrap',
                                                      wordBreak: 'break-word',
                                                    }}
                                                  >
                                                    {JSON.stringify(sample.data, null, 2)}
                                                  </pre>
                                                </TableCell>
                                              </TableRow>
                                            ))}
                                          </TableBody>
                                        </Table>
                                      </TableContainer>
                                    </Box>
                                  )}
                                </AccordionDetails>
                              </Accordion>
                            ))}
                          </Box>
                        )}
                      </CardContent>
                    </Card>
                  ))
                ) : (
                  <Box sx={{ textAlign: 'center', py: 6 }}>
                    <Typography color="text.secondary">{t('workflow.noMonitoringData')}</Typography>
                  </Box>
                )}
              </CardContent>
            </Card>
          </TabPanel>
        )}

        {/* Checkpoints Tab (only for realtime) */}
        {workflow.type === 'realtime' && (
          <TabPanel value={tabValue} index={runningExecutionId ? 4 : 3}>
            <Card>
              <CardHeader
                title={t('checkpoint.title')}
                action={
                  <Button
                    startIcon={<RefreshIcon />}
                    onClick={fetchCheckpoints}
                    disabled={checkpointsLoading}
                  >
                    {t('common.refresh')}
                  </Button>
                }
              />
              <CardContent>
                <Alert severity="info" sx={{ mb: 2 }}>
                  {t('checkpoint.description')}
                </Alert>
                {checkpointsLoading ? (
                  <Box sx={{ textAlign: 'center', py: 5 }}>
                    <CircularProgress />
                  </Box>
                ) : checkpoints.length > 0 ? (
                  Object.entries(
                    checkpoints.reduce((acc, cp) => {
                      const key = cp.pipeline_name || cp.pipeline_id
                      if (!acc[key]) acc[key] = { pipeline_id: cp.pipeline_id, pipeline_name: cp.pipeline_name, items: [] }
                      acc[key].items.push(cp)
                      return acc
                    }, {} as Record<string, { pipeline_id: string; pipeline_name: string; items: SourceCheckpoint[] }>)
                  ).map(([key, group]) => (
                    <Card key={key} variant="outlined" sx={{ mb: 2 }}>
                      <CardHeader
                        title={
                          <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                            <Typography>{group.pipeline_name || group.pipeline_id}</Typography>
                            <Chip label={group.items[0]?.source_type} size="small" />
                            <Chip label={`${group.items.length} ${t('checkpoint.partitions')}`} color="primary" size="small" />
                          </Box>
                        }
                        titleTypographyProps={{ variant: 'subtitle1' }}
                        action={
                          <Box sx={{ display: 'flex', gap: 1 }}>
                            <Button size="small" onClick={() => handleResetCheckpoint(group.pipeline_id)}>
                              {t('checkpoint.reset')}
                            </Button>
                            <Button size="small" color="error" onClick={() => setDeleteCheckpointPipelineId(group.pipeline_id)}>
                              {t('common.delete')}
                            </Button>
                          </Box>
                        }
                      />
                      <CardContent>
                        <TableContainer component={Paper} variant="outlined">
                          <Table size="small">
                            <TableHead>
                              <TableRow>
                                <TableCell>{t('checkpoint.partition')}</TableCell>
                                <TableCell>{t('checkpoint.offset')}</TableCell>
                                <TableCell align="right">{t('checkpoint.recordCount')}</TableCell>
                                <TableCell>{t('common.updatedAt')}</TableCell>
                              </TableRow>
                            </TableHead>
                            <TableBody>
                              {group.items.map((cp) => (
                                <TableRow key={cp.id}>
                                  <TableCell><code style={{ fontSize: 11 }}>{cp.partition_key}</code></TableCell>
                                  <TableCell>
                                    <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                                      <code style={{ fontSize: 11 }}>{cp.offset_value}</code>
                                      <Chip label={cp.offset_type} size="small" />
                                    </Box>
                                  </TableCell>
                                  <TableCell align="right">{cp.record_count?.toLocaleString() || 0}</TableCell>
                                  <TableCell>{new Date(cp.updated_at).toLocaleString()}</TableCell>
                                </TableRow>
                              ))}
                            </TableBody>
                          </Table>
                        </TableContainer>
                      </CardContent>
                    </Card>
                  ))
                ) : (
                  <Box sx={{ textAlign: 'center', py: 6 }}>
                    <Typography color="text.secondary">{t('checkpoint.noCheckpoints')}</Typography>
                    <Typography variant="body2" color="text.secondary">{t('checkpoint.noCheckpointsHelp')}</Typography>
                  </Box>
                )}
              </CardContent>
            </Card>
          </TabPanel>
        )}

        {/* Checkpoint Reset Modal */}
        <Dialog open={resetModalOpen} onClose={() => setResetModalOpen(false)} maxWidth="sm" fullWidth>
          <DialogTitle>{t('checkpoint.resetTitle')}</DialogTitle>
          <DialogContent>
            <Alert severity="warning" sx={{ mb: 2 }}>
              {t('checkpoint.resetWarning')}
            </Alert>
            <FormControl fullWidth sx={{ mb: 2 }}>
              <Typography variant="subtitle2" sx={{ mb: 1 }}>{t('checkpoint.resetMode')}</Typography>
              <RadioGroup value={resetMode} onChange={(e) => setResetMode(e.target.value as typeof resetMode)}>
                <FormControlLabel value="specific_time" control={<Radio />} label={t('checkpoint.resetModeSpecificTime')} />
                <FormControlLabel value="beginning" control={<Radio />} label={t('checkpoint.resetModeBeginning')} />
                <FormControlLabel value="specific_offset" control={<Radio />} label={t('checkpoint.resetModeSpecificOffset')} />
              </RadioGroup>
            </FormControl>

            {resetMode === 'specific_time' && (
              <DateTimePicker
                label={t('checkpoint.resetTimestamp')}
                value={resetTimestamp}
                onChange={setResetTimestamp}
                slotProps={{
                  textField: {
                    fullWidth: true,
                    placeholder: t('checkpoint.resetTimestampPlaceholder'),
                  },
                }}
              />
            )}

            {resetMode === 'specific_offset' && (
              <TextField
                label={t('checkpoint.resetOffsetValue')}
                value={resetOffsetValue}
                onChange={(e) => setResetOffsetValue(e.target.value)}
                fullWidth
                placeholder={t('checkpoint.resetOffsetPlaceholder')}
              />
            )}
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setResetModalOpen(false)}>{t('common.cancel')}</Button>
            <Button variant="contained" onClick={handleResetSubmit} disabled={resetting}>
              {resetting ? <CircularProgress size={20} /> : t('checkpoint.reset')}
            </Button>
          </DialogActions>
        </Dialog>

        {/* Pipeline Modal */}
        <Dialog open={pipelineModalOpen} onClose={() => setPipelineModalOpen(false)} maxWidth="sm" fullWidth>
          <DialogTitle>{editingPipeline ? t('pipeline.edit') : t('pipeline.new')}</DialogTitle>
          <DialogContent>
            <Box sx={{ display: 'flex', flexDirection: 'column', gap: 2, mt: 1 }}>
              <TextField
                label={t('pipeline.name')}
                value={pipelineForm.name}
                onChange={(e) => setPipelineForm({ ...pipelineForm, name: e.target.value })}
                required
                fullWidth
                placeholder={t('pipeline.namePlaceholder')}
              />
              <TextField
                label={t('common.description')}
                value={pipelineForm.description}
                onChange={(e) => setPipelineForm({ ...pipelineForm, description: e.target.value })}
                multiline
                rows={2}
                fullWidth
              />

              {/* Source mode selector - only for realtime workflows */}
              {workflow?.type === 'realtime' && (
                <FormControl fullWidth>
                  <InputLabel>{t('pipeline.sourceMode')}</InputLabel>
                  <Select
                    value={pipelineForm.realtime_mode}
                    label={t('pipeline.sourceMode')}
                    onChange={(e) => setPipelineForm({ ...pipelineForm, realtime_mode: e.target.value as RealtimePipelineMode })}
                  >
                    <MenuItem value="cdc">
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <Chip label="CDC" color="primary" size="small" />
                        <Typography variant="body2" color="text.secondary">{t('pipeline.sourceModeCdc')}</Typography>
                      </Box>
                    </MenuItem>
                    <MenuItem value="raw">
                      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                        <Chip label="RAW" size="small" />
                        <Typography variant="body2" color="text.secondary">{t('pipeline.sourceModeRaw')}</Typography>
                      </Box>
                    </MenuItem>
                  </Select>
                  <FormHelperText>{t('pipeline.sourceModeHelp')}</FormHelperText>
                </FormControl>
              )}

              <TextField
                label={t('pipeline.priority')}
                type="number"
                value={pipelineForm.priority}
                onChange={(e) => setPipelineForm({ ...pipelineForm, priority: parseInt(e.target.value) || 0 })}
                fullWidth
                helperText={t('pipeline.priorityHelp')}
                inputProps={{ min: 0 }}
              />

              {/* Target Data Model - Batch: single select, Realtime: multiple with discriminator */}
              {workflow?.type === 'batch' ? (
                <FormControl fullWidth>
                  <InputLabel>{t('pipeline.targetDataModel')}</InputLabel>
                  <Select
                    value={pipelineForm.target_data_type_id}
                    label={t('pipeline.targetDataModel')}
                    onChange={(e) => setPipelineForm({ ...pipelineForm, target_data_type_id: e.target.value })}
                  >
                    <MenuItem value="">{t('pipeline.targetDataModelPlaceholder')}</MenuItem>
                    {dataTypes.map(dt => (
                      <MenuItem key={dt.id} value={dt.id}>
                        {dt.display_name} <Typography component="span" color="text.secondary" sx={{ ml: 1 }}>({dt.name})</Typography>
                      </MenuItem>
                    ))}
                  </Select>
                  <FormHelperText>{t('pipeline.targetDataModelHelp')}</FormHelperText>
                </FormControl>
              ) : (
                <>
                  <TextField
                    label={t('pipeline.discriminatorField')}
                    value={pipelineForm.discriminator_field}
                    onChange={(e) => setPipelineForm({ ...pipelineForm, discriminator_field: e.target.value })}
                    fullWidth
                    placeholder={t('pipeline.discriminatorFieldPlaceholder')}
                    helperText={t('pipeline.discriminatorFieldHelp')}
                  />

                  {/* Target Models list */}
                  <Box>
                    <Typography variant="subtitle2" sx={{ mb: 1 }}>{t('pipeline.targetModels')}</Typography>
                    <Typography variant="caption" color="text.secondary" sx={{ mb: 1, display: 'block' }}>
                      {t('pipeline.targetModelsHelp')}
                    </Typography>
                    {pipelineForm.target_models.map((tm, index) => (
                      <Box key={index} sx={{ display: 'flex', gap: 1, mb: 1, alignItems: 'flex-start' }}>
                        <FormControl sx={{ minWidth: 200 }}>
                          <Select
                            value={tm.model_id}
                            onChange={(e) => updateTargetModel(index, 'model_id', e.target.value)}
                            displayEmpty
                            size="small"
                          >
                            <MenuItem value="">{t('pipeline.targetDataModelPlaceholder')}</MenuItem>
                            {dataTypes.map(dt => (
                              <MenuItem key={dt.id} value={dt.id}>{dt.display_name}</MenuItem>
                            ))}
                          </Select>
                        </FormControl>
                        {pipelineForm.discriminator_field && (
                          <TextField
                            value={tm.discriminator_value}
                            onChange={(e) => updateTargetModel(index, 'discriminator_value', e.target.value)}
                            placeholder={t('pipeline.matchValuePlaceholder')}
                            size="small"
                            sx={{ width: 150 }}
                          />
                        )}
                        {pipelineForm.target_models.length > 1 && (
                          <IconButton size="small" color="error" onClick={() => removeTargetModel(index)}>
                            <RemoveCircleIcon />
                          </IconButton>
                        )}
                      </Box>
                    ))}
                    <Button variant="outlined" size="small" startIcon={<AddIcon />} onClick={addTargetModel}>
                      {t('pipeline.addTargetModel')}
                    </Button>
                  </Box>
                </>
              )}

              <FormControl fullWidth>
                <InputLabel>{t('pipeline.parentPipeline')}</InputLabel>
                <Select
                  value={pipelineForm.parent_pipeline_id}
                  label={t('pipeline.parentPipeline')}
                  onChange={(e) => handleParentPipelineChange(e.target.value || undefined)}
                >
                  <MenuItem value="">{t('pipeline.parentPipelinePlaceholder')}</MenuItem>
                  {pipelines
                    .filter(p => p.id !== editingPipeline?.id)
                    .map(p => {
                      const depth = getPipelineDepth(p)
                      return (
                        <MenuItem key={p.id} value={p.id}>
                          <Box sx={{ pl: depth * 1.5 }}>
                            {depth > 0 && '-- '}
                            {p.name}
                          </Box>
                        </MenuItem>
                      )
                    })}
                </Select>
                <FormHelperText>{t('pipeline.parentPipelineHelp')}</FormHelperText>
              </FormControl>

              {selectedParentPipeline && (
                <>
                  <FormControl fullWidth>
                    <InputLabel>{t('pipeline.expansionMode')}</InputLabel>
                    <Select
                      value={pipelineForm.expansion_mode}
                      label={t('pipeline.expansionMode')}
                      onChange={(e) => setPipelineForm({ ...pipelineForm, expansion_mode: e.target.value as ExpansionMode })}
                    >
                      <MenuItem value="none">
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                          <Chip label={t('pipeline.expansionNone')} size="small" />
                          <Typography variant="body2" color="text.secondary">{t('pipeline.expansionNoneDesc')}</Typography>
                        </Box>
                      </MenuItem>
                      <MenuItem value="for_each_record">
                        <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                          <Chip label={t('pipeline.expansionForEachRecord')} color="secondary" size="small" />
                          <Typography variant="body2" color="text.secondary">{t('pipeline.expansionForEachRecordDesc')}</Typography>
                        </Box>
                      </MenuItem>
                    </Select>
                    <FormHelperText>{t('pipeline.expansionModeHelp')}</FormHelperText>
                  </FormControl>

                  {/* Parameter Bindings */}
                  <Box>
                    <Typography variant="subtitle2" sx={{ mb: 1 }}>{t('pipeline.parameterBindings')}</Typography>
                    <Typography variant="caption" color="text.secondary" sx={{ mb: 1, display: 'block' }}>
                      {t('pipeline.parameterBindingsHelp')}
                    </Typography>
                    {pipelineForm.parameter_bindings.map((pb, index) => (
                      <Box key={index} sx={{ display: 'flex', gap: 1, mb: 1, alignItems: 'center' }}>
                        <TextField
                          value={pb.parent_field}
                          onChange={(e) => updateParameterBinding(index, 'parent_field', e.target.value)}
                          placeholder={t('pipeline.parentFieldPlaceholder')}
                          size="small"
                          sx={{ width: 150 }}
                        />
                        <Typography>-&gt;</Typography>
                        <TextField
                          value={pb.child_param}
                          onChange={(e) => updateParameterBinding(index, 'child_param', e.target.value)}
                          placeholder={t('pipeline.childParamPlaceholder')}
                          size="small"
                          sx={{ width: 150 }}
                        />
                        <Button size="small" color="error" onClick={() => removeParameterBinding(index)}>
                          {t('common.delete')}
                        </Button>
                      </Box>
                    ))}
                    <Button variant="outlined" size="small" startIcon={<AddIcon />} onClick={addParameterBinding}>
                      {t('pipeline.addBinding')}
                    </Button>
                  </Box>
                </>
              )}
            </Box>
          </DialogContent>
          <DialogActions>
            <Button onClick={() => setPipelineModalOpen(false)}>{t('common.cancel')}</Button>
            <Button variant="contained" onClick={handlePipelineSubmit} disabled={saving}>
              {saving ? <CircularProgress size={20} /> : t('common.save')}
            </Button>
          </DialogActions>
        </Dialog>

        {/* Execution Detail Modal */}
        <Dialog open={executionDetailOpen} onClose={() => { setExecutionDetailOpen(false); setExecutionDetail(null) }} maxWidth="md" fullWidth>
          <DialogTitle>{t('workflow.executionDetail')}</DialogTitle>
          <DialogContent>
            {executionDetailLoading ? (
              <Box sx={{ display: 'flex', justifyContent: 'center', py: 5 }}>
                <CircularProgress />
              </Box>
            ) : executionDetail ? (
              <Box>
                {/* Error Alert */}
                {executionDetail.error_message && (
                  <Alert severity="error" icon={<WarningIcon />} sx={{ mb: 2 }}>
                    <Typography variant="subtitle2">{t('workflow.executionError')}</Typography>
                    <Typography variant="body2">{executionDetail.error_message}</Typography>
                  </Alert>
                )}

                {/* Execution Overview */}
                <TableContainer component={Paper} variant="outlined" sx={{ mb: 2 }}>
                  <Table size="small">
                    <TableBody>
                      <TableRow>
                        <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.executionId')}</TableCell>
                        <TableCell><code style={{ fontSize: 11 }}>{executionDetail.id}</code></TableCell>
                        <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('common.status')}</TableCell>
                        <TableCell>
                          {(() => {
                            const execStatusConfig: Record<string, { color: 'success' | 'info' | 'error' | 'default'; icon: React.ReactNode }> = {
                              completed: { color: 'success', icon: <CheckCircleIcon fontSize="small" /> },
                              running: { color: 'info', icon: <SyncIcon fontSize="small" /> },
                              error: { color: 'error', icon: <CloseCircleIcon fontSize="small" /> },
                              stopped: { color: 'default', icon: <StopIcon fontSize="small" /> },
                            }
                            const config = execStatusConfig[executionDetail.status] || { color: 'default' as const, icon: null }
                            return (
                              <Chip
                                icon={config.icon as React.ReactElement}
                                label={t(`pipeline.status.${executionDetail.status}`)}
                                color={config.color}
                                size="small"
                              />
                            )
                          })()}
                        </TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.startedAt')}</TableCell>
                        <TableCell>{new Date(executionDetail.started_at).toLocaleString()}</TableCell>
                        <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.completedAt')}</TableCell>
                        <TableCell>{executionDetail.completed_at ? new Date(executionDetail.completed_at).toLocaleString() : '-'}</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.duration')}</TableCell>
                        <TableCell>
                          {(() => {
                            if (!executionDetail.started_at) return '-'
                            const start = new Date(executionDetail.started_at).getTime()
                            const end = executionDetail.completed_at ? new Date(executionDetail.completed_at).getTime() : Date.now()
                            const duration = Math.round((end - start) / 1000)
                            if (duration < 60) return `${duration}s`
                            if (duration < 3600) return `${Math.floor(duration / 60)}m ${duration % 60}s`
                            return `${Math.floor(duration / 3600)}h ${Math.floor((duration % 3600) / 60)}m`
                          })()}
                        </TableCell>
                        <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.triggeredBy')}</TableCell>
                        <TableCell>{executionDetail.triggered_by || '-'}</TableCell>
                      </TableRow>
                      <TableRow>
                        <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.totalRecords')}</TableCell>
                        <TableCell>{executionDetail.total_records.toLocaleString()}</TableCell>
                        <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('workflow.failedRecords')}</TableCell>
                        <TableCell>
                          {executionDetail.failed_records > 0 ? (
                            <Typography color="error">{executionDetail.failed_records.toLocaleString()}</Typography>
                          ) : executionDetail.failed_records}
                        </TableCell>
                      </TableRow>
                    </TableBody>
                  </Table>
                </TableContainer>

                {/* Pipeline Results */}
                {(executionDetail.pipeline_results?.length ?? 0) > 0 && (
                  <Card variant="outlined" sx={{ mb: 2 }}>
                    <CardHeader title={t('workflow.pipelineResults')} titleTypographyProps={{ variant: 'subtitle1' }} />
                    <CardContent>
                      <TableContainer>
                        <Table size="small">
                          <TableHead>
                            <TableRow>
                              <TableCell>{t('pipeline.name')}</TableCell>
                              <TableCell sx={{ width: 100 }}>{t('common.status')}</TableCell>
                              <TableCell align="right">{t('workflow.recordsRead')}</TableCell>
                              <TableCell align="right">{t('workflow.recordsWritten')}</TableCell>
                              <TableCell align="right">{t('workflow.failedRecords')}</TableCell>
                              <TableCell>{t('workflow.errorMessage')}</TableCell>
                            </TableRow>
                          </TableHead>
                          <TableBody>
                            {executionDetail.pipeline_results?.map((pr) => (
                              <TableRow key={pr.pipeline_id}>
                                <TableCell>{pr.pipeline_name}</TableCell>
                                <TableCell>
                                  <Chip
                                    label={t(`pipeline.status.${pr.status}`)}
                                    color={pr.status === 'completed' ? 'success' : pr.status === 'error' ? 'error' : 'default'}
                                    size="small"
                                  />
                                </TableCell>
                                <TableCell align="right">{pr.records_read?.toLocaleString() || 0}</TableCell>
                                <TableCell align="right">{pr.records_written?.toLocaleString() || 0}</TableCell>
                                <TableCell align="right">
                                  {pr.records_failed > 0 ? (
                                    <Typography color="error">{pr.records_failed}</Typography>
                                  ) : pr.records_failed || 0}
                                </TableCell>
                                <TableCell sx={{ maxWidth: 300 }}>
                                  {pr.error_message ? (
                                    <Typography color="error" sx={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                                      {pr.error_message}
                                    </Typography>
                                  ) : '-'}
                                </TableCell>
                              </TableRow>
                            ))}
                          </TableBody>
                        </Table>
                      </TableContainer>
                    </CardContent>
                  </Card>
                )}

                {/* Pipeline Configuration Snapshot */}
                {(executionDetail.pipelines_snapshot?.length ?? 0) > 0 && (
                  <Card variant="outlined">
                    <CardHeader
                      title={t('workflow.pipelineConfigSnapshot')}
                      subheader={t('workflow.pipelineConfigSnapshotHelp')}
                      titleTypographyProps={{ variant: 'subtitle1' }}
                    />
                    <CardContent>
                      {executionDetail.pipelines_snapshot?.map((pipeline, index) => (
                        <Accordion key={pipeline.id || index} variant="outlined">
                          <AccordionSummary expandIcon={<ExpandMoreIcon />}>
                            <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
                              <Typography>{pipeline.name}</Typography>
                              <Chip label={pipeline.source?.type || 'unknown'} size="small" />
                              {(pipeline.stages?.length ?? 0) > 0 && (
                                <Chip label={`${pipeline.stages?.length ?? 0} ${t('stage.title')}`} color="primary" size="small" />
                              )}
                            </Box>
                          </AccordionSummary>
                          <AccordionDetails>
                            {/* Source Config */}
                            <Typography variant="subtitle2" sx={{ mb: 1 }}>{t('source.title')}</Typography>
                            <TableContainer component={Paper} variant="outlined" sx={{ mb: 2 }}>
                              <Table size="small">
                                <TableBody>
                                  <TableRow>
                                    <TableCell component="th" sx={{ bgcolor: 'grey.50', width: 100 }}>{t('source.type')}</TableCell>
                                    <TableCell><Chip label={pipeline.source?.type} size="small" /></TableCell>
                                  </TableRow>
                                  <TableRow>
                                    <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('source.config')}</TableCell>
                                    <TableCell>
                                      <pre style={{ margin: 0, fontSize: 11, maxHeight: 200, overflow: 'auto', background: '#f5f5f5', padding: 8, borderRadius: 4 }}>
                                        {JSON.stringify(pipeline.source?.config || {}, null, 2)}
                                      </pre>
                                    </TableCell>
                                  </TableRow>
                                  {pipeline.source?.partition && (
                                    <TableRow>
                                      <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('source.partition', 'Partition')}</TableCell>
                                      <TableCell>
                                        <pre style={{ margin: 0, fontSize: 11, maxHeight: 200, overflow: 'auto', background: '#f5f5f5', padding: 8, borderRadius: 4 }}>
                                          {JSON.stringify(pipeline.source.partition, null, 2)}
                                        </pre>
                                      </TableCell>
                                    </TableRow>
                                  )}
                                  {pipeline.source?.pagination && (
                                    <TableRow>
                                      <TableCell component="th" sx={{ bgcolor: 'grey.50' }}>{t('source.pagination', 'Pagination')}</TableCell>
                                      <TableCell>
                                        <pre style={{ margin: 0, fontSize: 11, maxHeight: 200, overflow: 'auto', background: '#f5f5f5', padding: 8, borderRadius: 4 }}>
                                          {JSON.stringify(pipeline.source.pagination, null, 2)}
                                        </pre>
                                      </TableCell>
                                    </TableRow>
                                  )}
                                </TableBody>
                              </Table>
                            </TableContainer>

                            {/* Stages */}
                            {(pipeline.stages?.length ?? 0) > 0 && (
                              <Box>
                                <Typography variant="subtitle2" sx={{ mb: 1 }}>{t('stage.title')}</Typography>
                                <TableContainer component={Paper} variant="outlined">
                                  <Table size="small">
                                    <TableHead>
                                      <TableRow>
                                        <TableCell sx={{ width: 150 }}>{t('stage.name')}</TableCell>
                                        <TableCell sx={{ width: 100 }}>{t('stage.type')}</TableCell>
                                        <TableCell>{t('stage.config')}</TableCell>
                                      </TableRow>
                                    </TableHead>
                                    <TableBody>
                                      {pipeline.stages?.map((stage, idx) => (
                                        <TableRow key={idx}>
                                          <TableCell>{stage.name}</TableCell>
                                          <TableCell><Chip label={stage.type} size="small" /></TableCell>
                                          <TableCell>
                                            <pre style={{ margin: 0, fontSize: 10, maxHeight: 100, overflow: 'auto', background: '#f5f5f5', padding: 4, borderRadius: 4 }}>
                                              {JSON.stringify(stage.config || {}, null, 2)}
                                            </pre>
                                          </TableCell>
                                        </TableRow>
                                      ))}
                                    </TableBody>
                                  </Table>
                                </TableContainer>
                              </Box>
                            )}
                          </AccordionDetails>
                        </Accordion>
                      ))}
                    </CardContent>
                  </Card>
                )}
              </Box>
            ) : (
              <Box sx={{ textAlign: 'center', py: 6 }}>
                <Typography color="text.secondary">{t('workflow.noExecutionDetail')}</Typography>
              </Box>
            )}
          </DialogContent>
          <DialogActions>
            <Button onClick={() => { setExecutionDetailOpen(false); setExecutionDetail(null) }}>
              {t('common.close')}
            </Button>
          </DialogActions>
        </Dialog>

        {/* Delete Pipeline Confirm Dialog */}
        <ConfirmDialog
          open={!!deletePipelineId}
          title={t('pipeline.deleteConfirm')}
          message={t('pipeline.deleteWarning') || ''}
          confirmText={t('common.delete')}
          cancelText={t('common.cancel')}
          onConfirm={handleDeletePipeline}
          onCancel={() => setDeletePipelineId(null)}
          severity="error"
        />

        {/* Delete Checkpoint Confirm Dialog */}
        <ConfirmDialog
          open={!!deleteCheckpointPipelineId}
          title={t('checkpoint.deleteConfirm')}
          message={t('checkpoint.deleteWarning') || ''}
          confirmText={t('common.delete')}
          cancelText={t('common.cancel')}
          onConfirm={handleDeleteCheckpoints}
          onCancel={() => setDeleteCheckpointPipelineId(null)}
          severity="error"
        />

        {/* Pipeline Editor Dialog (GUI/YAML 듀얼 에디터) */}
        <Dialog
          open={pipelineEditorOpen}
          onClose={handlePipelineEditorClose}
          fullScreen
          PaperProps={{ sx: { bgcolor: 'background.default' } }}
        >
          {pipelineToEdit && workflow && (
            <PipelineEditor
              pipeline={pipelineToEdit}
              workflowType={workflow.type}
              onSave={handlePipelineEditorSave}
              onCancel={handlePipelineEditorClose}
            />
          )}
        </Dialog>
      </Box>
    </LocalizationProvider>
  )
}
