import { useEffect, useState } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import {
  Card,
  Descriptions,
  Tag,
  Button,
  Space,
  message,
  Spin,
  Typography,
  Tabs,
  Table,
  Empty,
  Breadcrumb,
  Modal,
  Form,
  Input,
  Select,
  Popconfirm,
  Collapse,
  Alert,
  DatePicker,
  Radio,
} from 'antd'
import {
  ArrowLeftOutlined,
  EditOutlined,
  DeleteOutlined,
  PlusOutlined,
  MinusCircleOutlined,
  PlayCircleOutlined,
  PauseCircleOutlined,
  BranchesOutlined,
  SettingOutlined,
  ApiOutlined,
  HistoryOutlined,
  CheckCircleOutlined,
  CloseCircleOutlined,
  SyncOutlined,
  StopOutlined,
  EyeOutlined,
  ExclamationCircleOutlined,
  DatabaseOutlined,
  ReloadOutlined,
} from '@ant-design/icons'
import { useTranslation } from 'react-i18next'
import { api } from '../services/api'
import type { WorkflowPipeline, RealtimePipelineMode, TargetModelMapping } from '../types/pipeline'
import { createDefaultStages, removeAutoGeneratedStages } from '../utils/defaultStages'

const { Title, Text } = Typography

interface Workflow {
  id: string
  project_id: string
  name: string
  slug: string
  description?: string
  type: 'batch' | 'realtime'
  execution_mode: string
  status: string
  schedule_enabled: boolean
  pipelines_config?: string
  pipelines?: WorkflowPipeline[]
  created_at: string
  updated_at: string
  project?: {
    id: string
    name: string
    alias: string
  }
}

interface DataType {
  id: string
  name: string
  display_name: string
  parent_id?: string | null
}

interface WorkflowExecution {
  id: string
  workflow_id: string
  status: string
  started_at: string
  completed_at?: string
  total_records: number
  failed_records: number
  error_message?: string
  triggered_by?: string
  created_at: string
}

interface PipelineExecutionResult {
  pipeline_id: string
  pipeline_name: string
  status: string
  started_at: string
  completed_at?: string
  records_read: number
  records_written: number
  records_processed: number
  records_failed: number
  error_message?: string
}

interface ExecutionDetail {
  id: string
  workflow_id: string
  status: string
  started_at: string
  completed_at?: string
  duration_ms?: number
  total_records: number
  failed_records: number
  error_message?: string
  triggered_by?: string
  triggered_by_id?: string
  created_at: string
  pipelines_snapshot?: WorkflowPipeline[]
  pipeline_results?: PipelineExecutionResult[]
}

interface SourceCheckpoint {
  id: string
  workflow_id: string
  pipeline_id: string
  pipeline_name: string
  source_type: string
  partition_key: string
  offset_value: string
  offset_type: string
  record_count: number
  metadata?: string
  created_at: string
  updated_at: string
}

export default function WorkflowDetailPage() {
  const { t } = useTranslation()
  const { id, workflowId } = useParams<{ id?: string; workflowId?: string }>()
  const effectiveId = id || workflowId
  const navigate = useNavigate()
  const [workflow, setWorkflow] = useState<Workflow | null>(null)
  const [pipelines, setPipelines] = useState<WorkflowPipeline[]>([])
  const [dataTypes, setDataTypes] = useState<DataType[]>([])
  const [executions, setExecutions] = useState<WorkflowExecution[]>([])
  const [loading, setLoading] = useState(true)

  // Pipeline modal states
  const [pipelineModalVisible, setPipelineModalVisible] = useState(false)
  const [editingPipeline, setEditingPipeline] = useState<WorkflowPipeline | null>(null)
  const [pipelineForm] = Form.useForm()
  const [saving, setSaving] = useState(false)
  const [selectedParentPipeline, setSelectedParentPipeline] = useState<string | undefined>()
  const [actionLoading, setActionLoading] = useState(false)

  // Execution detail modal states
  const [executionDetailVisible, setExecutionDetailVisible] = useState(false)
  const [executionDetail, setExecutionDetail] = useState<ExecutionDetail | null>(null)
  const [executionDetailLoading, setExecutionDetailLoading] = useState(false)

  // Checkpoint states
  const [checkpoints, setCheckpoints] = useState<SourceCheckpoint[]>([])
  const [checkpointsLoading, setCheckpointsLoading] = useState(false)
  const [resetModalVisible, setResetModalVisible] = useState(false)
  const [resetPipelineId, setResetPipelineId] = useState<string | null>(null)
  const [resetForm] = Form.useForm()
  const [resetting, setResetting] = useState(false)

  // Monitoring states
  const [monitoringData, setMonitoringData] = useState<any>(null)
  const [monitoringLoading, setMonitoringLoading] = useState(false)
  const [monitoringInterval, setMonitoringInterval] = useState<ReturnType<typeof setInterval> | null>(null)
  const [runningExecutionId, setRunningExecutionId] = useState<string | null>(null)

  useEffect(() => {
    if (effectiveId) {
      fetchWorkflowData()
    }
  }, [effectiveId])

  // 실행 중인 execution 찾기 및 모니터링 시작
  useEffect(() => {
    const runningExec = executions.find(e => e.status === 'running')
    if (runningExec && runningExec.id !== runningExecutionId) {
      setRunningExecutionId(runningExec.id)
      fetchMonitoringData(runningExec.id)
      // 실시간 업데이트 (5초마다)
      const interval = setInterval(() => {
        fetchMonitoringData(runningExec.id)
      }, 5000)
      setMonitoringInterval(interval)
    } else if (!runningExec && monitoringInterval) {
      // 실행 중인 execution이 없으면 인터벌 정리
      clearInterval(monitoringInterval)
      setMonitoringInterval(null)
      setRunningExecutionId(null)
      setMonitoringData(null)
    }
    return () => {
      if (monitoringInterval) {
        clearInterval(monitoringInterval)
      }
    }
  }, [executions, runningExecutionId])

  const fetchMonitoringData = async (executionId: string) => {
    if (!effectiveId) return
    try {
      setMonitoringLoading(true)
      const res = await api.getWorkflowExecutionMonitoring(effectiveId, executionId)
      if (res.success && res.data) {
        setMonitoringData(res.data)
      }
    } catch (error) {
      // 실행이 종료되었거나 에러가 발생한 경우 조용히 처리
      console.error('Failed to fetch monitoring data:', error)
    } finally {
      setMonitoringLoading(false)
    }
  }

  const fetchWorkflowData = async () => {
    try {
      setLoading(true)
      const workflowRes = await api.getWorkflow(effectiveId!)
      if (workflowRes.success && workflowRes.data) {
        setWorkflow(workflowRes.data)
        // Use pipelines array directly from backend (already parsed)
        if (workflowRes.data.pipelines) {
          setPipelines(workflowRes.data.pipelines)
        } else if (workflowRes.data.pipelines_config) {
          // Fallback: parse from JSON string if pipelines not available
          try {
            const parsed = JSON.parse(workflowRes.data.pipelines_config)
            setPipelines(parsed || [])
          } catch {
            setPipelines([])
          }
        }
        // Fetch project's data types for expansion configuration
        if (workflowRes.data.project_id) {
          const dataTypesRes = await api.getProjectDataTypes(workflowRes.data.project_id)
          if (dataTypesRes.success) {
            setDataTypes(dataTypesRes.data || [])
          }
        }
        // Fetch workflow executions
        const executionsRes = await api.getWorkflowExecutions(effectiveId!)
        if (executionsRes.success) {
          setExecutions(executionsRes.data || [])
        }
      }
    } catch (error) {
      message.error(t('workflow.loadError'))
    } finally {
      setLoading(false)
    }
  }

  const fetchCheckpoints = async () => {
    if (!effectiveId) return
    try {
      setCheckpointsLoading(true)
      const res = await api.getWorkflowCheckpoints(effectiveId)
      if (res.success && res.data) {
        setCheckpoints(res.data.checkpoints || [])
      }
    } catch (error) {
      console.error('Failed to fetch checkpoints:', error)
    } finally {
      setCheckpointsLoading(false)
    }
  }

  const handleResetCheckpoint = (pipelineId: string) => {
    setResetPipelineId(pipelineId)
    resetForm.resetFields()
    resetForm.setFieldsValue({ mode: 'specific_time' })
    setResetModalVisible(true)
  }

  const handleResetSubmit = async () => {
    if (!resetPipelineId) return
    try {
      const values = await resetForm.validateFields()
      setResetting(true)

      const data: {
        mode: 'specific_time' | 'beginning' | 'specific_offset'
        timestamp?: string
        offset_value?: string
      } = { mode: values.mode }

      if (values.mode === 'specific_time' && values.timestamp) {
        data.timestamp = values.timestamp.toISOString()
      } else if (values.mode === 'specific_offset' && values.offset_value) {
        data.offset_value = values.offset_value
      }

      const res = await api.resetPipelineCheckpoints(resetPipelineId, data)
      if (res.success) {
        message.success(t('checkpoint.resetSuccess'))
        setResetModalVisible(false)
        fetchCheckpoints()
      } else {
        message.error(res.error?.message || t('checkpoint.resetError'))
      }
    } catch (error) {
      message.error(t('checkpoint.resetError'))
    } finally {
      setResetting(false)
    }
  }

  const handleDeleteCheckpoints = async (pipelineId: string) => {
    try {
      const res = await api.deletePipelineCheckpoints(pipelineId)
      if (res.success) {
        message.success(t('checkpoint.deleteSuccess'))
        fetchCheckpoints()
      } else {
        message.error(res.error?.message || t('checkpoint.deleteError'))
      }
    } catch (error) {
      message.error(t('checkpoint.deleteError'))
    }
  }

  const handleStartWorkflow = async () => {
    if (!effectiveId) return
    try {
      setActionLoading(true)
      const res = await api.startWorkflow(effectiveId)
      if (res.success) {
        message.success(t('workflow.startSuccess'))
        fetchWorkflowData()
      } else {
        message.error(res.error?.message || t('workflow.startError'))
      }
    } catch (error: unknown) {
      const err = error as { response?: { data?: { error?: { message?: string } } } }
      message.error(err.response?.data?.error?.message || t('workflow.startError'))
    } finally {
      setActionLoading(false)
    }
  }

  const handleStopWorkflow = async () => {
    if (!effectiveId) return
    try {
      setActionLoading(true)
      const res = await api.stopWorkflow(effectiveId)
      if (res.success) {
        message.success(t('workflow.stopSuccess'))
        fetchWorkflowData()
      } else {
        message.error(res.error?.message || t('workflow.stopError'))
      }
    } catch (error: unknown) {
      const err = error as { response?: { data?: { error?: { message?: string } } } }
      message.error(err.response?.data?.error?.message || t('workflow.stopError'))
    } finally {
      setActionLoading(false)
    }
  }

  const handleViewExecutionDetail = async (executionId: string) => {
    if (!effectiveId) return
    try {
      setExecutionDetailLoading(true)
      setExecutionDetailVisible(true)
      const res = await api.getWorkflowExecution(effectiveId, executionId)
      if (res.success && res.data) {
        setExecutionDetail(res.data)
      } else {
        message.error(t('workflow.executionDetailError'))
      }
    } catch (error) {
      message.error(t('workflow.executionDetailError'))
    } finally {
      setExecutionDetailLoading(false)
    }
  }

  const handleCreatePipeline = () => {
    setEditingPipeline(null)
    setSelectedParentPipeline(undefined)
    pipelineForm.resetFields()

    pipelineForm.setFieldsValue({
      priority: pipelines.length,
      expansion_mode: 'none',
      source: { type: 'rest_api', name: '', config: {} },
      // Default to 'cdc' mode for realtime workflows
      realtime_mode: workflow?.type === 'realtime' ? 'cdc' : undefined,
      // Initialize target_models for realtime, empty array
      target_models: workflow?.type === 'realtime' ? [{ model_id: '', discriminator_value: '' }] : undefined,
      discriminator_field: '',
    })
    setPipelineModalVisible(true)
  }

  const handleEditPipeline = (pipeline: WorkflowPipeline) => {
    setEditingPipeline(pipeline)
    setSelectedParentPipeline(pipeline.parent_pipeline_id || undefined)

    // Prepare target_models for realtime pipelines
    const targetModels = pipeline.target_models?.map(tm => ({
      model_id: tm.model_id,
      discriminator_value: tm.discriminator_value || '',
    })) || (pipeline.target_data_type_id ? [{ model_id: pipeline.target_data_type_id, discriminator_value: '' }] : [])

    pipelineForm.setFieldsValue({
      name: pipeline.name,
      description: pipeline.description,
      priority: pipeline.priority,
      parent_pipeline_id: pipeline.parent_pipeline_id || undefined,
      target_data_type_id: pipeline.target_data_type_id || undefined,
      expansion_mode: pipeline.expansion_mode || 'none',
      parameter_bindings: pipeline.parameter_bindings || [],
      realtime_mode: pipeline.realtime_mode || 'cdc',
      target_models: targetModels,
      discriminator_field: pipeline.discriminator_field || '',
    })
    setPipelineModalVisible(true)
  }

  const handleDeletePipeline = async (pipelineId: string) => {
    // Check if pipeline has children
    const hasChildren = pipelines.some(p => p.parent_pipeline_id === pipelineId)
    if (hasChildren) {
      message.error(t('pipeline.cannotDeleteHasChildren'))
      return
    }

    const newPipelines = pipelines.filter(p => p.id !== pipelineId)
    await savePipelines(newPipelines)
  }

  const handlePipelineSubmit = async () => {
    try {
      const values = await pipelineForm.validateFields()
      setSaving(true)

      const workflowType = workflow?.type || 'batch'
      const newRealtimeMode = values.realtime_mode as RealtimePipelineMode | undefined
      const oldRealtimeMode = editingPipeline?.realtime_mode

      // Determine stages based on workflow type and mode
      let stages = editingPipeline?.stages || []

      if (!editingPipeline) {
        // New pipeline: generate default stages based on type/mode
        stages = createDefaultStages(workflowType, newRealtimeMode)
      } else if (workflowType === 'realtime' && oldRealtimeMode !== newRealtimeMode) {
        // Realtime mode changed: regenerate default stages
        // Remove old auto-generated stages, add new ones
        const userStages = removeAutoGeneratedStages(stages)
        const newDefaultStages = createDefaultStages(workflowType, newRealtimeMode)
        stages = [...newDefaultStages, ...userStages]
      }

      // Build target models for realtime, target_data_type_id for batch
      let targetModels: TargetModelMapping[] | undefined
      let discriminatorField: string | undefined
      let targetDataTypeId: string | null = null

      if (workflowType === 'realtime') {
        // Realtime: use target_models
        targetModels = values.target_models?.map((tm: { model_id: string; discriminator_value?: string }) => ({
          model_id: tm.model_id,
          discriminator_value: tm.discriminator_value || undefined,
        })) || []
        discriminatorField = values.discriminator_field || undefined
      } else {
        // Batch: use target_data_type_id
        targetDataTypeId = values.target_data_type_id || null
      }

      const pipelineData: WorkflowPipeline = {
        id: editingPipeline?.id || crypto.randomUUID(),
        name: values.name,
        description: values.description,
        priority: values.priority,
        source: editingPipeline?.source || { type: 'rest_api', name: values.name, config: {} },
        parent_pipeline_id: values.parent_pipeline_id || null,
        target_data_type_id: targetDataTypeId,
        expansion_mode: values.expansion_mode || 'none',
        parameter_bindings: values.parameter_bindings || [],
        stages,
        realtime_mode: workflowType === 'realtime' ? newRealtimeMode : undefined,
        target_models: targetModels,
        discriminator_field: discriminatorField,
      }

      let newPipelines: WorkflowPipeline[]
      if (editingPipeline) {
        newPipelines = pipelines.map(p => p.id === editingPipeline.id ? pipelineData : p)
      } else {
        newPipelines = [...pipelines, pipelineData]
      }

      await savePipelines(newPipelines)
      setPipelineModalVisible(false)
    } catch (error) {
      message.error(t('common.saveError'))
    } finally {
      setSaving(false)
    }
  }

  const savePipelines = async (newPipelines: WorkflowPipeline[]) => {
    try {
      const response = await api.updateWorkflow(effectiveId!, {
        pipelines: newPipelines,
      })
      if (response.success) {
        setPipelines(newPipelines)
        message.success(t('common.saveSuccess'))
      } else {
        message.error(response.error || t('common.saveError'))
      }
    } catch (error) {
      message.error(t('common.saveError'))
    }
  }

  const handleParentPipelineChange = (parentId: string | undefined) => {
    setSelectedParentPipeline(parentId)
    if (parentId) {
      // Find parent pipeline's target DataType
      const parentPipeline = pipelines.find(p => p.id === parentId)
      if (parentPipeline?.target_data_type_id) {
        pipelineForm.setFieldsValue({
          target_data_type_id: parentPipeline.target_data_type_id,
          expansion_mode: 'for_each_record',
        })
      }
    } else {
      pipelineForm.setFieldsValue({
        expansion_mode: 'none',
        parameter_bindings: [],
      })
    }
  }

  const getStatusConfig = (status: string) => {
    const configs: Record<string, { color: string; text: string }> = {
      idle: { color: 'default', text: t('pipeline.status.idle') },
      running: { color: 'green', text: t('pipeline.status.running') },
      paused: { color: 'orange', text: t('pipeline.status.paused') },
      stopped: { color: 'default', text: t('pipeline.status.stopped') },
      error: { color: 'red', text: t('pipeline.status.error') },
      completed: { color: 'blue', text: t('pipeline.status.completed') },
    }
    return configs[status] || { color: 'default', text: status }
  }

  // Pipeline depth calculation
  const getPipelineDepth = (pipeline: WorkflowPipeline): number => {
    let depth = 0
    let currentParentId = pipeline.parent_pipeline_id
    while (currentParentId) {
      depth++
      const parent = pipelines.find(p => p.id === currentParentId)
      currentParentId = parent?.parent_pipeline_id || null
    }
    return depth
  }

  // Sort pipelines hierarchically
  const getHierarchicalPipelines = (): WorkflowPipeline[] => {
    const result: WorkflowPipeline[] = []
    const addWithChildren = (parentId: string | null) => {
      const children = pipelines
        .filter(p => (p.parent_pipeline_id || null) === parentId)
        .sort((a, b) => a.priority - b.priority)
      for (const child of children) {
        result.push(child)
        addWithChildren(child.id)
      }
    }
    addWithChildren(null)
    return result
  }

  const hierarchicalPipelines = getHierarchicalPipelines()

  const pipelineColumns = [
    {
      title: t('pipeline.name'),
      dataIndex: 'name',
      key: 'name',
      render: (name: string, record: WorkflowPipeline) => {
        const depth = getPipelineDepth(record)
        const targetDataType = dataTypes.find(dt => dt.id === record.target_data_type_id)
        return (
          <div style={{ paddingLeft: depth * 24 }}>
            <Space size={4}>
              {depth > 0 && (
                <span style={{ color: '#999', fontSize: 12 }}>└─</span>
              )}
              <span>{name}</span>
              {record.expansion_mode === 'for_each_record' && (
                <Tag color="purple" icon={<BranchesOutlined />}>
                  {t('pipeline.expansion')}
                </Tag>
              )}
            </Space>
            {targetDataType && (
              <div style={{ fontSize: 12, color: '#999', paddingLeft: depth > 0 ? 20 : 0 }}>
                {t('pipeline.targetDataModel')}: <code>{targetDataType.display_name}</code>
              </div>
            )}
          </div>
        )
      },
    },
    {
      title: t('pipeline.source'),
      dataIndex: ['source', 'type'],
      key: 'source',
      width: 120,
      render: (type: string) => <Tag>{type}</Tag>,
    },
    {
      title: t('pipeline.output'),
      key: 'outputStages',
      width: 120,
      render: (_: unknown, record: WorkflowPipeline) => {
        // 출력 타입 stage들만 필터링
        const outputTypes = ['sql', 'elasticsearch', 'kafka', 'mongodb', 's3', 'rest_api', 'file']
        const outputStages = record.stages?.filter(s => outputTypes.includes(s.type)) || []
        return (
          <Space>
            {outputStages.slice(0, 2).map((stage, i) => (
              <Tag key={i}>{stage.type}</Tag>
            ))}
            {outputStages.length > 2 && <Tag>+{outputStages.length - 2}</Tag>}
            {outputStages.length === 0 && <Tag color="default">-</Tag>}
          </Space>
        )
      },
    },
    {
      title: t('pipeline.priority'),
      dataIndex: 'priority',
      key: 'priority',
      width: 80,
      render: (priority: number) => priority,
    },
    {
      title: t('common.actions'),
      key: 'actions',
      width: 200,
      render: (_: unknown, record: WorkflowPipeline) => {
        const hasChildren = pipelines.some(p => p.parent_pipeline_id === record.id)
        return (
          <Space>
            <Button
              size="small"
              icon={<ApiOutlined />}
              onClick={() => navigate(`/projects/${workflow?.project?.alias}/workflows/${effectiveId}/pipelines/${record.id}/source`)}
              title={t('source.editSource')}
            />
            <Button
              size="small"
              icon={<SettingOutlined />}
              onClick={() => navigate(`/projects/${workflow?.project?.alias}/workflows/${effectiveId}/pipelines/${record.id}/stages`)}
              title={t('stage.editStages')}
            />
            <Button
              size="small"
              icon={<EditOutlined />}
              onClick={() => handleEditPipeline(record)}
            />
            {!hasChildren && (
              <Popconfirm
                title={t('pipeline.deleteConfirm')}
                onConfirm={() => handleDeletePipeline(record.id)}
                okText={t('common.delete')}
                cancelText={t('common.cancel')}
              >
                <Button size="small" danger icon={<DeleteOutlined />} />
              </Popconfirm>
            )}
          </Space>
        )
      },
    },
  ]

  if (loading) {
    return (
      <div style={{ display: 'flex', justifyContent: 'center', alignItems: 'center', height: 400 }}>
        <Spin size="large" />
      </div>
    )
  }

  if (!workflow) {
    return (
      <Empty description={t('workflow.notFound')}>
        <Button type="primary" onClick={() => navigate(-1)}>
          {t('common.back')}
        </Button>
      </Empty>
    )
  }

  const statusConfig = getStatusConfig(workflow.status)

  return (
    <div>
      <Breadcrumb
        style={{ marginBottom: 16 }}
        items={[
          { title: <a onClick={() => navigate('/projects')}>{t('project.title')}</a> },
          ...(workflow.project ? [
            { title: <a onClick={() => navigate(`/projects/${workflow.project_id}`)}>{workflow.project.name}</a> },
          ] : []),
          { title: workflow.name },
        ]}
      />

      <div style={{ marginBottom: 16, display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <Space>
          <Button icon={<ArrowLeftOutlined />} onClick={() => navigate(-1)}>
            {t('common.back')}
          </Button>
          <Title level={4} style={{ margin: 0 }}>
            {workflow.name}
          </Title>
          <Tag color={workflow.type === 'realtime' ? 'blue' : 'purple'}>
            {workflow.type === 'realtime' ? t('workflow.realtime') : t('workflow.batch')}
          </Tag>
          <Tag color={statusConfig.color}>{statusConfig.text}</Tag>
        </Space>
        <Space>
          {workflow.status === 'running' ? (
            <Button
              icon={<PauseCircleOutlined />}
              onClick={handleStopWorkflow}
              loading={actionLoading}
            >
              {t('workflow.stop')}
            </Button>
          ) : (
            <Button
              type="primary"
              icon={<PlayCircleOutlined />}
              onClick={handleStartWorkflow}
              loading={actionLoading}
            >
              {t('workflow.start')}
            </Button>
          )}
        </Space>
      </div>

      <Tabs
        defaultActiveKey="pipelines"
        items={[
          {
            key: 'overview',
            label: t('project.overview'),
            children: (
              <Card>
                <Descriptions bordered column={2}>
                  <Descriptions.Item label={t('workflow.name')}>
                    {workflow.name}
                  </Descriptions.Item>
                  <Descriptions.Item label={t('workflow.slug')}>
                    <code>{workflow.slug}</code>
                  </Descriptions.Item>
                  <Descriptions.Item label={t('workflow.type')}>
                    <Tag color={workflow.type === 'realtime' ? 'blue' : 'purple'}>
                      {workflow.type === 'realtime' ? t('workflow.realtime') : t('workflow.batch')}
                    </Tag>
                  </Descriptions.Item>
                  <Descriptions.Item label={t('workflow.executionMode')}>
                    <Tag>{workflow.execution_mode}</Tag>
                  </Descriptions.Item>
                  <Descriptions.Item label={t('common.status')}>
                    <Tag color={statusConfig.color}>{statusConfig.text}</Tag>
                  </Descriptions.Item>
                  <Descriptions.Item label={t('workflow.enabled')}>
                    <Tag color={workflow.schedule_enabled ? 'green' : 'default'}>
                      {workflow.schedule_enabled ? t('workflow.on') : t('workflow.off')}
                    </Tag>
                  </Descriptions.Item>
                  <Descriptions.Item label={t('common.description')} span={2}>
                    {workflow.description || '-'}
                  </Descriptions.Item>
                  <Descriptions.Item label={t('common.createdAt')}>
                    {new Date(workflow.created_at).toLocaleString()}
                  </Descriptions.Item>
                  <Descriptions.Item label={t('common.updatedAt')}>
                    {new Date(workflow.updated_at).toLocaleString()}
                  </Descriptions.Item>
                </Descriptions>
              </Card>
            ),
          },
          {
            key: 'pipelines',
            label: (
              <span>
                <BranchesOutlined />
                {t('pipeline.title')} ({pipelines.length})
              </span>
            ),
            children: (
              <Card
                title={t('pipeline.title')}
                extra={
                  <Button type="primary" icon={<PlusOutlined />} onClick={handleCreatePipeline}>
                    {t('pipeline.new')}
                  </Button>
                }
              >
                <Text type="secondary" style={{ display: 'block', marginBottom: 16 }}>
                  {t('pipeline.hierarchyHelp')}
                </Text>
                {pipelines.length > 0 ? (
                  <Table
                    dataSource={hierarchicalPipelines}
                    columns={pipelineColumns}
                    rowKey="id"
                    pagination={false}
                  />
                ) : (
                  <Empty description={t('pipeline.noPipelines')}>
                    <Button type="primary" onClick={handleCreatePipeline}>
                      {t('pipeline.new')}
                    </Button>
                  </Empty>
                )}
              </Card>
            ),
          },
          {
            key: 'executions',
            label: (
              <span>
                <HistoryOutlined />
                {t('workflow.executions')} ({executions.length})
              </span>
            ),
            children: (
              <Card title={t('workflow.executionHistory')}>
                {executions.length > 0 ? (
                  <Table
                    dataSource={executions}
                    rowKey="id"
                    pagination={{ pageSize: 10 }}
                    columns={[
                      {
                        title: t('common.status'),
                        dataIndex: 'status',
                        key: 'status',
                        width: 120,
                        render: (status: string) => {
                          const statusConfig: Record<string, { color: string; icon: React.ReactNode; text: string }> = {
                            completed: { color: 'success', icon: <CheckCircleOutlined />, text: t('pipeline.status.completed') },
                            running: { color: 'processing', icon: <SyncOutlined spin />, text: t('pipeline.status.running') },
                            error: { color: 'error', icon: <CloseCircleOutlined />, text: t('pipeline.status.error') },
                            stopped: { color: 'default', icon: <StopOutlined />, text: t('pipeline.status.stopped') },
                          }
                          const config = statusConfig[status] || { color: 'default', icon: null, text: status }
                          return <Tag icon={config.icon} color={config.color}>{config.text}</Tag>
                        },
                      },
                      {
                        title: t('workflow.startedAt'),
                        dataIndex: 'started_at',
                        key: 'started_at',
                        render: (date: string) => date ? new Date(date).toLocaleString() : '-',
                      },
                      {
                        title: t('workflow.completedAt'),
                        dataIndex: 'completed_at',
                        key: 'completed_at',
                        render: (date: string) => date ? new Date(date).toLocaleString() : '-',
                      },
                      {
                        title: t('workflow.duration'),
                        key: 'duration',
                        render: (_: unknown, record: WorkflowExecution) => {
                          if (!record.started_at) return '-'
                          const start = new Date(record.started_at).getTime()
                          const end = record.completed_at ? new Date(record.completed_at).getTime() : Date.now()
                          const duration = Math.round((end - start) / 1000)
                          if (duration < 60) return `${duration}s`
                          if (duration < 3600) return `${Math.floor(duration / 60)}m ${duration % 60}s`
                          return `${Math.floor(duration / 3600)}h ${Math.floor((duration % 3600) / 60)}m`
                        },
                      },
                      {
                        title: t('workflow.totalRecords'),
                        dataIndex: 'total_records',
                        key: 'total_records',
                        align: 'right' as const,
                      },
                      {
                        title: t('workflow.failedRecords'),
                        dataIndex: 'failed_records',
                        key: 'failed_records',
                        align: 'right' as const,
                        render: (count: number) => count > 0 ? <Text type="danger">{count}</Text> : count,
                      },
                      {
                        title: t('workflow.errorMessage'),
                        dataIndex: 'error_message',
                        key: 'error_message',
                        ellipsis: true,
                        render: (msg: string) => msg ? (
                          <Text type="danger" ellipsis={{ tooltip: msg }}>{msg}</Text>
                        ) : '-',
                      },
                      {
                        title: t('common.actions'),
                        key: 'actions',
                        width: 80,
                        render: (_: unknown, record: WorkflowExecution) => (
                          <Button
                            size="small"
                            icon={<EyeOutlined />}
                            onClick={() => handleViewExecutionDetail(record.id)}
                            title={t('workflow.viewExecutionDetail')}
                          />
                        ),
                      },
                    ]}
                  />
                ) : (
                  <Empty description={t('workflow.noExecutions')} />
                )}
              </Card>
            ),
          },
          // Monitoring tab - only for running executions
          ...(runningExecutionId ? [{
            key: 'monitoring',
            label: (
              <span>
                <SyncOutlined spin={monitoringLoading} />
                {t('workflow.monitoring')} {monitoringLoading && <Spin size="small" style={{ marginLeft: 8 }} />}
              </span>
            ),
            children: (
              <Card
                title={t('workflow.monitoring')}
                extra={
                  <Button
                    icon={<ReloadOutlined />}
                    onClick={() => runningExecutionId && fetchMonitoringData(runningExecutionId)}
                    loading={monitoringLoading}
                  >
                    {t('common.refresh')}
                  </Button>
                }
              >
                {monitoringLoading && !monitoringData ? (
                  <div style={{ textAlign: 'center', padding: 40 }}>
                    <Spin size="large" />
                  </div>
                ) : monitoringData?.data ? (
                  <div>
                    {monitoringData.data.pipelines?.map((pipeline: any) => (
                      <Card
                        key={pipeline.pipeline_id}
                        title={
                          <Space>
                            <span>{pipeline.pipeline_name || pipeline.pipeline_id}</span>
                            <Tag color={pipeline.status === 'running' ? 'green' : 'default'}>
                              {pipeline.status}
                            </Tag>
                          </Space>
                        }
                        style={{ marginBottom: 16 }}
                        size="small"
                      >
                        {/* Source Checkpoints */}
                        {pipeline.checkpoints && pipeline.checkpoints.length > 0 && (
                          <div style={{ marginBottom: 16 }}>
                            <Title level={5}>
                              <DatabaseOutlined /> {t('checkpoint.sourceCheckpoints')}
                            </Title>
                            <Table
                              dataSource={pipeline.checkpoints}
                              rowKey="partition_key"
                              size="small"
                              pagination={false}
                              columns={[
                                {
                                  title: t('checkpoint.partition'),
                                  dataIndex: 'partition_key',
                                  key: 'partition_key',
                                  render: (key: string) => <code style={{ fontSize: 11 }}>{key}</code>,
                                },
                                {
                                  title: t('checkpoint.offset'),
                                  dataIndex: 'offset_value',
                                  key: 'offset_value',
                                  render: (value: string, record: any) => (
                                    <Space>
                                      <code style={{ fontSize: 11 }}>{value}</code>
                                      <Tag>{record.offset_type}</Tag>
                                    </Space>
                                  ),
                                },
                                {
                                  title: t('checkpoint.recordCount'),
                                  dataIndex: 'record_count',
                                  key: 'record_count',
                                  align: 'right' as const,
                                  render: (count: number) => count?.toLocaleString() || 0,
                                },
                              ]}
                            />
                          </div>
                        )}

                        {/* Stages with Data Samples */}
                        {pipeline.stages && pipeline.stages.length > 0 && (
                          <div>
                            <Title level={5}>{t('stage.title')}</Title>
                            <Collapse>
                              {pipeline.stages.map((stage: any) => (
                                <Collapse.Panel
                                  key={stage.name}
                                  header={
                                    <Space>
                                      <span>{stage.name}</span>
                                      <Tag>{stage.type}</Tag>
                                      <Tag color="blue">입력: {stage.input_count?.toLocaleString() || 0}</Tag>
                                      <Tag color="green">출력: {stage.output_count?.toLocaleString() || 0}</Tag>
                                      {stage.error_count > 0 && (
                                        <Tag color="red">에러: {stage.error_count}</Tag>
                                      )}
                                    </Space>
                                  }
                                >
                                  {/* Stage Statistics */}
                                  <Descriptions bordered column={3} size="small" style={{ marginBottom: 16 }}>
                                    <Descriptions.Item label={t('stage.inputCount')}>
                                      {stage.input_count?.toLocaleString() || 0}
                                    </Descriptions.Item>
                                    <Descriptions.Item label={t('stage.outputCount')}>
                                      {stage.output_count?.toLocaleString() || 0}
                                    </Descriptions.Item>
                                    <Descriptions.Item label={t('stage.errorCount')}>
                                      {stage.error_count > 0 ? (
                                        <Text type="danger">{stage.error_count}</Text>
                                      ) : (
                                        stage.error_count || 0
                                      )}
                                    </Descriptions.Item>
                                  </Descriptions>

                                  {/* Recent Data Samples */}
                                  {stage.samples && stage.samples.length > 0 && (
                                    <div>
                                      <Title level={5}>{t('workflow.recentDataSamples')}</Title>
                                      <Table
                                        dataSource={stage.samples}
                                        rowKey={(_, index) => `${stage.name}-${index}`}
                                        size="small"
                                        pagination={{ pageSize: 5 }}
                                        columns={[
                                          {
                                            title: t('workflow.timestamp'),
                                            dataIndex: 'timestamp',
                                            key: 'timestamp',
                                            width: 180,
                                            render: (ts: number) => new Date(ts).toLocaleString(),
                                          },
                                          {
                                            title: t('workflow.data'),
                                            dataIndex: 'data',
                                            key: 'data',
                                            render: (data: any) => (
                                              <pre
                                                style={{
                                                  margin: 0,
                                                  fontSize: 11,
                                                  maxHeight: 200,
                                                  overflow: 'auto',
                                                  background: '#f5f5f5',
                                                  padding: 8,
                                                  borderRadius: 4,
                                                  whiteSpace: 'pre-wrap',
                                                  wordBreak: 'break-word',
                                                }}
                                              >
                                                {JSON.stringify(data, null, 2)}
                                              </pre>
                                            ),
                                          },
                                        ]}
                                      />
                                    </div>
                                  )}
                                </Collapse.Panel>
                              ))}
                            </Collapse>
                          </div>
                        )}

                        {/* Pipeline Statistics */}
                        {pipeline.statistics && (
                          <div style={{ marginTop: 16 }}>
                            <Title level={5}>{t('workflow.statistics')}</Title>
                            <Descriptions bordered column={2} size="small">
                              <Descriptions.Item label={t('workflow.recordsCollected')}>
                                {pipeline.statistics.records_collected?.toLocaleString() || 0}
                              </Descriptions.Item>
                              <Descriptions.Item label={t('workflow.recordsProcessed')}>
                                {pipeline.statistics.records_processed?.toLocaleString() || 0}
                              </Descriptions.Item>
                              <Descriptions.Item label={t('workflow.collectionErrors')}>
                                {pipeline.statistics.collection_errors > 0 ? (
                                  <Text type="danger">{pipeline.statistics.collection_errors}</Text>
                                ) : (
                                  pipeline.statistics.collection_errors || 0
                                )}
                              </Descriptions.Item>
                              <Descriptions.Item label={t('workflow.processingErrors')}>
                                {pipeline.statistics.processing_errors > 0 ? (
                                  <Text type="danger">{pipeline.statistics.processing_errors}</Text>
                                ) : (
                                  pipeline.statistics.processing_errors || 0
                                )}
                              </Descriptions.Item>
                            </Descriptions>
                          </div>
                        )}
                      </Card>
                    ))}
                    {(!monitoringData.data.pipelines || monitoringData.data.pipelines.length === 0) && (
                      <Empty description={t('workflow.noMonitoringData')} />
                    )}
                  </div>
                ) : (
                  <Empty description={t('workflow.noMonitoringData')} />
                )}
              </Card>
            ),
          }] : []),
          // Checkpoints tab - only for realtime workflows
          ...(workflow?.type === 'realtime' ? [{
            key: 'checkpoints',
            label: (
              <span>
                <DatabaseOutlined />
                {t('checkpoint.title')}
              </span>
            ),
            children: (
              <Card
                title={t('checkpoint.title')}
                extra={
                  <Button
                    icon={<ReloadOutlined />}
                    onClick={fetchCheckpoints}
                    loading={checkpointsLoading}
                  >
                    {t('common.refresh')}
                  </Button>
                }
              >
                <Alert
                  type="info"
                  message={t('checkpoint.description')}
                  style={{ marginBottom: 16 }}
                  showIcon
                />
                {checkpointsLoading ? (
                  <div style={{ textAlign: 'center', padding: 40 }}>
                    <Spin />
                  </div>
                ) : checkpoints.length > 0 ? (
                  <>
                    {/* Group by pipeline */}
                    {Object.entries(
                      checkpoints.reduce((acc, cp) => {
                        const key = cp.pipeline_name || cp.pipeline_id
                        if (!acc[key]) acc[key] = { pipeline_id: cp.pipeline_id, pipeline_name: cp.pipeline_name, items: [] }
                        acc[key].items.push(cp)
                        return acc
                      }, {} as Record<string, { pipeline_id: string; pipeline_name: string; items: SourceCheckpoint[] }>)
                    ).map(([key, group]) => (
                      <Card
                        key={key}
                        size="small"
                        title={
                          <Space>
                            <span>{group.pipeline_name || group.pipeline_id}</span>
                            <Tag>{group.items[0]?.source_type}</Tag>
                            <Tag color="blue">{group.items.length} {t('checkpoint.partitions')}</Tag>
                          </Space>
                        }
                        extra={
                          <Space>
                            <Button
                              size="small"
                              onClick={() => handleResetCheckpoint(group.pipeline_id)}
                            >
                              {t('checkpoint.reset')}
                            </Button>
                            <Popconfirm
                              title={t('checkpoint.deleteConfirm')}
                              onConfirm={() => handleDeleteCheckpoints(group.pipeline_id)}
                              okText={t('common.delete')}
                              cancelText={t('common.cancel')}
                            >
                              <Button size="small" danger>
                                {t('common.delete')}
                              </Button>
                            </Popconfirm>
                          </Space>
                        }
                        style={{ marginBottom: 16 }}
                      >
                        <Table
                          dataSource={group.items}
                          rowKey="id"
                          size="small"
                          pagination={false}
                          columns={[
                            {
                              title: t('checkpoint.partition'),
                              dataIndex: 'partition_key',
                              key: 'partition_key',
                              render: (key: string) => <code style={{ fontSize: 11 }}>{key}</code>,
                            },
                            {
                              title: t('checkpoint.offset'),
                              dataIndex: 'offset_value',
                              key: 'offset_value',
                              render: (value: string, record: SourceCheckpoint) => (
                                <Space>
                                  <code style={{ fontSize: 11 }}>{value}</code>
                                  <Tag>{record.offset_type}</Tag>
                                </Space>
                              ),
                            },
                            {
                              title: t('checkpoint.recordCount'),
                              dataIndex: 'record_count',
                              key: 'record_count',
                              align: 'right' as const,
                              render: (count: number) => count?.toLocaleString() || 0,
                            },
                            {
                              title: t('common.updatedAt'),
                              dataIndex: 'updated_at',
                              key: 'updated_at',
                              render: (date: string) => new Date(date).toLocaleString(),
                            },
                          ]}
                        />
                      </Card>
                    ))}
                  </>
                ) : (
                  <Empty description={t('checkpoint.noCheckpoints')}>
                    <Text type="secondary">{t('checkpoint.noCheckpointsHelp')}</Text>
                  </Empty>
                )}
              </Card>
            ),
          }] : []),
        ]}
      />

      {/* Checkpoint Reset Modal */}
      <Modal
        title={t('checkpoint.resetTitle')}
        open={resetModalVisible}
        onOk={handleResetSubmit}
        onCancel={() => setResetModalVisible(false)}
        okText={t('checkpoint.reset')}
        cancelText={t('common.cancel')}
        confirmLoading={resetting}
      >
        <Alert
          type="warning"
          message={t('checkpoint.resetWarning')}
          style={{ marginBottom: 16 }}
          showIcon
        />
        <Form form={resetForm} layout="vertical">
          <Form.Item
            name="mode"
            label={t('checkpoint.resetMode')}
            rules={[{ required: true }]}
          >
            <Radio.Group>
              <Space direction="vertical">
                <Radio value="specific_time">
                  {t('checkpoint.resetModeSpecificTime')}
                </Radio>
                <Radio value="beginning">
                  {t('checkpoint.resetModeBeginning')}
                </Radio>
                <Radio value="specific_offset">
                  {t('checkpoint.resetModeSpecificOffset')}
                </Radio>
              </Space>
            </Radio.Group>
          </Form.Item>

          <Form.Item
            noStyle
            shouldUpdate={(prevValues, currentValues) => prevValues.mode !== currentValues.mode}
          >
            {({ getFieldValue }) => {
              const mode = getFieldValue('mode')
              if (mode === 'specific_time') {
                return (
                  <Form.Item
                    name="timestamp"
                    label={t('checkpoint.resetTimestamp')}
                    rules={[{ required: true, message: t('checkpoint.resetTimestampRequired') }]}
                  >
                    <DatePicker
                      showTime
                      style={{ width: '100%' }}
                      placeholder={t('checkpoint.resetTimestampPlaceholder')}
                    />
                  </Form.Item>
                )
              }
              if (mode === 'specific_offset') {
                return (
                  <Form.Item
                    name="offset_value"
                    label={t('checkpoint.resetOffsetValue')}
                    rules={[{ required: true, message: t('checkpoint.resetOffsetRequired') }]}
                  >
                    <Input placeholder={t('checkpoint.resetOffsetPlaceholder')} />
                  </Form.Item>
                )
              }
              return null
            }}
          </Form.Item>
        </Form>
      </Modal>

      {/* Pipeline Create/Edit Modal */}
      <Modal
        title={editingPipeline ? t('pipeline.edit') : t('pipeline.new')}
        open={pipelineModalVisible}
        onOk={handlePipelineSubmit}
        onCancel={() => setPipelineModalVisible(false)}
        okText={t('common.save')}
        cancelText={t('common.cancel')}
        confirmLoading={saving}
        width={600}
      >
        <Form form={pipelineForm} layout="vertical">
          <Form.Item
            name="name"
            label={t('pipeline.name')}
            rules={[{ required: true, message: t('pipeline.nameRequired') }]}
          >
            <Input placeholder={t('pipeline.namePlaceholder')} />
          </Form.Item>

          <Form.Item name="description" label={t('common.description')}>
            <Input.TextArea rows={2} />
          </Form.Item>

          {/* Source mode selector - only for realtime workflows */}
          {workflow?.type === 'realtime' && (
            <Form.Item
              name="realtime_mode"
              label={t('pipeline.sourceMode')}
              extra={t('pipeline.sourceModeHelp')}
            >
              <Select>
                <Select.Option value="cdc">
                  <Tag color="blue">CDC</Tag>
                  <span style={{ marginLeft: 8, color: '#666' }}>{t('pipeline.sourceModeCdc')}</span>
                </Select.Option>
                <Select.Option value="raw">
                  <Tag>RAW</Tag>
                  <span style={{ marginLeft: 8, color: '#666' }}>{t('pipeline.sourceModeRaw')}</span>
                </Select.Option>
              </Select>
            </Form.Item>
          )}

          <Form.Item
            name="priority"
            label={t('pipeline.priority')}
            extra={t('pipeline.priorityHelp')}
          >
            <Input type="number" min={0} />
          </Form.Item>

          {/* Target Data Model - Batch: single select, Realtime: multiple with discriminator */}
          {workflow?.type === 'batch' ? (
            <Form.Item
              name="target_data_type_id"
              label={t('pipeline.targetDataModel')}
              extra={t('pipeline.targetDataModelHelp')}
              rules={[{ required: true, message: t('pipeline.targetDataModelRequired') }]}
            >
              <Select placeholder={t('pipeline.targetDataModelPlaceholder')}>
                {dataTypes.map(dt => (
                  <Select.Option key={dt.id} value={dt.id}>
                    {dt.display_name}
                    <span style={{ marginLeft: 8, color: '#999' }}>({dt.name})</span>
                  </Select.Option>
                ))}
              </Select>
            </Form.Item>
          ) : (
            <>
              {/* Discriminator field - shown when multiple models or routing needed */}
              <Form.Item
                name="discriminator_field"
                label={t('pipeline.discriminatorField')}
                extra={t('pipeline.discriminatorFieldHelp')}
              >
                <Input placeholder={t('pipeline.discriminatorFieldPlaceholder')} />
              </Form.Item>

              {/* Target Models list */}
              <Form.List name="target_models">
                {(fields, { add, remove }) => (
                  <Form.Item
                    label={t('pipeline.targetModels')}
                    extra={t('pipeline.targetModelsHelp')}
                    required
                  >
                    {fields.map((field) => (
                      <Space key={field.key} style={{ display: 'flex', marginBottom: 8 }} align="start">
                        <Form.Item
                          {...field}
                          name={[field.name, 'model_id']}
                          rules={[{ required: true, message: t('pipeline.targetDataModelRequired') }]}
                          style={{ marginBottom: 0, width: 200 }}
                        >
                          <Select placeholder={t('pipeline.targetDataModelPlaceholder')}>
                            {dataTypes.map(dt => (
                              <Select.Option key={dt.id} value={dt.id}>
                                {dt.display_name}
                              </Select.Option>
                            ))}
                          </Select>
                        </Form.Item>
                        <Form.Item
                          noStyle
                          shouldUpdate={(prevValues, currentValues) =>
                            prevValues.discriminator_field !== currentValues.discriminator_field
                          }
                        >
                          {({ getFieldValue }) => {
                            const discriminatorField = getFieldValue('discriminator_field')
                            return discriminatorField ? (
                              <Form.Item
                                {...field}
                                name={[field.name, 'discriminator_value']}
                                rules={[{ required: true, message: t('pipeline.matchValueRequired') }]}
                                style={{ marginBottom: 0, width: 150 }}
                              >
                                <Input placeholder={t('pipeline.matchValuePlaceholder')} />
                              </Form.Item>
                            ) : null
                          }}
                        </Form.Item>
                        {fields.length > 1 && (
                          <Button
                            type="text"
                            danger
                            icon={<MinusCircleOutlined />}
                            onClick={() => remove(field.name)}
                          />
                        )}
                      </Space>
                    ))}
                    <Button
                      type="dashed"
                      onClick={() => add({ model_id: '', discriminator_value: '' })}
                      block
                      icon={<PlusOutlined />}
                    >
                      {t('pipeline.addTargetModel')}
                    </Button>
                  </Form.Item>
                )}
              </Form.List>
            </>
          )}

          <Form.Item
            name="parent_pipeline_id"
            label={t('pipeline.parentPipeline')}
            extra={t('pipeline.parentPipelineHelp')}
          >
            <Select
              allowClear
              placeholder={t('pipeline.parentPipelinePlaceholder')}
              onChange={handleParentPipelineChange}
            >
              {pipelines
                .filter(p => p.id !== editingPipeline?.id)
                .map(p => {
                  const depth = getPipelineDepth(p)
                  return (
                    <Select.Option key={p.id} value={p.id}>
                      <span style={{ paddingLeft: depth * 12 }}>
                        {depth > 0 && '└─ '}
                        {p.name}
                      </span>
                    </Select.Option>
                  )
                })}
            </Select>
          </Form.Item>

          {selectedParentPipeline && (
            <>
              <Form.Item
                name="expansion_mode"
                label={t('pipeline.expansionMode')}
                extra={t('pipeline.expansionModeHelp')}
              >
                <Select>
                  <Select.Option value="none">
                    <Tag>{t('pipeline.expansionNone')}</Tag>
                    <span style={{ marginLeft: 8, color: '#666' }}>{t('pipeline.expansionNoneDesc')}</span>
                  </Select.Option>
                  <Select.Option value="for_each_record">
                    <Tag color="purple">{t('pipeline.expansionForEachRecord')}</Tag>
                    <span style={{ marginLeft: 8, color: '#666' }}>{t('pipeline.expansionForEachRecordDesc')}</span>
                  </Select.Option>
                </Select>
              </Form.Item>

              <Form.List name="parameter_bindings">
                {(fields, { add, remove }) => (
                  <Form.Item
                    label={t('pipeline.parameterBindings')}
                    extra={t('pipeline.parameterBindingsHelp')}
                  >
                    {fields.map((field) => (
                      <Space key={field.key} style={{ display: 'flex', marginBottom: 8 }} align="baseline">
                        <Form.Item
                          {...field}
                          name={[field.name, 'parent_field']}
                          rules={[{ required: true, message: t('pipeline.parentFieldRequired') }]}
                          style={{ marginBottom: 0 }}
                        >
                          <Input placeholder={t('pipeline.parentFieldPlaceholder')} style={{ width: 150 }} />
                        </Form.Item>
                        <span style={{ margin: '0 8px' }}>→</span>
                        <Form.Item
                          {...field}
                          name={[field.name, 'child_param']}
                          rules={[{ required: true, message: t('pipeline.childParamRequired') }]}
                          style={{ marginBottom: 0 }}
                        >
                          <Input placeholder={t('pipeline.childParamPlaceholder')} style={{ width: 150 }} />
                        </Form.Item>
                        <Button type="link" danger onClick={() => remove(field.name)}>
                          {t('common.delete')}
                        </Button>
                      </Space>
                    ))}
                    <Button type="dashed" onClick={() => add({ parent_field: 'id', child_param: '' })} block>
                      <PlusOutlined /> {t('pipeline.addBinding')}
                    </Button>
                  </Form.Item>
                )}
              </Form.List>
            </>
          )}
        </Form>
      </Modal>

      {/* Execution Detail Modal */}
      <Modal
        title={t('workflow.executionDetail')}
        open={executionDetailVisible}
        onCancel={() => {
          setExecutionDetailVisible(false)
          setExecutionDetail(null)
        }}
        footer={[
          <Button key="close" onClick={() => {
            setExecutionDetailVisible(false)
            setExecutionDetail(null)
          }}>
            {t('common.close')}
          </Button>
        ]}
        width={900}
      >
        {executionDetailLoading ? (
          <div style={{ display: 'flex', justifyContent: 'center', padding: 40 }}>
            <Spin size="large" />
          </div>
        ) : executionDetail ? (
          <div>
            {/* Error Alert */}
            {executionDetail.error_message && (
              <Alert
                type="error"
                icon={<ExclamationCircleOutlined />}
                message={t('workflow.executionError')}
                description={executionDetail.error_message}
                style={{ marginBottom: 16 }}
                showIcon
              />
            )}

            {/* Execution Overview */}
            <Descriptions bordered column={2} size="small" style={{ marginBottom: 16 }}>
              <Descriptions.Item label={t('workflow.executionId')}>
                <code style={{ fontSize: 11 }}>{executionDetail.id}</code>
              </Descriptions.Item>
              <Descriptions.Item label={t('common.status')}>
                {(() => {
                  const statusConfig: Record<string, { color: string; icon: React.ReactNode; text: string }> = {
                    completed: { color: 'success', icon: <CheckCircleOutlined />, text: t('pipeline.status.completed') },
                    running: { color: 'processing', icon: <SyncOutlined spin />, text: t('pipeline.status.running') },
                    error: { color: 'error', icon: <CloseCircleOutlined />, text: t('pipeline.status.error') },
                    stopped: { color: 'default', icon: <StopOutlined />, text: t('pipeline.status.stopped') },
                  }
                  const config = statusConfig[executionDetail.status] || { color: 'default', icon: null, text: executionDetail.status }
                  return <Tag icon={config.icon} color={config.color}>{config.text}</Tag>
                })()}
              </Descriptions.Item>
              <Descriptions.Item label={t('workflow.startedAt')}>
                {new Date(executionDetail.started_at).toLocaleString()}
              </Descriptions.Item>
              <Descriptions.Item label={t('workflow.completedAt')}>
                {executionDetail.completed_at ? new Date(executionDetail.completed_at).toLocaleString() : '-'}
              </Descriptions.Item>
              <Descriptions.Item label={t('workflow.duration')}>
                {(() => {
                  if (!executionDetail.started_at) return '-'
                  const start = new Date(executionDetail.started_at).getTime()
                  const end = executionDetail.completed_at ? new Date(executionDetail.completed_at).getTime() : Date.now()
                  const duration = Math.round((end - start) / 1000)
                  if (duration < 60) return `${duration}s`
                  if (duration < 3600) return `${Math.floor(duration / 60)}m ${duration % 60}s`
                  return `${Math.floor(duration / 3600)}h ${Math.floor((duration % 3600) / 60)}m`
                })()}
              </Descriptions.Item>
              <Descriptions.Item label={t('workflow.triggeredBy')}>
                {executionDetail.triggered_by || '-'}
              </Descriptions.Item>
              <Descriptions.Item label={t('workflow.totalRecords')}>
                {executionDetail.total_records.toLocaleString()}
              </Descriptions.Item>
              <Descriptions.Item label={t('workflow.failedRecords')}>
                {executionDetail.failed_records > 0 ? (
                  <Text type="danger">{executionDetail.failed_records.toLocaleString()}</Text>
                ) : executionDetail.failed_records}
              </Descriptions.Item>
            </Descriptions>

            {/* Pipeline Results */}
            {executionDetail.pipeline_results && executionDetail.pipeline_results.length > 0 && (
              <Card title={t('workflow.pipelineResults')} size="small" style={{ marginBottom: 16 }}>
                <Table
                  dataSource={executionDetail.pipeline_results}
                  rowKey="pipeline_id"
                  size="small"
                  pagination={false}
                  columns={[
                    {
                      title: t('pipeline.name'),
                      dataIndex: 'pipeline_name',
                      key: 'pipeline_name',
                    },
                    {
                      title: t('common.status'),
                      dataIndex: 'status',
                      key: 'status',
                      width: 100,
                      render: (status: string) => {
                        const config: Record<string, { color: string; text: string }> = {
                          completed: { color: 'success', text: t('pipeline.status.completed') },
                          running: { color: 'processing', text: t('pipeline.status.running') },
                          error: { color: 'error', text: t('pipeline.status.error') },
                        }
                        const c = config[status] || { color: 'default', text: status }
                        return <Tag color={c.color}>{c.text}</Tag>
                      },
                    },
                    {
                      title: t('workflow.recordsRead'),
                      dataIndex: 'records_read',
                      key: 'records_read',
                      align: 'right' as const,
                      render: (v: number) => v?.toLocaleString() || 0,
                    },
                    {
                      title: t('workflow.recordsWritten'),
                      dataIndex: 'records_written',
                      key: 'records_written',
                      align: 'right' as const,
                      render: (v: number) => v?.toLocaleString() || 0,
                    },
                    {
                      title: t('workflow.failedRecords'),
                      dataIndex: 'records_failed',
                      key: 'records_failed',
                      align: 'right' as const,
                      render: (v: number) => v > 0 ? <Text type="danger">{v}</Text> : v || 0,
                    },
                    {
                      title: t('workflow.errorMessage'),
                      dataIndex: 'error_message',
                      key: 'error_message',
                      width: 300,
                      render: (msg: string) => msg ? (
                        <Text type="danger" style={{ whiteSpace: 'pre-wrap', wordBreak: 'break-word' }}>
                          {msg}
                        </Text>
                      ) : '-',
                    },
                  ]}
                />
              </Card>
            )}

            {/* Pipeline Configuration Snapshot */}
            {executionDetail.pipelines_snapshot && executionDetail.pipelines_snapshot.length > 0 && (
              <Card title={t('workflow.pipelineConfigSnapshot')} size="small">
                <Text type="secondary" style={{ display: 'block', marginBottom: 12 }}>
                  {t('workflow.pipelineConfigSnapshotHelp')}
                </Text>
                <Collapse>
                  {executionDetail.pipelines_snapshot.map((pipeline, index) => (
                    <Collapse.Panel
                      header={
                        <Space>
                          <span>{pipeline.name}</span>
                          <Tag>{pipeline.source?.type || 'unknown'}</Tag>
                          {pipeline.stages && pipeline.stages.length > 0 && (
                            <Tag color="blue">{pipeline.stages.length} {t('stage.title')}</Tag>
                          )}
                        </Space>
                      }
                      key={pipeline.id || index}
                    >
                      {/* Source Config */}
                      <Descriptions title={t('source.title')} bordered column={1} size="small" style={{ marginBottom: 16 }}>
                        <Descriptions.Item label={t('source.type')}>
                          <Tag>{pipeline.source?.type}</Tag>
                        </Descriptions.Item>
                        <Descriptions.Item label={t('source.config')}>
                          <pre style={{ margin: 0, fontSize: 11, maxHeight: 200, overflow: 'auto', background: '#f5f5f5', padding: 8, borderRadius: 4 }}>
                            {JSON.stringify(pipeline.source?.config || {}, null, 2)}
                          </pre>
                        </Descriptions.Item>
                      </Descriptions>

                      {/* Stages */}
                      {pipeline.stages && pipeline.stages.length > 0 && (
                        <div style={{ marginBottom: 16 }}>
                          <Title level={5}>{t('stage.title')}</Title>
                          <Table
                            dataSource={pipeline.stages}
                            rowKey={(_, idx) => String(idx)}
                            size="small"
                            pagination={false}
                            columns={[
                              {
                                title: t('stage.name'),
                                dataIndex: 'name',
                                key: 'name',
                                width: 150,
                              },
                              {
                                title: t('stage.type'),
                                dataIndex: 'type',
                                key: 'type',
                                width: 100,
                                render: (type: string) => <Tag>{type}</Tag>,
                              },
                              {
                                title: t('stage.config'),
                                dataIndex: 'config',
                                key: 'config',
                                render: (config: Record<string, unknown>) => (
                                  <pre style={{ margin: 0, fontSize: 10, maxHeight: 100, overflow: 'auto', background: '#f5f5f5', padding: 4, borderRadius: 4 }}>
                                    {JSON.stringify(config || {}, null, 2)}
                                  </pre>
                                ),
                              },
                            ]}
                          />
                        </div>
                      )}

                    </Collapse.Panel>
                  ))}
                </Collapse>
              </Card>
            )}
          </div>
        ) : (
          <Empty description={t('workflow.noExecutionDetail')} />
        )}
      </Modal>
    </div>
  )
}
