// Copyright 2026 Conduix Authors
// Plugin Architecture V3 - Go Native Build System
// gRPC service for plugin stage execution via HashiCorp go-plugin

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/plugin/v1/plugin.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Record represents a single data record in the pipeline.
type Record struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-serialized data payload (map[string]any)
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// Optional metadata key-value pairs
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *Record) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Record) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// InitRequest contains stage configuration.
type InitRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-serialized config from pipeline definition
	Config []byte `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	// Stage type identifier
	StageType     string `protobuf:"bytes,2,opt,name=stage_type,json=stageType,proto3" json:"stage_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *InitRequest) GetConfig() []byte {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *InitRequest) GetStageType() string {
	if x != nil {
		return x.StageType
	}
	return ""
}

// InitResponse returns initialization result.
type InitResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Empty on success, error message on failure
	Error         string `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *InitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// ProcessBatchRequest contains a batch of records to process.
type ProcessBatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessBatchRequest) Reset() {
	*x = ProcessBatchRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessBatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessBatchRequest) ProtoMessage() {}

func (x *ProcessBatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessBatchRequest.ProtoReflect.Descriptor instead.
func (*ProcessBatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *ProcessBatchRequest) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// ProcessBatchResponse contains the processed results.
type ProcessBatchResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// Number of records filtered out (not included in records)
	FilteredCount int32 `protobuf:"varint,2,opt,name=filtered_count,json=filteredCount,proto3" json:"filtered_count,omitempty"`
	// Non-fatal error message (processing continues)
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ProcessBatchResponse) Reset() {
	*x = ProcessBatchResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProcessBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProcessBatchResponse) ProtoMessage() {}

func (x *ProcessBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProcessBatchResponse.ProtoReflect.Descriptor instead.
func (*ProcessBatchResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *ProcessBatchResponse) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *ProcessBatchResponse) GetFilteredCount() int32 {
	if x != nil {
		return x.FilteredCount
	}
	return 0
}

func (x *ProcessBatchResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// CloseRequest is empty.
type CloseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseRequest) Reset() {
	*x = CloseRequest{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseRequest) ProtoMessage() {}

func (x *CloseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseRequest.ProtoReflect.Descriptor instead.
func (*CloseRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{5}
}

// CloseResponse returns shutdown result.
type CloseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CloseResponse) Reset() {
	*x = CloseResponse{}
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CloseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CloseResponse) ProtoMessage() {}

func (x *CloseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_v1_plugin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CloseResponse.ProtoReflect.Descriptor instead.
func (*CloseResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_v1_plugin_proto_rawDescGZIP(), []int{6}
}

func (x *CloseResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_proto_plugin_v1_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_v1_plugin_proto_rawDesc = "" +
	"\n" +
	"\x1cproto/plugin/v1/plugin.proto\x12\x11conduix.plugin.v1\"\x9e\x01\n" +
	"\x06Record\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12C\n" +
	"\bmetadata\x18\x02 \x03(\v2'.conduix.plugin.v1.Record.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"D\n" +
	"\vInitRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\fR\x06config\x12\x1d\n" +
	"\n" +
	"stage_type\x18\x02 \x01(\tR\tstageType\"$\n" +
	"\fInitResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"J\n" +
	"\x13ProcessBatchRequest\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.conduix.plugin.v1.RecordR\arecords\"\x88\x01\n" +
	"\x14ProcessBatchResponse\x123\n" +
	"\arecords\x18\x01 \x03(\v2\x19.conduix.plugin.v1.RecordR\arecords\x12%\n" +
	"\x0efiltered_count\x18\x02 \x01(\x05R\rfilteredCount\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x0e\n" +
	"\fCloseRequest\"%\n" +
	"\rCloseResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error2\x83\x02\n" +
	"\vStagePlugin\x12G\n" +
	"\x04Init\x12\x1e.conduix.plugin.v1.InitRequest\x1a\x1f.conduix.plugin.v1.InitResponse\x12_\n" +
	"\fProcessBatch\x12&.conduix.plugin.v1.ProcessBatchRequest\x1a'.conduix.plugin.v1.ProcessBatchResponse\x12J\n" +
	"\x05Close\x12\x1f.conduix.plugin.v1.CloseRequest\x1a .conduix.plugin.v1.CloseResponseB-Z+github.com/conduix/conduix/plugin-sdk/protob\x06proto3"

var (
	file_proto_plugin_v1_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_v1_plugin_proto_rawDescData []byte
)

func file_proto_plugin_v1_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_v1_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_v1_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_v1_plugin_proto_rawDescData
}

var file_proto_plugin_v1_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_plugin_v1_plugin_proto_goTypes = []any{
	(*Record)(nil),               // 0: conduix.plugin.v1.Record
	(*InitRequest)(nil),          // 1: conduix.plugin.v1.InitRequest
	(*InitResponse)(nil),         // 2: conduix.plugin.v1.InitResponse
	(*ProcessBatchRequest)(nil),  // 3: conduix.plugin.v1.ProcessBatchRequest
	(*ProcessBatchResponse)(nil), // 4: conduix.plugin.v1.ProcessBatchResponse
	(*CloseRequest)(nil),         // 5: conduix.plugin.v1.CloseRequest
	(*CloseResponse)(nil),        // 6: conduix.plugin.v1.CloseResponse
	nil,                          // 7: conduix.plugin.v1.Record.MetadataEntry
}
var file_proto_plugin_v1_plugin_proto_depIdxs = []int32{
	7, // 0: conduix.plugin.v1.Record.metadata:type_name -> conduix.plugin.v1.Record.MetadataEntry
	0, // 1: conduix.plugin.v1.ProcessBatchRequest.records:type_name -> conduix.plugin.v1.Record
	0, // 2: conduix.plugin.v1.ProcessBatchResponse.records:type_name -> conduix.plugin.v1.Record
	1, // 3: conduix.plugin.v1.StagePlugin.Init:input_type -> conduix.plugin.v1.InitRequest
	3, // 4: conduix.plugin.v1.StagePlugin.ProcessBatch:input_type -> conduix.plugin.v1.ProcessBatchRequest
	5, // 5: conduix.plugin.v1.StagePlugin.Close:input_type -> conduix.plugin.v1.CloseRequest
	2, // 6: conduix.plugin.v1.StagePlugin.Init:output_type -> conduix.plugin.v1.InitResponse
	4, // 7: conduix.plugin.v1.StagePlugin.ProcessBatch:output_type -> conduix.plugin.v1.ProcessBatchResponse
	6, // 8: conduix.plugin.v1.StagePlugin.Close:output_type -> conduix.plugin.v1.CloseResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_plugin_v1_plugin_proto_init() }
func file_proto_plugin_v1_plugin_proto_init() {
	if File_proto_plugin_v1_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_v1_plugin_proto_rawDesc), len(file_proto_plugin_v1_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_v1_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_v1_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_v1_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_v1_plugin_proto = out.File
	file_proto_plugin_v1_plugin_proto_goTypes = nil
	file_proto_plugin_v1_plugin_proto_depIdxs = nil
}
