// Copyright 2026 Conduix Authors
// Plugin Architecture V3 - Go Native Build System
// gRPC service for plugin stage execution via HashiCorp go-plugin

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/plugin/v1/plugin.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StagePlugin_Init_FullMethodName         = "/conduix.plugin.v1.StagePlugin/Init"
	StagePlugin_ProcessBatch_FullMethodName = "/conduix.plugin.v1.StagePlugin/ProcessBatch"
	StagePlugin_Close_FullMethodName        = "/conduix.plugin.v1.StagePlugin/Close"
)

// StagePluginClient is the client API for StagePlugin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// StagePlugin is the gRPC service that plugin binaries implement.
// Pipeline Runner calls this service via HashiCorp go-plugin (unix socket).
type StagePluginClient interface {
	// Init initializes the stage with configuration.
	// Called once when the plugin process starts.
	Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error)
	// ProcessBatch processes a batch of records.
	// This is the main data processing method, called repeatedly.
	ProcessBatch(ctx context.Context, in *ProcessBatchRequest, opts ...grpc.CallOption) (*ProcessBatchResponse, error)
	// Close gracefully shuts down the stage.
	// Called when the pipeline stops.
	Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error)
}

type stagePluginClient struct {
	cc grpc.ClientConnInterface
}

func NewStagePluginClient(cc grpc.ClientConnInterface) StagePluginClient {
	return &stagePluginClient{cc}
}

func (c *stagePluginClient) Init(ctx context.Context, in *InitRequest, opts ...grpc.CallOption) (*InitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitResponse)
	err := c.cc.Invoke(ctx, StagePlugin_Init_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePluginClient) ProcessBatch(ctx context.Context, in *ProcessBatchRequest, opts ...grpc.CallOption) (*ProcessBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ProcessBatchResponse)
	err := c.cc.Invoke(ctx, StagePlugin_ProcessBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stagePluginClient) Close(ctx context.Context, in *CloseRequest, opts ...grpc.CallOption) (*CloseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CloseResponse)
	err := c.cc.Invoke(ctx, StagePlugin_Close_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StagePluginServer is the server API for StagePlugin service.
// All implementations must embed UnimplementedStagePluginServer
// for forward compatibility.
//
// StagePlugin is the gRPC service that plugin binaries implement.
// Pipeline Runner calls this service via HashiCorp go-plugin (unix socket).
type StagePluginServer interface {
	// Init initializes the stage with configuration.
	// Called once when the plugin process starts.
	Init(context.Context, *InitRequest) (*InitResponse, error)
	// ProcessBatch processes a batch of records.
	// This is the main data processing method, called repeatedly.
	ProcessBatch(context.Context, *ProcessBatchRequest) (*ProcessBatchResponse, error)
	// Close gracefully shuts down the stage.
	// Called when the pipeline stops.
	Close(context.Context, *CloseRequest) (*CloseResponse, error)
	mustEmbedUnimplementedStagePluginServer()
}

// UnimplementedStagePluginServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStagePluginServer struct{}

func (UnimplementedStagePluginServer) Init(context.Context, *InitRequest) (*InitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Init not implemented")
}
func (UnimplementedStagePluginServer) ProcessBatch(context.Context, *ProcessBatchRequest) (*ProcessBatchResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ProcessBatch not implemented")
}
func (UnimplementedStagePluginServer) Close(context.Context, *CloseRequest) (*CloseResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Close not implemented")
}
func (UnimplementedStagePluginServer) mustEmbedUnimplementedStagePluginServer() {}
func (UnimplementedStagePluginServer) testEmbeddedByValue()                     {}

// UnsafeStagePluginServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StagePluginServer will
// result in compilation errors.
type UnsafeStagePluginServer interface {
	mustEmbedUnimplementedStagePluginServer()
}

func RegisterStagePluginServer(s grpc.ServiceRegistrar, srv StagePluginServer) {
	// If the following call panics, it indicates UnimplementedStagePluginServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StagePlugin_ServiceDesc, srv)
}

func _StagePlugin_Init_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).Init(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePlugin_Init_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).Init(ctx, req.(*InitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePlugin_ProcessBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProcessBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).ProcessBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePlugin_ProcessBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).ProcessBatch(ctx, req.(*ProcessBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StagePlugin_Close_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CloseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StagePluginServer).Close(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StagePlugin_Close_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StagePluginServer).Close(ctx, req.(*CloseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StagePlugin_ServiceDesc is the grpc.ServiceDesc for StagePlugin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StagePlugin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "conduix.plugin.v1.StagePlugin",
	HandlerType: (*StagePluginServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Init",
			Handler:    _StagePlugin_Init_Handler,
		},
		{
			MethodName: "ProcessBatch",
			Handler:    _StagePlugin_ProcessBatch_Handler,
		},
		{
			MethodName: "Close",
			Handler:    _StagePlugin_Close_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/plugin/v1/plugin.proto",
}
