import type { Stage, RealtimePipelineMode } from '../types/pipeline'

// 자동 생성 스테이지 이름들 (제거 시 사용)
const AUTO_GENERATED_STAGE_NAMES = {
  batch: ['default_filter', 'default_dedupe'],
  raw: ['default_filter'],
  cdc: ['event_router', 'delete_handler'],
}

/**
 * 배치 파이프라인 기본 스테이지 생성
 * - filter: 기본 필터 스테이지
 * - dedupe: 중복 제거 스테이지
 */
export function createBatchDefaultStages(): Stage[] {
  return [
    {
      id: crypto.randomUUID(),
      name: 'default_filter',
      type: 'filter',
      config: {
        condition: 'true', // 기본값: 모든 레코드 통과
      },
    },
    {
      id: crypto.randomUUID(),
      name: 'default_dedupe',
      type: 'dedupe',
      config: {
        key_fields: ['id'],
        strategy: 'keep_last',
      },
    },
  ]
}

/**
 * 실시간 Raw 모드 기본 스테이지 생성
 * - filter: 기본 필터 스테이지
 */
export function createRawDefaultStages(): Stage[] {
  return [
    {
      id: crypto.randomUUID(),
      name: 'default_filter',
      type: 'filter',
      config: {
        condition: 'true', // 기본값: 모든 레코드 통과
      },
    },
  ]
}

/**
 * 실시간 CDC 모드 기본 스테이지 생성
 * - event_router: insert/update와 delete 이벤트 분리
 * - delete_handler: 삭제 이벤트 처리 (논리적 삭제)
 */
export function createCdcDefaultStages(): Stage[] {
  return [
    {
      id: crypto.randomUUID(),
      name: 'event_router',
      type: 'route',
      config: {
        field: '_op',
        routes: [
          {
            match: ['insert', 'update'],
            target: 'main_flow',
          },
          {
            match: ['delete'],
            target: 'delete_flow',
          },
        ],
      },
    },
    {
      id: crypto.randomUUID(),
      name: 'delete_handler',
      type: 'delete',
      config: {
        mode: 'logical',
        logical: {
          field: 'deleted_at',
          value: '$now',
        },
      },
    },
  ]
}

/**
 * 파이프라인 타입과 모드에 따라 기본 스테이지 생성
 */
export function createDefaultStages(
  workflowType: 'batch' | 'realtime',
  realtimeMode?: RealtimePipelineMode
): Stage[] {
  if (workflowType === 'batch') {
    return createBatchDefaultStages()
  }

  // realtime
  if (realtimeMode === 'cdc') {
    return createCdcDefaultStages()
  }

  return createRawDefaultStages()
}

/**
 * 자동 생성된 스테이지 이름 목록 반환
 */
export function getAutoGeneratedStageNames(
  workflowType: 'batch' | 'realtime',
  realtimeMode?: RealtimePipelineMode
): string[] {
  if (workflowType === 'batch') {
    return AUTO_GENERATED_STAGE_NAMES.batch
  }

  if (realtimeMode === 'cdc') {
    return AUTO_GENERATED_STAGE_NAMES.cdc
  }

  return AUTO_GENERATED_STAGE_NAMES.raw
}

/**
 * 모든 자동 생성 스테이지 이름 목록 반환
 */
export function getAllAutoGeneratedStageNames(): string[] {
  return [
    ...AUTO_GENERATED_STAGE_NAMES.batch,
    ...AUTO_GENERATED_STAGE_NAMES.raw,
    ...AUTO_GENERATED_STAGE_NAMES.cdc,
  ]
}

/**
 * 스테이지 목록에서 자동 생성 스테이지 제거
 */
export function removeAutoGeneratedStages(stages: Stage[]): Stage[] {
  const allAutoNames = getAllAutoGeneratedStageNames()
  return stages.filter(s => !allAutoNames.includes(s.name))
}

/**
 * 스테이지가 자동 생성된 것인지 확인
 */
export function isAutoGeneratedStage(stage: Stage): boolean {
  return getAllAutoGeneratedStageNames().includes(stage.name)
}
